/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_EDIT_0 (GUI_ID_USER + 0x02)
#define ID_BUTTON_0 (GUI_ID_USER + 0x0F)
#define ID_BUTTON_1 (GUI_ID_USER + 0x10)
#define ID_BUTTON_2 (GUI_ID_USER + 0x11)
#define ID_BUTTON_3 (GUI_ID_USER + 0x12)
#define ID_BUTTON_4 (GUI_ID_USER + 0x13)
#define ID_BUTTON_5 (GUI_ID_USER + 0x14)
#define ID_BUTTON_6 (GUI_ID_USER + 0x15)
#define ID_BUTTON_7 (GUI_ID_USER + 0x16)
#define ID_BUTTON_8 (GUI_ID_USER + 0x17)
#define ID_BUTTON_9 (GUI_ID_USER + 0x0E)
#define ID_BUTTON_10 (GUI_ID_USER + 0x19)
#define ID_BUTTON_11 (GUI_ID_USER + 0x1A)
#define ID_BUTTON_12 (GUI_ID_USER + 0x1B)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
//static u16 _PIN_Value;  //存放密码
//static u8 _PIN_Digits;  //密码位数

// USER START (Optionally insert additional static data)
// USER END
typedef struct 
{
	u8 Item;        //表示选中第几项
	u8 _PIN_Digits; //输入密码个数
//	u8  _Lock_sta;
	u8  _RUN_sta;   //状态转换
	u16 _PIN_Value;  //输入的密码
	u16 _Old_PIN;
	u16 _New_PIN;    //存储新密码
	
}Pass_set;

static Pass_set Pass_data; //只用于此页面处理数据
static System_Second_Data* Pass_Second;

//此函数用来获得第二界面指针数据
void Get_Sys_Second (System_Second_Data* L)
{
	Pass_Second = L;
//	Pass_data._Lock_sta = Pass_Second->_Lock_sta;
	Pass_data._Old_PIN  = Pass_Second->data._Old_PIN;
	Pass_data._PIN_Digits = Pass_Second->_PIN_Digits;
	Pass_data._PIN_Value = Pass_Second->_PIN_Value;
	Pass_data.Item     =   Pass_Second->Item;
	Pass_data._RUN_sta = 0;  //初始状态
}

//用来获取第三界面指针数据
void Get_Sys_Third ()
{
	
}

//返回是否开锁标志位
u16 Return_PIN(void)
{
	return Pass_data._New_PIN;
}


/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 400, 240, 0, 0x64, 0 },
	{ EDIT_CreateIndirect, "Edit", ID_EDIT_0, 156, 6, 80, 26, 0, 0x64, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 13, 45, 80, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 104, 45, 80, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 200, 45, 80, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_10, 292, 45, 80, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 13, 85, 80, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 104, 85, 80, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 200, 85, 80, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_11, 292, 85, 80, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_6, 13, 124, 80, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_7, 104, 124, 80, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_8, 200, 124, 80, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_12, 292, 124, 80, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_9, 104, 164, 80, 35, 0, 0x0, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	int     NCode;
	int     Id;
	GUI_RECT r;
	// USER START (Optionally insert additional variables)
	// USER END

	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		//
		// Initialization of 'Framewin'
		//
		hItem = pMsg->hWin;
		FRAMEWIN_SetTitleHeight(hItem, 30);
		if(Pass_data.Item == 1)
		{
			FRAMEWIN_SetText(hItem, "Please enter Old four PIN :");
		}
		else
		{
			FRAMEWIN_SetText(hItem, "Please enter four PIN :");
		}
		FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		FRAMEWIN_SetFont(hItem, GUI_FONT_20B_1);
		//
		// Initialization of 'Edit'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		WIDGET_SetEffect(hItem, &WIDGET_Effect_3D2L);  //3D效果显示
		EDIT_SetFont(hItem, GUI_FONT_24B_1);
		WM_DisableWindow(hItem);  //禁止窗口
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetFont(hItem, GUI_FONT_24B_1);
		BUTTON_SetText(hItem, "1");
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetFont(hItem, GUI_FONT_24B_1);
		BUTTON_SetText(hItem, "2");
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		BUTTON_SetFont(hItem, GUI_FONT_24B_1);
		BUTTON_SetText(hItem, "3");
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
		BUTTON_SetText(hItem, "Del");
		BUTTON_SetFont(hItem, GUI_FONT_20B_1);
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		BUTTON_SetFont(hItem, GUI_FONT_24B_1);
		BUTTON_SetText(hItem, "4");
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		BUTTON_SetText(hItem, "5");
		BUTTON_SetFont(hItem, GUI_FONT_24B_1);
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		BUTTON_SetFont(hItem, GUI_FONT_24B_1);
		BUTTON_SetText(hItem, "6");
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
		BUTTON_SetFont(hItem, GUI_FONT_20B_1);
		BUTTON_SetText(hItem, "Cancel");
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		BUTTON_SetFont(hItem, GUI_FONT_24B_1);
		BUTTON_SetText(hItem, "7");
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
		BUTTON_SetFont(hItem, GUI_FONT_24B_1);
		BUTTON_SetText(hItem, "8");
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
		BUTTON_SetFont(hItem, GUI_FONT_24B_1);
		BUTTON_SetText(hItem, "9");
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
		BUTTON_SetFont(hItem, GUI_FONT_20B_1);
		BUTTON_SetText(hItem, "Confirm");
		WM_DisableWindow(hItem);  //禁止窗口
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
		BUTTON_SetFont(hItem, GUI_FONT_24B_1);
		BUTTON_SetText(hItem, "0");
		// USER START (Optionally insert additional code for further widget initialization)
		// USER END
		break;
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
		case ID_EDIT_0: // Notifications sent by 'Edit'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_0: // Notifications sent by 'Button'
		case ID_BUTTON_1: // Notifications sent by 'Button'
		case ID_BUTTON_2: // Notifications sent by 'Button'
		case ID_BUTTON_3: // Notifications sent by 'Button'
		case ID_BUTTON_4: // Notifications sent by 'Button'
		case ID_BUTTON_5: // Notifications sent by 'Button'
		case ID_BUTTON_6: // Notifications sent by 'Button'
		case ID_BUTTON_7: // Notifications sent by 'Button'
		case ID_BUTTON_8: // Notifications sent by 'Button'
		case ID_BUTTON_9: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				
				if(Pass_data._PIN_Digits < 4)
				{
					Pass_data._PIN_Value = (Pass_data._PIN_Value * 10) + (Id - ID_BUTTON_9);
					Pass_data._PIN_Digits++;
					WM_SendMessageNoPara(WM_GetClientWindow(pMsg->hWin),MSG_PIN_CHANGED);
				}
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		
		case ID_BUTTON_10: // Notifications sent by 'Button'--DEL
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				if(Pass_data._PIN_Digits)
				{
					Pass_data._PIN_Value /= 10;
					Pass_data._PIN_Digits--;
					WM_SendMessageNoPara(WM_GetClientWindow(pMsg->hWin),MSG_PIN_CHANGED);
				}
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_11: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
				
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_12: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				//先判断处于什么状态
				if(Pass_data._RUN_sta == 0)  //初始状态
				{
					if (Pass_data._PIN_Value == Pass_data._Old_PIN)
					{
						WM_SendMessageNoPara(WM_GetClientWindow(pMsg->hWin), MSG_PIN_OK);
					}
					else
					{
						WM_SendMessageNoPara(WM_GetClientWindow(pMsg->hWin), MSG_PIN_ERROR);
					}
				}
				else if(Pass_data._RUN_sta == 1)
				{
					//存储新密码
					Pass_data._Old_PIN = Pass_data._PIN_Value;
					WM_SendMessageNoPara(WM_GetClientWindow(pMsg->hWin), MSG_PIN_OK);
				}
				else if(Pass_data._RUN_sta == 2)
				{
					//比较新密码是否正确
					if(Pass_data._PIN_Value == Pass_data._Old_PIN)
					{
						WM_SendMessageNoPara(WM_GetClientWindow(pMsg->hWin), MSG_PIN_OK);
					}
					else
					{
						WM_SendMessageNoPara(WM_GetClientWindow(pMsg->hWin), MSG_PIN_ERROR);
					}
				}
			
//				if (Pass_data._PIN_Value == Pass_data._Old_PIN)
//				{
//					WM_SendMessageNoPara(WM_GetClientWindow(pMsg->hWin), MSG_PIN_OK);
//				}
//				else
//				{
//					WM_SendMessageNoPara(WM_GetClientWindow(pMsg->hWin), MSG_PIN_ERROR);
//				}
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
			// USER START (Optionally insert additional code for further Ids)
			// USER END
		}
		break;
		// USER START (Optionally insert additional message handling)
		// USER END
	case WM_PAINT:
		WM_GetClientRect(&r);
		GUI_SetBkColor(GUI_LIGHTGRAY);
		GUI_Clear();
		//_DrawUpRectEx(&WIDGET_Effect_3D2L, &r);
		WIDGET_Effect_3D2L.pfDrawUpRect(&r); //使用3D效果
		break;
	/******************************自定义信息********************/
	case MSG_PIN_CHANGED:
		if (Pass_data._PIN_Digits == 0) 
			{
				EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0), "");
				if(WM_HasFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12)))
				{
					WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0));
				}
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12));
			} 
			else if (Pass_data._PIN_Digits == 1) 
			{
				EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0), "x");
			} 
			else if (Pass_data._PIN_Digits == 2) 
			{
				EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0), "xx");
			} 
			else if (Pass_data._PIN_Digits == 3) 
			{
				EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0), "xxx");
				WM_DisableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12));
			} else if (Pass_data._PIN_Digits == 4) 
			{
				EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0), "xxxx");
				WM_EnableWindow(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12));
				
			}
			
		break;
			
	case MSG_PIN_OK:
		
		if(Pass_data.Item == 1)
		{
			Pass_data._RUN_sta ++;  //下一个状态
			if(Pass_data._RUN_sta == 1)
			{
				FRAMEWIN_SetText(pMsg->hWin, "Please enter New PIN :");
				Pass_data._PIN_Digits = 0;
				Pass_data._PIN_Value = 0;
				WM_SendMessageNoPara(WM_GetClientWindow(pMsg->hWin),MSG_PIN_CHANGED);
			}
			else if(Pass_data._RUN_sta == 2)
			{
				FRAMEWIN_SetText(pMsg->hWin, "Please enter New PIN again :");
				Pass_data._PIN_Digits = 0;
				Pass_data._PIN_Value = 0;
				WM_SendMessageNoPara(WM_GetClientWindow(pMsg->hWin),MSG_PIN_CHANGED);
			}
			else if(Pass_data._RUN_sta == 3)
			{
				Pass_data._New_PIN = Pass_data._Old_PIN;
				GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
				WM_SendMessageNoPara(hWin_now,MSG_PIN_NEW); //发送改密码成功信息
			}
		}
		else
		{
			
			GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
			WM_SendMessageNoPara(hWin_now,MSG_PIN_UNLOCK); //发送解锁成功信息
		}
		break;

	case MSG_PIN_ERROR:
		if(Pass_data._RUN_sta == 2)
		{
			FRAMEWIN_SetText(pMsg->hWin, "Please enter New PIN :");
			Pass_data._PIN_Digits = 0;
			Pass_data._PIN_Value = 0;
			Pass_data._RUN_sta = 1;
			
		}
		hItem = CreateMessge();
		WM_MakeModal(hItem);
		break;
	
	/*********************************按键处理******************************************/
	case WM_KEY:
		switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) //获得关于按键信息的值
		{
			//ESC
			case GUI_KEY_ESCAPE:
            GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
            break;
		}
		break;
	
	//删除窗口前清除数据
	case WM_DELETE:
//		Pass_data._PIN_Digits = 0;
//		Pass_data._PIN_Value = 0;
		Button_flex_2();
		WM_InvalidateWindow(hWin_now);  //表示要重新刷新页面
		WM_SetFocus(hWin_now);          //重新聚焦
		break;
			
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

WM_HWIN CreatePIN(void) {
	WM_HWIN hWin;
	
	Button_flex();

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);

	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
#define  ID_FRAMEWIN_1   (GUI_ID_USER + 0X1C)
#define  ID_TEXT_0		(GUI_ID_USER + 0X1D)
#define  ID_BUTTON_13	(GUI_ID_USER + 0X1E)

static const GUI_WIDGET_CREATE_INFO _aDialogMessge[] = {
	{ FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_1, 80, 40, 232, 134, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_0, 4, 14, 217, 35, 0, 0x64, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_13, 71, 56, 80, 32, 0, 0x0, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};


static void _cbDialogMessge(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	int     NCode;
	int     Id;
	// USER START (Optionally insert additional variables)
	// USER END

	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		//
		// Initialization of 'Framewin'
		//
		hItem = pMsg->hWin;
		FRAMEWIN_SetTitleHeight(hItem, 30);
		FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		FRAMEWIN_SetText(hItem, "Wrong PIN");
		FRAMEWIN_SetFont(hItem, GUI_FONT_24B_1);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem, "Input password error , try again !");
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
		BUTTON_SetText(hItem, "OK");
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);
		// USER START (Optionally insert additional code for further widget initialization)
		// USER END
		break;
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
		case ID_BUTTON_13: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				hItem = WM_GetPrevSibling(pMsg->hWin);  //得到前一窗口
				GUI_EndDialog(pMsg->hWin,1);
				WM_SetFocus(WM_GetPrevSibling(pMsg->hWin)); //聚焦前一层窗口
				Pass_data._PIN_Digits = 0;
				Pass_data._PIN_Value = 0;
				WM_SendMessageNoPara(WM_GetClientWindow(hItem),MSG_PIN_CHANGED);
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
			// USER START (Optionally insert additional code for further Ids)
			// USER END
		}
		break;
		// USER START (Optionally insert additional message handling)
		// USER END

	default:
		WM_DefaultProc(pMsg);
		break;
	}
}


WM_HWIN CreateMessge(void) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogMessge, GUI_COUNTOF(_aDialogMessge), _cbDialogMessge, WM_HBKWIN, 0, 0);
	return hWin;
}


