/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "data.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_1 (GUI_ID_USER + 0x02)
#define ID_BUTTON_2 (GUI_ID_USER + 0x03)
#define ID_BUTTON_3 (GUI_ID_USER + 0x04)
#define ID_BUTTON_4 (GUI_ID_USER + 0x05)
#define ID_BUTTON_5 (GUI_ID_USER + 0x06)

#define ID_TEXT_0	(GUI_ID_USER + 0x07)
#define ID_TEXT_1	(GUI_ID_USER + 0x08)
#define ID_BUTTON_6 (GUI_ID_USER + 0x09)
#define ID_BUTTON_7 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_8 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_9 (GUI_ID_USER + 0x0C)
#define ID_BUTTON_10 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_11 (GUI_ID_USER + 0x0E)
#define ID_BUTTON_12 (GUI_ID_USER + 0x0F)
#define ID_BUTTON_13 (GUI_ID_USER + 0x10)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static Mode_First_Data * Current_Data;
// USER START (Optionally insert additional static data)
// USER END
#define dec_size 40
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 400, 240, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 0, 68, 198, 40, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 0, 112, 198, 40, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 0, 155, 198, 40, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 0, 198, 130, 40, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 134, 198, 130, 40, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 268, 198, 130, 40, 0, 0x0, 0 },

	//TEXT
	{ TEXT_CreateIndirect, "Text", ID_TEXT_0, 109, 3, 194, 28, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_1, 59, 36, 294, 28, 0, 0, 0 },

	//增减按钮
	//left
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_6, 208, 75, dec_size, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_7, 208, 118, dec_size, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_8, 208, 162, dec_size, 25, 0, 0x0, 0 },

	//right
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_9, 170  + 180, 75,  dec_size, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_10, 170 + 180, 118, dec_size, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_11, 170 + 180, 162, dec_size, 25, 0, 0x0, 0 },
	
	/*页面切换*/
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_12, 5, 5, dec_size, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_13, 375-20, 5, dec_size, 25, 0, 0x0, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
static const GUI_POINT pPoint_left[] = {
	{ 0, 10 },
	{ 10, 0 },
	{ 10, 20 },
};

static const GUI_POINT pPoint_right[] = {
	{ 10+20, 0 },
	{ 20+20, 10 },
	{ 10+20, 20 },
};

//定义无效区域
static const GUI_RECT Rect[] = {
	{ 250, 		70, 	350, 	100 }, 
	{ 250, 		115, 	350, 	145 },
	{ 250, 		160, 	350, 	190 },
};

//左边三角形
static void _cbButton_left(WM_MESSAGE * pMsg) //--------------（3）
{
	WM_HWIN hWin;
	hWin = pMsg->hWin;
	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		if (BUTTON_IsPressed(hWin))
		{
			//画红色三角形
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_left, 3, 0, 0);
		}
		else
		{
			//画黑色三角形
			GUI_SetColor(GUI_BLACK);
			GUI_FillPolygon(pPoint_left, 3, 0, 0);
		}

		break;

		//处理默认信息
	default:
		BUTTON_Callback(pMsg);
	}
}

#include "BUTTON_Private.h"
//右边三角形
#define BUTTON_H2P(h) (BUTTON_Obj*) GUI_ALLOC_h2p(h)

static void _cbButton_right(WM_MESSAGE * pMsg) //--------------（3）
{
	WM_HWIN hWin;
	BUTTON_Obj * pObj; //用来提取出按钮的指针结构体，包含了各种信息

	//	const GUI_PID_STATE* pState = (const GUI_PID_STATE*)pMsg->Data.p;
	hWin = pMsg->hWin;
	pObj = BUTTON_H2P(hWin);

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		if (BUTTON_IsPressed(hWin))
		{
			//画红色三角形
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}
		else
		{
			//画黑色三角形
			GUI_SetColor(GUI_BLACK);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}

		//绘制聚焦,如果不接受聚焦则此项不起作用
		if (pObj->Widget.State & WIDGET_STATE_FOCUS)
		{
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}
		break;


		//case WM_TOUCH:
		//	if (pMsg->Data.p) {  /* Something happened in our area (pressed or released) */
		//		if (pState->Pressed) {
		//			RMSTC_Value++;
		//			WIDGET_OrState(hWin, BUTTON_STATE_PRESSED);
		//			WM_NotifyParent(hWin, WM_NOTIFICATION_CLICKED);
		//		}
		//		else {
		//			/* React only if button was pressed before ... avoid problems with moving / hiding windows above (such as dropdown) */
		//			
		//		}
		//	}
		//	else {
		//		
		//	}
		//	break;
		//处理默认信息
	default:
		BUTTON_Callback(pMsg);
	}
}

/******************************Show_Value 所需数据*****************************/
#include "stdio.h"

#define LOAD_X  300
#define LOAD_Y  77

static const char mode_string[][10] = 
{
	"MODE_0",
	"MODE_1",
	"MODE_2",
	"MODE_3",
	"MODE_4",
	"MODE_5",
	"MODE_6",
	"MODE_7",
	"MODE_8",
	"MODE_9",
};
/*
*******************************************************************************************
* 函 数 名: Show_Value
* 功能说明: 显示数值
* 形 参: 无
* 返 回 值: 无
*******************************************************************************************
*/
#define MODE_MAX  	9
#define MODE_MIN	0
#include "string.h"

static void Show_Value(void)
{
	char str[10];
	char over;
	GUI_SetColor(GUI_BLACK);
	GUI_SetTextMode(GUI_TM_TRANS);
	GUI_SetFont(&GUI_Font20_1);
	
	//load mode
//	if(p_Mode_First->data.LOAD_DATA == MODE_1)
//	{
//		GUI_DispStringHCenterAt("MODE_0",LOAD_X,LOAD_Y);          //以当前坐标为中心显示字符串
//	}
//	else if(p_Mode_First->data.LOAD_DATA == MODE_2)
//	{
//		GUI_DispStringHCenterAt("MODE_1",LOAD_X,LOAD_Y);
//	}
//	
//	//save mode
//	if(p_Mode_First->data.SAVE_DATA == MODE_1)
//	{
//		GUI_DispStringHCenterAt("MODE_0",LOAD_X,LOAD_Y+45);
//	}
//	else if(p_Mode_First->data.SAVE_DATA == MODE_2)
//	{
//		GUI_DispStringHCenterAt("MODE_1",LOAD_X,LOAD_Y+45);
//	}
//	
//	//init mode
//	if(p_Mode_First->data.INIT_DATA == MODE_1)
//	{
//		GUI_DispStringHCenterAt("MODE_0",LOAD_X,LOAD_Y+90);
//	}
//	else if(p_Mode_First->data.INIT_DATA == MODE_2)
//	{
//		GUI_DispStringHCenterAt("MODE_1",LOAD_X,LOAD_Y+90);
//	}

	//LOAD MODE
	over = Max_Min(&Current_Data->data.LOAD_DATA,MODE_MAX,MODE_MIN);
	Current_Data->overflow |= (over<<First_Item);
	switch(Current_Data->data.LOAD_DATA)
	{
		case 0:
		case 1:
		case 2:
		case 3:
		case 4:
		case 5:
		case 6:
		case 7:
		case 8:
		case 9:
			strcpy(str,mode_string[Current_Data->data.LOAD_DATA]);
			break;
	}
	GUI_DispStringHCenterAt(str,300,LOAD_Y); 
	
	//SAVE MODE
	over = Max_Min(&Current_Data->data.SAVE_DATA,MODE_MAX,MODE_MIN);
	Current_Data->overflow |= (over<<Second_Item);
	switch(Current_Data->data.SAVE_DATA)
	{
		case 0:
		case 1:
		case 2:
		case 3:
		case 4:
		case 5:
		case 6:
		case 7:
		case 8:
		case 9:
			strcpy(str,mode_string[Current_Data->data.SAVE_DATA]);
			break;
	}
	GUI_DispStringHCenterAt(str,300,LOAD_Y+45);
	
	//INIT MODE
	over = Max_Min(&Current_Data->data.INIT_DATA,MODE_MAX,MODE_MIN);
	Current_Data->overflow |= (over<<Third_Item);
	switch(Current_Data->data.INIT_DATA)
	{
		case 0:
		case 1:
		case 2:
		case 3:
		case 4:
		case 5:
		case 6:
		case 7:
		case 8:
		case 9:
			strcpy(str,mode_string[Current_Data->data.INIT_DATA]);
			break;
	}
	GUI_DispStringHCenterAt(str,300,LOAD_Y+90);
	
}
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	int     NCode;
	int     Id;
	// USER START (Optionally insert additional variables)
	// USER END

	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetText(hItem, "LOAD MODE");
		BUTTON_SetFont(hItem, GUI_FONT_20B_1);
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetText(hItem, "SAVE MODE");
		BUTTON_SetFont(hItem, GUI_FONT_20B_1);
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		BUTTON_SetText(hItem, "INIT MODE");
		BUTTON_SetFont(hItem, GUI_FONT_20B_1);
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		BUTTON_SetText(hItem, "LOAD");
		BUTTON_SetFont(hItem, GUI_FONT_20B_1);
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		BUTTON_SetText(hItem, "SAVE");
		BUTTON_SetFont(hItem, GUI_FONT_20B_1);
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		BUTTON_SetText(hItem, "ESC");
		BUTTON_SetFont(hItem, GUI_FONT_20B_1);
		

		//TEXT设置
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem, "MODE PAGE 1/1");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		//INPUT_EQ
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem, "DEVICE  MODE  SETTINGS");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		/*增减按钮*/
		//left
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		//right
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点
		break;
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
			
		//点击主标题  退出
		case ID_TEXT_0:
			switch(NCode)
			{
				case WM_NOTIFICATION_RELEASED:
						GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
						hWin_now = CreateMainface();  //页面
						break;
			}
			break;
				
		case ID_BUTTON_0: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_SetFocus(WM_GetDialogItem(pMsg->hWin, Id)); //改变聚焦
				Current_Data->Item = First_Item;
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_1: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_SetFocus(WM_GetDialogItem(pMsg->hWin, Id)); //改变聚焦
				Current_Data->Item = Second_Item;
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_2: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_SetFocus(WM_GetDialogItem(pMsg->hWin, Id)); //改变聚焦
				Current_Data->Item = Third_Item;
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_3: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_SetFocus(WM_GetDialogItem(pMsg->hWin, Id)); //改变聚焦
				Current_Data->Item = Four_Item;
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_4: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_SetFocus(WM_GetDialogItem(pMsg->hWin, Id)); //改变聚焦
				Current_Data->Item = Five_Item;
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_5: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_SetFocus(WM_GetDialogItem(pMsg->hWin, Id)); //改变聚焦
				Current_Data->Item = Six_Item;
				break;
			case WM_NOTIFICATION_RELEASED:
				GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
				hWin_now = CreateMainface();  //显示主页面
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
			// USER START (Optionally insert additional code for further Ids)
			// USER END
		
		//增减按钮
		//left
		case ID_BUTTON_6:
			switch(NCode)
			{
				//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						Current_Data->change_item = First_Item;  //子选项改变
						Time_add_dec(&Current_Data->data.LOAD_DATA,&Rect[First_Item],&Current_Data->hItime,First_Time_left,pMsg);
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Time_end(&Current_Data->Time_count,Current_Data->hItime);
					break; 
			}
			break;
		
		case ID_BUTTON_7:
			switch(NCode)
			{
				//已点击按钮
				case WM_NOTIFICATION_CLICKED:
					Current_Data->change_item = Second_Item;  //子选项改变
					Time_add_dec(&Current_Data->data.SAVE_DATA,&Rect[Second_Item],&Current_Data->hItime,Second_Time_left,pMsg);
				
					break;
				
				//已释放按钮
				case WM_NOTIFICATION_RELEASED:
					Time_end(&Current_Data->Time_count,Current_Data->hItime);
				break;
			}
			break;
		
		case ID_BUTTON_8:
			switch(NCode)
			{
				//已点击按钮
				case WM_NOTIFICATION_CLICKED:
					Current_Data->change_item = Third_Item;  //子选项改变
					Time_add_dec(&Current_Data->data.INIT_DATA,&Rect[Third_Item],&Current_Data->hItime,Third_Time_left,pMsg);
				
					break;
				
				//已释放按钮
				case WM_NOTIFICATION_RELEASED:
					Time_end(&Current_Data->Time_count,Current_Data->hItime);
				break;
			}
			break;
			
		//right
		case ID_BUTTON_9:
			switch(NCode)
			{
				//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						Current_Data->change_item = First_Item;  //子选项改变
						Time_add_dec(&Current_Data->data.LOAD_DATA,&Rect[First_Item],&Current_Data->hItime,First_Time_right,pMsg);
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Time_end(&Current_Data->Time_count,Current_Data->hItime);
					break; 
			}
			break;
		
		case ID_BUTTON_10:
			switch(NCode)
			{
				//已点击按钮
				case WM_NOTIFICATION_CLICKED:
					Current_Data->change_item = Second_Item;  //子选项改变
					Time_add_dec(&Current_Data->data.SAVE_DATA,&Rect[Second_Item],&Current_Data->hItime,Second_Time_right,pMsg);
				
					break;
				
				//已释放按钮
				case WM_NOTIFICATION_RELEASED:
					Time_end(&Current_Data->Time_count,Current_Data->hItime);
				break;
			}
			break;
		
		case ID_BUTTON_11:
			switch(NCode)
			{
				//已点击按钮
				case WM_NOTIFICATION_CLICKED:
					Current_Data->change_item = Third_Item;  //子选项改变
					Time_add_dec(&Current_Data->data.INIT_DATA,&Rect[Third_Item],&Current_Data->hItime,Third_Time_right,pMsg);
				
					break;
				
				//已释放按钮
				case WM_NOTIFICATION_RELEASED:
					Time_end(&Current_Data->Time_count,Current_Data->hItime);
				break;
			}
			break;
		
		}
		break;
		// USER START (Optionally insert additional message handling)
		// USER END

	case WM_PAINT:
		GUI_SetBkColor(GUI_BLACK);
		GUI_Clear();

		//标题项
		GUI_SetColor(GUI_RED);
		GUI_FillRoundedRect(0, 0, 400, 30, 4);

		/*DEVICE项*/
		GUI_SetColor(GUI_BLUE);
		GUI_FillRoundedRect(0, 34, 400, 64, 4);

		GUI_SetColor(GUI_WHITE);
		GUI_FillRoundedRect(202, 68, 396, 68 + 38, 4);
		GUI_FillRoundedRect(202, 112, 396, 112 + 38, 4);
		GUI_FillRoundedRect(202, 155, 396, 155 + 38, 4);
		
		//显示各个子选项
		Show_Value();
		break;
	/*********************************************自定义信息处理**************************************************/
	//旋钮左转
	case MSG_KNOB_CONTROL_LEFT:
		Item_change(&(Current_Data->Item),First_Item,Six_Item,Next_dir);
		GUI_SendKeyMsg(GUI_KEY_TAB, 1);     //下一个聚焦点
		break;
	
	//旋钮右转
	case MSG_KNOB_CONTROL_RIGHT:
		Item_change(&(Current_Data->Item),First_Item,Six_Item,Last_dir);
		GUI_SendKeyMsg(GUI_KEY_BACKTAB, 1); //上一个聚焦
		break;
	
	//ESC
	case MSG_KEY_ESC:
		GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
        hWin_now = CreateMainface();  //显示Input_First页面
		break;
	
	//没有旋钮动作
	case MSG_KNOB_NULL:
		Current_Data->Key_count = 0;
		Current_Data->dir		 = 0;
		break;
	
	//INPUT右转
	case MSG_KNOB_INPUT_RIGHT:
		if(Out_Second[OUTPUT_CHANNEL]->dir	== 1)
		{
			Out_Second[OUTPUT_CHANNEL]->Key_count = 0;
		}
		Out_Second[OUTPUT_CHANNEL]->dir = 2;
		Current_Data->Key_count = 0;
		switch(Current_Data->Item)
		{
			//LOAD MODE
			case First_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_dec(&Current_Data->data.LOAD_DATA,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				break;
			
			//SAVE MODE
			case Second_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_dec(&Current_Data->data.SAVE_DATA,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				break;
			
			//INIT MODE
			case Third_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_dec(&Current_Data->data.INIT_DATA,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				break;
		}
		break;
	
	//INPUT左转
	case MSG_KNOB_INPUT_LEFT:
		if(Out_Second[OUTPUT_CHANNEL]->dir	== 2)
		{
			Out_Second[OUTPUT_CHANNEL]->Key_count = 0;
		}
		Out_Second[OUTPUT_CHANNEL]->dir = 1;
		Current_Data->Key_count = 0; //没有快速转
		switch(Current_Data->Item)
		{
			//LOAD MODE
			case First_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_add(&Current_Data->data.LOAD_DATA,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				break;
			
			//SAVE MODE
			case Second_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_add(&Current_Data->data.SAVE_DATA,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				break;
			
			//INIT MODE
			case Third_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_add(&Current_Data->data.INIT_DATA,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				break;
		}
		break;
	
	case WM_DELETE:
//		myfree(0,p_Mode_First);
		break;
	
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
//初始化数据
static void Init_data(Mode_First_Data *L)
{
	L->Item				=	First_Item;
	L->change_item		=	-1;
	L->Key_count		=	0;
	L->Time_count		=	0;
	

}


WM_HWIN Mode_First(void) {
	WM_HWIN hWin;
	
	//申请动态内存

	Init_data(Mode_first);
	
	Current_Data = Mode_first;
	
	Button_flex_2();
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
