#ifndef __ALGORITHM_H__
#define __ALGORITHM_H__
#include "math.h"
#include "sigmastudiofw.h"
#include "adau1452_drive_ic_1_param.h"

#define PI 3.1415926535897932384626433832795
#define DEVICE_ADDR_IC_1                          0x0

#define SAMPLE_RATE 48000

//void mute_control(unsigned int module_addr,unsigned char data );
#define MUTE 0
#define UMUTE 1
#define IN1_MUTE_ADDR                 MOD_IN1_MUTE_ALG0_MUTE_ADDR
#define IN2_MUTE_ADDR                 MOD_IN2_MUTE_ALG0_MUTE_ADDR
#define IN3_MUTE_ADDR                 MOD_IN3_MUTE_ALG0_MUTE_ADDR
#define IN4_MUTE_ADDR                 MOD_IN4_MUTE_ALG0_MUTE_ADDR
#define IN5_MUTE_ADDR                 MOD_IN5_MUTE_ALG0_MUTE_ADDR
#define IN6_MUTE_ADDR                 MOD_IN6_MUTE_ALG0_MUTE_ADDR
#define COAX_MUTE_ADDR                MOD_COAX_MUTE_ALG0_MUTE_ADDR
                                      

#define OUT1_MUTE_ADDR                MOD_OUT1_MUTE_ALG0_MUTE_ADDR
#define OUT2_MUTE_ADDR                MOD_OUT2_MUTE_ALG0_MUTE_ADDR
#define OUT3_MUTE_ADDR                MOD_OUT3_MUTE_ALG0_MUTE_ADDR
#define OUT4_MUTE_ADDR                MOD_OUT4_MUTE_ALG0_MUTE_ADDR
#define OUT5_MUTE_ADDR                MOD_OUT5_MUTE_ALG0_MUTE_ADDR
#define OUT6_MUTE_ADDR                MOD_OUT6_MUTE_ALG0_MUTE_ADDR
#define OUT7_MUTE_ADDR                MOD_OUT7_MUTE_ALG0_MUTE_ADDR
#define OUT8_MUTE_ADDR                MOD_OUT8_MUTE_ALG0_MUTE_ADDR

//void gain_control(unsigned int module_addr,double data);

#define IN1_GAIN_ADDR                 MOD_IN1_GAIN_ALG0_SWGAINOPTADAU145XALG1TARGET_ADDR
#define IN2_GAIN_ADDR                 MOD_IN2_GAIN_ALG0_SWGAINOPTADAU145XALG45TARGET_ADDR
#define IN3_GAIN_ADDR                 MOD_IN3_GAIN_ALG0_SWGAINOPTADAU145XALG2TARGET_ADDR
#define IN4_GAIN_ADDR                 MOD_IN4_GAIN_ALG0_SWGAINOPTADAU145XALG27TARGET_ADDR
#define IN5_GAIN_ADDR                 MOD_IN5_GAIN_ALG0_SWGAINOPTADAU145XALG27TARGET_ADDR
#define IN6_GAIN_ADDR                 MOD_IN6_GAIN_ALG0_SWGAINOPTADAU145XALG27TARGET_ADDR
#define COAX_L_GAIN_ADDR              MOD_COAX_L_GAIN_ALG0_SWGAINOPTADAU145XALG85TARGET_ADDR
#define COAX_R_GAIN_ADDR              MOD_COAX_R_GAIN_ALG0_SWGAINOPTADAU145XALG85TARGET_ADDR
                                      
#define OUT1_GAIN_ADDR                MOD_OUT1_GAIN_ALG0_SWGAINOPTADAU145XALG3TARGET_ADDR
#define OUT2_GAIN_ADDR                MOD_OUT2_GAIN_ALG0_SWGAINOPTADAU145XALG3TARGET_ADDR
#define OUT3_GAIN_ADDR                MOD_OUT3_GAIN_ALG0_SWGAINOPTADAU145XALG3TARGET_ADDR
#define OUT4_GAIN_ADDR                MOD_OUT4_GAIN_ALG0_SWGAINOPTADAU145XALG3TARGET_ADDR
#define OUT5_GAIN_ADDR                MOD_OUT5_GAIN_ALG0_SWGAINOPTADAU145XALG3TARGET_ADDR
#define OUT6_GAIN_ADDR                MOD_OUT6_GAIN_ALG0_SWGAINOPTADAU145XALG3TARGET_ADDR
#define OUT7_GAIN_ADDR                MOD_OUT7_GAIN_ALG0_SWGAINOPTADAU145XALG3TARGET_ADDR
#define OUT8_GAIN_ADDR                MOD_OUT8_GAIN_ALG0_SWGAINOPTADAU145XALG3TARGET_ADDR








//void invert_control(unsigned int  safeload_parameter_addr,unsigned int  safeload_parameter)
#define INVERT 0
#define UINVERT 1

#define IN1_INVERT_ADDR    MOD_IN1_INVERT_EQS300INVERT1INVERT_ADDR
#define IN2_INVERT_ADDR    MOD_IN2_INVERT_EQS300INVERT1INVERT_ADDR
#define IN3_INVERT_ADDR    MOD_IN3_INVERT_EQS300INVERT1INVERT_ADDR
#define IN4_INVERT_ADDR    MOD_IN4_INVERT_EQS300INVERT1INVERT_ADDR
#define IN5_INVERT_ADDR    MOD_IN5_INVERT_EQS300INVERT1INVERT_ADDR
#define IN6_INVERT_ADDR    MOD_IN6_INVERT_EQS300INVERT1INVERT_ADDR
#define COAX_INVERT_ADDR   MOD_COAX_INVERT_EQS300INVERT1INVERT_ADDR


#define OUT1_INVERT_ADDR        MOD_OUT1_INVERT_EQS300INVERT3INVERT_ADDR
#define OUT2_INVERT_ADDR        MOD_OUT2_INVERT_EQS300INVERT3INVERT_ADDR
#define OUT3_INVERT_ADDR        MOD_OUT3_INVERT_EQS300INVERT3INVERT_ADDR
#define OUT4_INVERT_ADDR        MOD_OUT4_INVERT_EQS300INVERT3INVERT_ADDR
#define OUT5_INVERT_ADDR        MOD_OUT5_INVERT_EQS300INVERT3INVERT_ADDR
#define OUT6_INVERT_ADDR        MOD_OUT6_INVERT_EQS300INVERT3INVERT_ADDR
#define OUT7_INVERT_ADDR        MOD_OUT7_INVERT_EQS300INVERT3INVERT_ADDR
#define OUT8_INVERT_ADDR        MOD_OUT8_INVERT_EQS300INVERT3INVERT_ADDR
                                

//void parametric_EQ_calculation(unsigned int safeload_parameter_addr,double boost,unsigned int frequency, unsigned int Fs,double gainlinear,double Q)
#define IN1_PEQ_POINT0_ADDR            MOD_IN1_PEQ_ALG0_STAGE0_B2_ADDR
#define IN1_PEQ_POINT1_ADDR            MOD_IN1_PEQ_ALG0_STAGE1_B2_ADDR
#define IN1_PEQ_POINT2_ADDR            MOD_IN1_PEQ_ALG0_STAGE2_B2_ADDR
#define IN1_PEQ_POINT3_ADDR            MOD_IN1_PEQ_ALG0_STAGE3_B2_ADDR
#define IN1_PEQ_POINT4_ADDR            MOD_IN1_PEQ_ALG0_STAGE4_B2_ADDR
#define IN1_PEQ_POINT5_ADDR            MOD_IN1_PEQ_ALG0_STAGE5_B2_ADDR
#define IN1_PEQ_POINT6_ADDR            MOD_IN1_PEQ_ALG0_STAGE6_B2_ADDR

#define IN2_PEQ_POINT0_ADDR            MOD_IN2_PEQ_ALG0_STAGE0_B2_ADDR
#define IN2_PEQ_POINT1_ADDR            MOD_IN2_PEQ_ALG0_STAGE1_B2_ADDR
#define IN2_PEQ_POINT2_ADDR            MOD_IN2_PEQ_ALG0_STAGE2_B2_ADDR
#define IN2_PEQ_POINT3_ADDR            MOD_IN2_PEQ_ALG0_STAGE3_B2_ADDR
#define IN2_PEQ_POINT4_ADDR            MOD_IN2_PEQ_ALG0_STAGE4_B2_ADDR
#define IN2_PEQ_POINT5_ADDR            MOD_IN2_PEQ_ALG0_STAGE5_B2_ADDR
#define IN2_PEQ_POINT6_ADDR            MOD_IN2_PEQ_ALG0_STAGE6_B2_ADDR

#define IN3_PEQ_POINT0_ADDR            MOD_IN3_PEQ_ALG0_STAGE0_B2_ADDR
#define IN3_PEQ_POINT1_ADDR            MOD_IN3_PEQ_ALG0_STAGE1_B2_ADDR
#define IN3_PEQ_POINT2_ADDR            MOD_IN3_PEQ_ALG0_STAGE2_B2_ADDR
#define IN3_PEQ_POINT3_ADDR            MOD_IN3_PEQ_ALG0_STAGE3_B2_ADDR
#define IN3_PEQ_POINT4_ADDR            MOD_IN3_PEQ_ALG0_STAGE4_B2_ADDR
#define IN3_PEQ_POINT5_ADDR            MOD_IN3_PEQ_ALG0_STAGE5_B2_ADDR
#define IN3_PEQ_POINT6_ADDR            MOD_IN3_PEQ_ALG0_STAGE6_B2_ADDR

#define IN4_PEQ_POINT0_ADDR            MOD_IN4_PEQ_ALG0_STAGE0_B2_ADDR
#define IN4_PEQ_POINT1_ADDR            MOD_IN4_PEQ_ALG0_STAGE1_B2_ADDR
#define IN4_PEQ_POINT2_ADDR            MOD_IN4_PEQ_ALG0_STAGE2_B2_ADDR
#define IN4_PEQ_POINT3_ADDR            MOD_IN4_PEQ_ALG0_STAGE3_B2_ADDR
#define IN4_PEQ_POINT4_ADDR            MOD_IN4_PEQ_ALG0_STAGE4_B2_ADDR
#define IN4_PEQ_POINT5_ADDR            MOD_IN4_PEQ_ALG0_STAGE5_B2_ADDR
#define IN4_PEQ_POINT6_ADDR            MOD_IN4_PEQ_ALG0_STAGE6_B2_ADDR

#define IN5_PEQ_POINT0_ADDR            MOD_IN5_PEQ_ALG0_STAGE0_B2_ADDR
#define IN5_PEQ_POINT1_ADDR            MOD_IN5_PEQ_ALG0_STAGE1_B2_ADDR
#define IN5_PEQ_POINT2_ADDR            MOD_IN5_PEQ_ALG0_STAGE2_B2_ADDR
#define IN5_PEQ_POINT3_ADDR            MOD_IN5_PEQ_ALG0_STAGE3_B2_ADDR
#define IN5_PEQ_POINT4_ADDR            MOD_IN5_PEQ_ALG0_STAGE4_B2_ADDR
#define IN5_PEQ_POINT5_ADDR            MOD_IN5_PEQ_ALG0_STAGE5_B2_ADDR
#define IN5_PEQ_POINT6_ADDR            MOD_IN5_PEQ_ALG0_STAGE6_B2_ADDR

#define IN6_PEQ_POINT0_ADDR            MOD_IN6_PEQ_ALG0_STAGE0_B2_ADDR
#define IN6_PEQ_POINT1_ADDR            MOD_IN6_PEQ_ALG0_STAGE1_B2_ADDR
#define IN6_PEQ_POINT2_ADDR            MOD_IN6_PEQ_ALG0_STAGE2_B2_ADDR
#define IN6_PEQ_POINT3_ADDR            MOD_IN6_PEQ_ALG0_STAGE3_B2_ADDR
#define IN6_PEQ_POINT4_ADDR            MOD_IN6_PEQ_ALG0_STAGE4_B2_ADDR
#define IN6_PEQ_POINT5_ADDR            MOD_IN6_PEQ_ALG0_STAGE5_B2_ADDR
#define IN6_PEQ_POINT6_ADDR            MOD_IN6_PEQ_ALG0_STAGE6_B2_ADDR

#define COAX_PEQ_POINT0_ADDR            MOD_COAX_PEQ_ALG0_STAGE0_B2_ADDR
#define COAX_PEQ_POINT1_ADDR            MOD_COAX_PEQ_ALG0_STAGE1_B2_ADDR
#define COAX_PEQ_POINT2_ADDR            MOD_COAX_PEQ_ALG0_STAGE2_B2_ADDR
#define COAX_PEQ_POINT3_ADDR            MOD_COAX_PEQ_ALG0_STAGE3_B2_ADDR
#define COAX_PEQ_POINT4_ADDR            MOD_COAX_PEQ_ALG0_STAGE4_B2_ADDR
#define COAX_PEQ_POINT5_ADDR            MOD_COAX_PEQ_ALG0_STAGE5_B2_ADDR
#define COAX_PEQ_POINT6_ADDR            MOD_COAX_PEQ_ALG0_STAGE6_B2_ADDR







#define OUT1_PEQ_POINT0_ADDR            MOD_OUT1_PEQ_ALG0_STAGE0_B2_ADDR
#define OUT1_PEQ_POINT1_ADDR            MOD_OUT1_PEQ_ALG0_STAGE1_B2_ADDR
#define OUT1_PEQ_POINT2_ADDR            MOD_OUT1_PEQ_ALG0_STAGE2_B2_ADDR
#define OUT1_PEQ_POINT3_ADDR            MOD_OUT1_PEQ_ALG0_STAGE3_B2_ADDR
#define OUT1_PEQ_POINT4_ADDR            MOD_OUT1_PEQ_ALG0_STAGE4_B2_ADDR
#define OUT1_PEQ_POINT5_ADDR            MOD_OUT1_PEQ_ALG0_STAGE5_B2_ADDR
#define OUT1_PEQ_POINT6_ADDR            MOD_OUT1_PEQ_ALG0_STAGE6_B2_ADDR

#define OUT2_PEQ_POINT0_ADDR            MOD_OUT2_PEQ_ALG0_STAGE0_B2_ADDR
#define OUT2_PEQ_POINT1_ADDR            MOD_OUT2_PEQ_ALG0_STAGE1_B2_ADDR
#define OUT2_PEQ_POINT2_ADDR            MOD_OUT2_PEQ_ALG0_STAGE2_B2_ADDR
#define OUT2_PEQ_POINT3_ADDR            MOD_OUT2_PEQ_ALG0_STAGE3_B2_ADDR
#define OUT2_PEQ_POINT4_ADDR            MOD_OUT2_PEQ_ALG0_STAGE4_B2_ADDR
#define OUT2_PEQ_POINT5_ADDR            MOD_OUT2_PEQ_ALG0_STAGE5_B2_ADDR
#define OUT2_PEQ_POINT6_ADDR            MOD_OUT2_PEQ_ALG0_STAGE6_B2_ADDR

#define OUT3_PEQ_POINT0_ADDR            MOD_OUT3_PEQ_ALG0_STAGE0_B2_ADDR
#define OUT3_PEQ_POINT1_ADDR            MOD_OUT3_PEQ_ALG0_STAGE1_B2_ADDR
#define OUT3_PEQ_POINT2_ADDR            MOD_OUT3_PEQ_ALG0_STAGE2_B2_ADDR
#define OUT3_PEQ_POINT3_ADDR            MOD_OUT3_PEQ_ALG0_STAGE3_B2_ADDR
#define OUT3_PEQ_POINT4_ADDR            MOD_OUT3_PEQ_ALG0_STAGE4_B2_ADDR
#define OUT3_PEQ_POINT5_ADDR            MOD_OUT3_PEQ_ALG0_STAGE5_B2_ADDR
#define OUT3_PEQ_POINT6_ADDR            MOD_OUT3_PEQ_ALG0_STAGE6_B2_ADDR

#define OUT4_PEQ_POINT0_ADDR            MOD_OUT4_PEQ_ALG0_STAGE0_B2_ADDR
#define OUT4_PEQ_POINT1_ADDR            MOD_OUT4_PEQ_ALG0_STAGE1_B2_ADDR
#define OUT4_PEQ_POINT2_ADDR            MOD_OUT4_PEQ_ALG0_STAGE2_B2_ADDR
#define OUT4_PEQ_POINT3_ADDR            MOD_OUT4_PEQ_ALG0_STAGE3_B2_ADDR
#define OUT4_PEQ_POINT4_ADDR            MOD_OUT4_PEQ_ALG0_STAGE4_B2_ADDR
#define OUT4_PEQ_POINT5_ADDR            MOD_OUT4_PEQ_ALG0_STAGE5_B2_ADDR
#define OUT4_PEQ_POINT6_ADDR            MOD_OUT4_PEQ_ALG0_STAGE6_B2_ADDR

#define OUT5_PEQ_POINT0_ADDR            MOD_OUT5_PEQ_ALG0_STAGE0_B2_ADDR
#define OUT5_PEQ_POINT1_ADDR            MOD_OUT5_PEQ_ALG0_STAGE1_B2_ADDR
#define OUT5_PEQ_POINT2_ADDR            MOD_OUT5_PEQ_ALG0_STAGE2_B2_ADDR
#define OUT5_PEQ_POINT3_ADDR            MOD_OUT5_PEQ_ALG0_STAGE3_B2_ADDR
#define OUT5_PEQ_POINT4_ADDR            MOD_OUT5_PEQ_ALG0_STAGE4_B2_ADDR
#define OUT5_PEQ_POINT5_ADDR            MOD_OUT5_PEQ_ALG0_STAGE5_B2_ADDR
#define OUT5_PEQ_POINT6_ADDR            MOD_OUT5_PEQ_ALG0_STAGE6_B2_ADDR

#define OUT6_PEQ_POINT0_ADDR            MOD_OUT6_PEQ_ALG0_STAGE0_B2_ADDR
#define OUT6_PEQ_POINT1_ADDR            MOD_OUT6_PEQ_ALG0_STAGE1_B2_ADDR
#define OUT6_PEQ_POINT2_ADDR            MOD_OUT6_PEQ_ALG0_STAGE2_B2_ADDR
#define OUT6_PEQ_POINT3_ADDR            MOD_OUT6_PEQ_ALG0_STAGE3_B2_ADDR
#define OUT6_PEQ_POINT4_ADDR            MOD_OUT6_PEQ_ALG0_STAGE4_B2_ADDR
#define OUT6_PEQ_POINT5_ADDR            MOD_OUT6_PEQ_ALG0_STAGE5_B2_ADDR
#define OUT6_PEQ_POINT6_ADDR            MOD_OUT6_PEQ_ALG0_STAGE6_B2_ADDR

#define OUT7_PEQ_POINT0_ADDR            MOD_OUT7_PEQ_ALG0_STAGE0_B2_ADDR
#define OUT7_PEQ_POINT1_ADDR            MOD_OUT7_PEQ_ALG0_STAGE1_B2_ADDR
#define OUT7_PEQ_POINT2_ADDR            MOD_OUT7_PEQ_ALG0_STAGE2_B2_ADDR
#define OUT7_PEQ_POINT3_ADDR            MOD_OUT7_PEQ_ALG0_STAGE3_B2_ADDR
#define OUT7_PEQ_POINT4_ADDR            MOD_OUT7_PEQ_ALG0_STAGE4_B2_ADDR
#define OUT7_PEQ_POINT5_ADDR            MOD_OUT7_PEQ_ALG0_STAGE5_B2_ADDR
#define OUT7_PEQ_POINT6_ADDR            MOD_OUT7_PEQ_ALG0_STAGE6_B2_ADDR


                                



#define OFF 0
#define ON 1
#define IN1_Aux1MixerGainSw_ADDR        MOD_IN1_AUX1MIXERGAINSW_ALG0_MUTE_ADDR
#define IN1_Aux2MixerGainSw_ADDR        MOD_IN1_AUX2MIXERGAINSW_ALG0_MUTE_ADDR
#define IN1_Aux3MixerGainSw_ADDR        MOD_IN1_AUX3MIXERGAINSW_ALG0_MUTE_ADDR
#define IN1_Aux4MixerGainSw_ADDR        MOD_IN1_AUX4MIXERGAINSW_ALG0_MUTE_ADDR
#define IN1_Aux5MixerGainSw_ADDR        MOD_IN1_AUX5MIXERGAINSW_ALG0_MUTE_ADDR
#define IN1_Aux6MixerGainSw_ADDR        MOD_IN1_AUX6MIXERGAINSW_ALG0_MUTE_ADDR
#define IN1_Aux7MixerGainSw_ADDR        MOD_IN1_AUX7MIXERGAINSW_ALG0_MUTE_ADDR
#define IN1_Aux8MixerGainSw_ADDR        MOD_IN1_AUX8MIXERGAINSW_ALG0_MUTE_ADDR
                           
                           
#define IN2_Aux1MixerGainSw_ADDR        MOD_IN2_AUX1MIXERGAINSW_ALG0_MUTE_ADDR
#define IN2_Aux2MixerGainSw_ADDR        MOD_IN2_AUX2MIXERGAINSW_ALG0_MUTE_ADDR
#define IN2_Aux3MixerGainSw_ADDR        MOD_IN2_AUX3MIXERGAINSW_ALG0_MUTE_ADDR
#define IN2_Aux4MixerGainSw_ADDR        MOD_IN2_AUX4MIXERGAINSW_ALG0_MUTE_ADDR
#define IN2_Aux5MixerGainSw_ADDR        MOD_IN2_AUX5MIXERGAINSW_ALG0_MUTE_ADDR
#define IN2_Aux6MixerGainSw_ADDR        MOD_IN2_AUX6MIXERGAINSW_ALG0_MUTE_ADDR
#define IN2_Aux7MixerGainSw_ADDR        MOD_IN2_AUX7MIXERGAINSW_ALG0_MUTE_ADDR
#define IN2_Aux8MixerGainSw_ADDR        MOD_IN2_AUX8MIXERGAINSW_ALG0_MUTE_ADDR
                           
                           
#define IN3_Aux1MixerGainSw_ADDR        MOD_IN3_AUX1MIXERGAINSW_ALG0_MUTE_ADDR
#define IN3_Aux2MixerGainSw_ADDR        MOD_IN3_AUX2MIXERGAINSW_ALG0_MUTE_ADDR
#define IN3_Aux3MixerGainSw_ADDR        MOD_IN3_AUX3MIXERGAINSW_ALG0_MUTE_ADDR
#define IN3_Aux4MixerGainSw_ADDR        MOD_IN3_AUX4MIXERGAINSW_ALG0_MUTE_ADDR
#define IN3_Aux5MixerGainSw_ADDR        MOD_IN3_AUX5MIXERGAINSW_ALG0_MUTE_ADDR
#define IN3_Aux6MixerGainSw_ADDR        MOD_IN3_AUX6MIXERGAINSW_ALG0_MUTE_ADDR
#define IN3_Aux7MixerGainSw_ADDR        MOD_IN3_AUX7MIXERGAINSW_ALG0_MUTE_ADDR
#define IN3_Aux8MixerGainSw_ADDR        MOD_IN3_AUX8MIXERGAINSW_ALG0_MUTE_ADDR

#define IN4_Aux1MixerGainSw_ADDR        MOD_IN4_AUX1MIXERGAINSW_ALG0_MUTE_ADDR
#define IN4_Aux2MixerGainSw_ADDR        MOD_IN4_AUX2MIXERGAINSW_ALG0_MUTE_ADDR
#define IN4_Aux3MixerGainSw_ADDR        MOD_IN4_AUX3MIXERGAINSW_ALG0_MUTE_ADDR
#define IN4_Aux4MixerGainSw_ADDR        MOD_IN4_AUX4MIXERGAINSW_ALG0_MUTE_ADDR
#define IN4_Aux5MixerGainSw_ADDR        MOD_IN4_AUX5MIXERGAINSW_ALG0_MUTE_ADDR
#define IN4_Aux6MixerGainSw_ADDR        MOD_IN4_AUX6MIXERGAINSW_ALG0_MUTE_ADDR
#define IN4_Aux7MixerGainSw_ADDR        MOD_IN4_AUX7MIXERGAINSW_ALG0_MUTE_ADDR
#define IN4_Aux8MixerGainSw_ADDR        MOD_IN4_AUX8MIXERGAINSW_ALG0_MUTE_ADDR


#define IN5_Aux1MixerGainSw_ADDR        MOD_IN5_AUX1MIXERGAINSW_ALG0_MUTE_ADDR
#define IN5_Aux2MixerGainSw_ADDR        MOD_IN5_AUX2MIXERGAINSW_ALG0_MUTE_ADDR
#define IN5_Aux3MixerGainSw_ADDR        MOD_IN5_AUX3MIXERGAINSW_ALG0_MUTE_ADDR
#define IN5_Aux4MixerGainSw_ADDR        MOD_IN5_AUX4MIXERGAINSW_ALG0_MUTE_ADDR
#define IN5_Aux5MixerGainSw_ADDR        MOD_IN5_AUX5MIXERGAINSW_ALG0_MUTE_ADDR
#define IN5_Aux6MixerGainSw_ADDR        MOD_IN5_AUX6MIXERGAINSW_ALG0_MUTE_ADDR
#define IN5_Aux7MixerGainSw_ADDR        MOD_IN5_AUX7MIXERGAINSW_ALG0_MUTE_ADDR
#define IN5_Aux8MixerGainSw_ADDR        MOD_IN5_AUX8MIXERGAINSW_ALG0_MUTE_ADDR

#define IN6_Aux1MixerGainSw_ADDR        MOD_IN6_AUX1MIXERGAINSW_ALG0_MUTE_ADDR
#define IN6_Aux2MixerGainSw_ADDR        MOD_IN6_AUX2MIXERGAINSW_ALG0_MUTE_ADDR
#define IN6_Aux3MixerGainSw_ADDR        MOD_IN6_AUX3MIXERGAINSW_ALG0_MUTE_ADDR
#define IN6_Aux4MixerGainSw_ADDR        MOD_IN6_AUX4MIXERGAINSW_ALG0_MUTE_ADDR
#define IN6_Aux5MixerGainSw_ADDR        MOD_IN6_AUX5MIXERGAINSW_ALG0_MUTE_ADDR
#define IN6_Aux6MixerGainSw_ADDR        MOD_IN6_AUX6MIXERGAINSW_ALG0_MUTE_ADDR
#define IN6_Aux7MixerGainSw_ADDR        MOD_IN6_AUX7MIXERGAINSW_ALG0_MUTE_ADDR
#define IN6_Aux8MixerGainSw_ADDR        MOD_IN6_AUX8MIXERGAINSW_ALG0_MUTE_ADDR
          










#define COAX_L_Aux1MixerGainSw_ADDR        MOD_COAX_L_AUX1MIXERGAINSW_ALG0_MUTE_ADDR
#define COAX_L_Aux2MixerGainSw_ADDR        MOD_COAX_L_AUX2MIXERGAINSW_ALG0_MUTE_ADDR
#define COAX_L_Aux3MixerGainSw_ADDR        MOD_COAX_L_AUX3MIXERGAINSW_ALG0_MUTE_ADDR
#define COAX_L_Aux4MixerGainSw_ADDR        MOD_COAX_L_AUX4MIXERGAINSW_ALG0_MUTE_ADDR
#define COAX_L_Aux5MixerGainSw_ADDR        MOD_COAX_L_AUX5MIXERGAINSW_ALG0_MUTE_ADDR
#define COAX_L_Aux6MixerGainSw_ADDR        MOD_COAX_L_AUX6MIXERGAINSW_ALG0_MUTE_ADDR
#define COAX_L_Aux7MixerGainSw_ADDR        MOD_COAX_L_AUX7MIXERGAINSW_ALG0_MUTE_ADDR
#define COAX_L_Aux8MixerGainSw_ADDR        MOD_COAX_L_AUX8MIXERGAINSW_ALG0_MUTE_ADDR


#define COAX_R_Aux1MixerGainSw_ADDR        MOD_COAX_R_AUX1MIXERGAINSW_ALG0_MUTE_ADDR
#define COAX_R_Aux2MixerGainSw_ADDR        MOD_COAX_R_AUX2MIXERGAINSW_ALG0_MUTE_ADDR
#define COAX_R_Aux3MixerGainSw_ADDR        MOD_COAX_R_AUX3MIXERGAINSW_ALG0_MUTE_ADDR
#define COAX_R_Aux4MixerGainSw_ADDR        MOD_COAX_R_AUX4MIXERGAINSW_ALG0_MUTE_ADDR
#define COAX_R_Aux5MixerGainSw_ADDR        MOD_COAX_R_AUX5MIXERGAINSW_ALG0_MUTE_ADDR
#define COAX_R_Aux6MixerGainSw_ADDR        MOD_COAX_R_AUX6MIXERGAINSW_ALG0_MUTE_ADDR
#define COAX_R_Aux7MixerGainSw_ADDR        MOD_COAX_R_AUX7MIXERGAINSW_ALG0_MUTE_ADDR
#define COAX_R_Aux8MixerGainSw_ADDR        MOD_COAX_R_AUX8MIXERGAINSW_ALG0_MUTE_ADDR





#define IN1_Aux1MixerGain_ADDR            MOD_IN1_AUX1MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN1_Aux2MixerGain_ADDR            MOD_IN1_AUX2MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN1_Aux3MixerGain_ADDR            MOD_IN1_AUX3MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN1_Aux4MixerGain_ADDR            MOD_IN1_AUX4MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN1_Aux5MixerGain_ADDR            MOD_IN1_AUX5MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN1_Aux6MixerGain_ADDR            MOD_IN1_AUX6MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN1_Aux7MixerGain_ADDR            MOD_IN1_AUX7MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN1_Aux8MixerGain_ADDR            MOD_IN1_AUX8MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR

#define IN2_Aux1MixerGain_ADDR            MOD_IN2_AUX1MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN2_Aux2MixerGain_ADDR            MOD_IN2_AUX2MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN2_Aux3MixerGain_ADDR            MOD_IN2_AUX3MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN2_Aux4MixerGain_ADDR            MOD_IN2_AUX4MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN2_Aux5MixerGain_ADDR            MOD_IN2_AUX5MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN2_Aux6MixerGain_ADDR            MOD_IN2_AUX6MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN2_Aux7MixerGain_ADDR            MOD_IN2_AUX7MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN2_Aux8MixerGain_ADDR            MOD_IN2_AUX8MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR


#define IN3_Aux1MixerGain_ADDR            MOD_IN3_AUX1MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN3_Aux2MixerGain_ADDR            MOD_IN3_AUX2MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN3_Aux3MixerGain_ADDR            MOD_IN3_AUX3MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN3_Aux4MixerGain_ADDR            MOD_IN3_AUX4MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN3_Aux5MixerGain_ADDR            MOD_IN3_AUX5MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN3_Aux6MixerGain_ADDR            MOD_IN3_AUX6MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN3_Aux7MixerGain_ADDR            MOD_IN3_AUX7MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN3_Aux8MixerGain_ADDR            MOD_IN3_AUX8MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR


#define IN4_Aux1MixerGain_ADDR            MOD_IN4_AUX1MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN4_Aux2MixerGain_ADDR            MOD_IN4_AUX2MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN4_Aux3MixerGain_ADDR            MOD_IN4_AUX3MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN4_Aux4MixerGain_ADDR            MOD_IN4_AUX4MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN4_Aux5MixerGain_ADDR            MOD_IN4_AUX5MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN4_Aux6MixerGain_ADDR            MOD_IN4_AUX6MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN4_Aux7MixerGain_ADDR            MOD_IN4_AUX7MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN4_Aux8MixerGain_ADDR            MOD_IN4_AUX8MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR

#define IN5_Aux1MixerGain_ADDR            MOD_IN5_AUX1MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN5_Aux2MixerGain_ADDR            MOD_IN5_AUX2MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN5_Aux3MixerGain_ADDR            MOD_IN5_AUX3MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN5_Aux4MixerGain_ADDR            MOD_IN5_AUX4MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN5_Aux5MixerGain_ADDR            MOD_IN5_AUX5MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN5_Aux6MixerGain_ADDR            MOD_IN5_AUX6MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN5_Aux7MixerGain_ADDR            MOD_IN5_AUX7MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN5_Aux8MixerGain_ADDR            MOD_IN5_AUX8MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR


#define IN6_Aux1MixerGain_ADDR            MOD_IN6_AUX1MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN6_Aux2MixerGain_ADDR            MOD_IN6_AUX2MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN6_Aux3MixerGain_ADDR            MOD_IN6_AUX3MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN6_Aux4MixerGain_ADDR            MOD_IN6_AUX4MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN6_Aux5MixerGain_ADDR            MOD_IN6_AUX5MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN6_Aux6MixerGain_ADDR            MOD_IN6_AUX6MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN6_Aux7MixerGain_ADDR            MOD_IN6_AUX7MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define IN6_Aux8MixerGain_ADDR            MOD_IN6_AUX8MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR


#define COAX_L_Aux1MixerGain_ADDR            MOD_COAX_L_AUX1MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define COAX_L_Aux2MixerGain_ADDR            MOD_COAX_L_AUX2MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define COAX_L_Aux3MixerGain_ADDR            MOD_COAX_L_AUX3MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define COAX_L_Aux4MixerGain_ADDR            MOD_COAX_L_AUX4MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define COAX_L_Aux5MixerGain_ADDR            MOD_COAX_L_AUX5MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define COAX_L_Aux6MixerGain_ADDR            MOD_COAX_L_AUX6MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define COAX_L_Aux7MixerGain_ADDR            MOD_COAX_L_AUX7MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define COAX_L_Aux8MixerGain_ADDR            MOD_COAX_L_AUX8MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR



#define COAX_R_Aux1MixerGain_ADDR            MOD_COAX_R_AUX1MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define COAX_R_Aux2MixerGain_ADDR            MOD_COAX_R_AUX2MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define COAX_R_Aux3MixerGain_ADDR            MOD_COAX_R_AUX3MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define COAX_R_Aux4MixerGain_ADDR            MOD_COAX_R_AUX4MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define COAX_R_Aux5MixerGain_ADDR            MOD_COAX_R_AUX5MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define COAX_R_Aux6MixerGain_ADDR            MOD_COAX_R_AUX6MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define COAX_R_Aux7MixerGain_ADDR            MOD_COAX_R_AUX7MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR
#define COAX_R_Aux8MixerGain_ADDR            MOD_COAX_R_AUX8MIXERGAIN_ALG0_SWGAINOPTADAU145XALG20TARGET_ADDR












//void delay_control(unsigned int module_addr,unsigned int data)
#define OUT1_DELAY_ADDR      MOD_OUT1_DELAY_DELAYAMT_ADDR
#define OUT2_DELAY_ADDR      MOD_OUT2_DELAY_DELAYAMT_ADDR
#define OUT3_DELAY_ADDR      MOD_OUT3_DELAY_DELAYAMT_ADDR
#define OUT4_DELAY_ADDR      MOD_OUT4_DELAY_DELAYAMT_ADDR
#define OUT5_DELAY_ADDR      MOD_OUT5_DELAY_DELAYAMT_ADDR
#define OUT6_DELAY_ADDR      MOD_OUT6_DELAY_DELAYAMT_ADDR
#define OUT7_DELAY_ADDR      MOD_OUT7_DELAY_DELAYAMT_ADDR
#define OUT8_DELAY_ADDR      MOD_OUT8_DELAY_DELAYAMT_ADDR




#define LOWPASS  0
#define HIGHPASS 1


#define OUT1_LOWPASS_ADDR    MOD_OUT1_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR
#define OUT2_LOWPASS_ADDR    MOD_OUT2_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR
#define OUT3_LOWPASS_ADDR    MOD_OUT3_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR
#define OUT4_LOWPASS_ADDR    MOD_OUT4_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR
#define OUT5_LOWPASS_ADDR    MOD_OUT5_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR
#define OUT6_LOWPASS_ADDR    MOD_OUT6_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR
#define OUT7_LOWPASS_ADDR    MOD_OUT7_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR
#define OUT8_LOWPASS_ADDR    MOD_OUT8_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR




#define IN1_CMOPRESSOR_THRESHOLD_RATIO_ADDR   MOD_IN1_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE2POINTS0_ADDR
#define IN2_CMOPRESSOR_THRESHOLD_RATIO_ADDR   MOD_IN2_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE4POINTS0_ADDR
#define IN3_CMOPRESSOR_THRESHOLD_RATIO_ADDR   MOD_IN3_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE6POINTS0_ADDR
#define IN4_CMOPRESSOR_THRESHOLD_RATIO_ADDR   MOD_IN4_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE8POINTS0_ADDR
#define IN5_CMOPRESSOR_THRESHOLD_RATIO_ADDR   MOD_IN5_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE9POINTS0_ADDR
#define IN6_CMOPRESSOR_THRESHOLD_RATIO_ADDR   MOD_IN6_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE10POINTS0_ADDR
#define COAX_CMOPRESSOR_THRESHOLD_RATIO_ADDR   MOD_COAX_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE10POINTS0_ADDR

#define IN1_CMOPRESSOR_RMS_TC_ADDR      MOD_IN1_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE2TC_ADDR
#define IN2_CMOPRESSOR_RMS_TC_ADDR      MOD_IN2_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE4TC_ADDR
#define IN3_CMOPRESSOR_RMS_TC_ADDR      MOD_IN3_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE6TC_ADDR
#define IN4_CMOPRESSOR_RMS_TC_ADDR      MOD_IN4_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE8TC_ADDR
#define IN5_CMOPRESSOR_RMS_TC_ADDR      MOD_IN5_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE9TC_ADDR
#define IN6_CMOPRESSOR_RMS_TC_ADDR      MOD_IN6_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE10TC_ADDR
#define COAX_CMOPRESSOR_RMS_TC_ADDR     MOD_COAX_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE10TC_ADDR



#define IN1_CMOPRESSOR_DECAY_ADDR      MOD_IN1_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE2DECAY_ADDR
#define IN2_CMOPRESSOR_DECAY_ADDR      MOD_IN2_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE4DECAY_ADDR
#define IN3_CMOPRESSOR_DECAY_ADDR      MOD_IN3_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE6DECAY_ADDR
#define IN4_CMOPRESSOR_DECAY_ADDR      MOD_IN4_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE8DECAY_ADDR
#define IN5_CMOPRESSOR_DECAY_ADDR      MOD_IN5_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE9DECAY_ADDR
#define IN6_CMOPRESSOR_DECAY_ADDR      MOD_IN6_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE10DECAY_ADDR
#define COAX_CMOPRESSOR_DECAY_ADDR     MOD_COAX_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE10DECAY_ADDR


#define IN1_CMOPRESSOR_HOLD_ADDR       MOD_IN1_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE2HOLD_ADDR
#define IN2_CMOPRESSOR_HOLD_ADDR       MOD_IN2_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE4HOLD_ADDR
#define IN3_CMOPRESSOR_HOLD_ADDR       MOD_IN3_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE6HOLD_ADDR
#define IN4_CMOPRESSOR_HOLD_ADDR       MOD_IN4_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE8HOLD_ADDR
#define IN5_CMOPRESSOR_HOLD_ADDR       MOD_IN5_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE9HOLD_ADDR
#define IN6_CMOPRESSOR_HOLD_ADDR       MOD_IN6_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE10HOLD_ADDR
#define COAX_CMOPRESSOR_HOLD_ADDR      MOD_COAX_COMPRESSOR_ALG0_MONONOPOSTGAINS300FULLRANGE10HOLD_ADDR


#define IN1_NOISE_GATE_ADDR             MOD_IN1_NOISEGATE_ALG0_MONONOPOSTGAINS300FULLRANGE1POINTS0_ADDR
#define IN2_NOISE_GATE_ADDR             MOD_IN2_NOISEGATE_ALG0_MONONOPOSTGAINS300FULLRANGE1POINTS0_ADDR
#define IN3_NOISE_GATE_ADDR             MOD_IN3_NOISEGATE_ALG0_MONONOPOSTGAINS300FULLRANGE1POINTS0_ADDR
#define IN4_NOISE_GATE_ADDR             MOD_IN4_NOISEGATE_ALG0_MONONOPOSTGAINS300FULLRANGE1POINTS0_ADDR
#define IN5_NOISE_GATE_ADDR             MOD_IN5_NOISEGATE_ALG0_MONONOPOSTGAINS300FULLRANGE1POINTS0_ADDR
#define IN6_NOISE_GATE_ADDR             MOD_IN6_NOISEGATE_ALG0_MONONOPOSTGAINS300FULLRANGE1POINTS0_ADDR
#define COAX_NOISE_GATE_ADDR            MOD_COAX_NOISEGATE_ALG0_TWOCHANRMSNOPOSTGAINS300FULLRANGE1POINTS0_ADDR


#define IN1_NOISE_TC_ADDR      MOD_IN1_NOISE_ALG0_MONONOPOSTGAINS300FULLRANGE2TC_ADDR
#define IN2_NOISE_TC_ADDR      MOD_IN2_NOISE_ALG0_MONONOPOSTGAINS300FULLRANGE4TC_ADDR
#define IN3_NOISE_TC_ADDR      MOD_IN3_NOISE_ALG0_MONONOPOSTGAINS300FULLRANGE6TC_ADDR
#define IN4_NOISE_TC_ADDR      MOD_IN4_NOISE_ALG0_MONONOPOSTGAINS300FULLRANGE8TC_ADDR
#define IN5_NOISE_TC_ADDR      MOD_IN5_NOISE_ALG0_MONONOPOSTGAINS300FULLRANGE9TC_ADDR
#define IN6_NOISE_TC_ADDR      MOD_IN6_NOISE_ALG0_MONONOPOSTGAINS300FULLRANGE10TC_ADDR
#define COAX_NOISE_TC_ADDR     MOD_COAX_NOISE_TC_ADD_ALG0_MONONOPOSTGAINS300FULLRANGE11TC_ADDR



#define IN1_NOISE_DECAY_ADDR      MOD_IN1_NOISE_ALG0_MONONOPOSTGAINS300FULLRANGE2DECAY_ADDR
#define IN2_NOISE_DECAY_ADDR      MOD_IN2_NOISE_ALG0_MONONOPOSTGAINS300FULLRANGE4DECAY_ADDR
#define IN3_NOISE_DECAY_ADDR      MOD_IN3_NOISE_ALG0_MONONOPOSTGAINS300FULLRANGE6DECAY_ADDR
#define IN4_NOISE_DECAY_ADDR      MOD_IN4_NOISE_ALG0_MONONOPOSTGAINS300FULLRANGE8DECAY_ADDR
#define IN5_NOISE_DECAY_ADDR      MOD_IN5_NOISE_ALG0_MONONOPOSTGAINS300FULLRANGE9DECAY_ADDR
#define IN6_NOISE_DECAY_ADDR      MOD_IN6_NOISE_ALG0_MONONOPOSTGAINS300FULLRANGE10DECAY_ADDR
#define COAX_NOISE_DECAY_ADDR     MOD_ COAX_NOISE_ALG0_MONONOPOSTGAINS300FULLRANGE11DECAY_ADDR




#define OUT1_LIMIT_THRESHOLD_ADDR       MOD_OUT1_LIMITER_ALG0_THRESHOLD_ADDR
#define OUT2_LIMIT_THRESHOLD_ADDR       MOD_OUT2_LIMITER_ALG0_THRESHOLD_ADDR
#define OUT3_LIMIT_THRESHOLD_ADDR       MOD_OUT3_LIMITER_ALG0_THRESHOLD_ADDR
#define OUT4_LIMIT_THRESHOLD_ADDR       MOD_OUT4_LIMITER_ALG0_THRESHOLD_ADDR
#define OUT5_LIMIT_THRESHOLD_ADDR       MOD_OUT5_LIMITER_ALG0_THRESHOLD_ADDR
#define OUT6_LIMIT_THRESHOLD_ADDR       MOD_OUT6_LIMITER_ALG0_THRESHOLD_ADDR
#define OUT7_LIMIT_THRESHOLD_ADDR       MOD_OUT7_LIMITER_ALG0_THRESHOLD_ADDR
#define OUT8_LIMIT_THRESHOLD_ADDR       MOD_OUT8_LIMITER_ALG0_THRESHOLD_ADDR


#define OUT1_LIMIT_DECAY_ADDR           MOD_OUT1_LIMITER_ALG0_DECAY_ADDR
#define OUT2_LIMIT_DECAY_ADDR           MOD_OUT2_LIMITER_ALG0_DECAY_ADDR
#define OUT3_LIMIT_DECAY_ADDR           MOD_OUT3_LIMITER_ALG0_DECAY_ADDR
#define OUT4_LIMIT_DECAY_ADDR           MOD_OUT4_LIMITER_ALG0_DECAY_ADDR
#define OUT5_LIMIT_DECAY_ADDR           MOD_OUT5_LIMITER_ALG0_DECAY_ADDR
#define OUT6_LIMIT_DECAY_ADDR           MOD_OUT6_LIMITER_ALG0_DECAY_ADDR
#define OUT7_LIMIT_DECAY_ADDR           MOD_OUT7_LIMITER_ALG0_DECAY_ADDR
#define OUT8_LIMIT_DECAY_ADDR           MOD_OUT8_LIMITER_ALG0_DECAY_ADDR

                                        
#define OUT1_LIMIT_RMS_TC_ADDR          MOD_OUT1_LIMITER_ALG0_RMS_ADDR
#define OUT2_LIMIT_RMS_TC_ADDR          MOD_OUT2_LIMITER_ALG0_RMS_ADDR  
#define OUT3_LIMIT_RMS_TC_ADDR          MOD_OUT3_LIMITER_ALG0_RMS_ADDR
#define OUT4_LIMIT_RMS_TC_ADDR          MOD_OUT4_LIMITER_ALG0_RMS_ADDR
#define OUT5_LIMIT_RMS_TC_ADDR          MOD_OUT5_LIMITER_ALG0_RMS_ADDR
#define OUT6_LIMIT_RMS_TC_ADDR          MOD_OUT6_LIMITER_ALG0_RMS_ADDR
#define OUT7_LIMIT_RMS_TC_ADDR          MOD_OUT7_LIMITER_ALG0_RMS_ADDR
#define OUT8_LIMIT_RMS_TC_ADDR          MOD_OUT8_LIMITER_ALG0_RMS_ADDR



//#define GENERATOR_ENABLE

#define WHITE_NOISE_ENABLE_ADDR           MOD_WNOISE_ENABLENOISE_ADDR
#define WHITE_NOISE_GAIN_ADDR             MOD_WNOISE_GAIN_ALG0_SWGAINOPTADAU145XALG80TARGET_ADDR
#define WHITE_Aux1MixerGainSw_ADDR        MOD_WNOISE_AUX1MIXERSW_ALG0_MUTE_ADDR
#define WHITE_Aux2MixerGainSw_ADDR        MOD_WNOISE_AUX2MIXERSW_ALG0_MUTE_ADDR
#define WHITE_Aux3MixerGainSw_ADDR        MOD_WNOISE_AUX3MIXERSW_ALG0_MUTE_ADDR
#define WHITE_Aux4MixerGainSw_ADDR        MOD_WNOISE_AUX4MIXERSW_ALG0_MUTE_ADDR
#define WHITE_Aux5MixerGainSw_ADDR        MOD_WNOISE_AUX5MIXERSW_ALG0_MUTE_ADDR
#define WHITE_Aux6MixerGainSw_ADDR        MOD_WNOISE_AUX6MIXERSW_ALG0_MUTE_ADDR
#define WHITE_Aux7MixerGainSw_ADDR        MOD_WNOISE_AUX7MIXERSW_ALG0_MUTE_ADDR
#define WHITE_Aux8MixerGainSw_ADDR        MOD_WNOISE_AUX8MIXERSW_ALG0_MUTE_ADDR





#define SINE_ENABLE_ADDR                 MOD_SIN_ALG0_SINEPHASEGAINALGS3001GAIN00_ADDR
#define SINE_FREQUENCY_ADDR              MOD_SIN_ALG0_INCREMENT_ADDR  
#define SINE_GAIN_ADDR                   MOD_SIN_GAIN_ALG0_SWGAINOPTADAU145XALG83TARGET_ADDR 
#define SINE_Aux1MixerGainSw_ADDR        MOD_SIN_AUX1MIXERSW_ALG0_MUTE_ADDR
#define SINE_Aux2MixerGainSw_ADDR        MOD_SIN_AUX2MIXERSW_ALG0_MUTE_ADDR
#define SINE_Aux3MixerGainSw_ADDR        MOD_SIN_AUX3MIXERSW_ALG0_MUTE_ADDR
#define SINE_Aux4MixerGainSw_ADDR        MOD_SIN_AUX4MIXERSW_ALG0_MUTE_ADDR
#define SINE_Aux5MixerGainSw_ADDR        MOD_SIN_AUX5MIXERSW_ALG0_MUTE_ADDR
#define SINE_Aux6MixerGainSw_ADDR        MOD_SIN_AUX6MIXERSW_ALG0_MUTE_ADDR
#define SINE_Aux7MixerGainSw_ADDR        MOD_SIN_AUX7MIXERSW_ALG0_MUTE_ADDR
#define SINE_Aux8MixerGainSw_ADDR        MOD_SIN_AUX8MIXERSW_ALG0_MUTE_ADDR



#define SQUARE_ENABLE_ADDR                 MOD_SQUARE_ALG0_SQUAREWITHPHASEAMPALGS3001GAIN00_ADDR
#define SQUARE_FREQUENCY_ADDR              MOD_SQUARE_ALG0_INCREMENT_ADDR  
#define SQUARE_GAIN_ADDR                   MOD_SQUARE_GAIN_ALG0_SWGAINOPTADAU145XALG84TARGET_ADDR 
#define SQUARE_Aux1MixerGainSw_ADDR        MOD_SQUARE_AUX1MIXERSW_ALG0_MUTE_ADDR
#define SQUARE_Aux2MixerGainSw_ADDR        MOD_SQUARE_AUX2MIXERSW_ALG0_MUTE_ADDR
#define SQUARE_Aux3MixerGainSw_ADDR        MOD_SQUARE_AUX3MIXERSW_ALG0_MUTE_ADDR
#define SQUARE_Aux4MixerGainSw_ADDR        MOD_SQUARE_AUX4MIXERSW_ALG0_MUTE_ADDR
#define SQUARE_Aux5MixerGainSw_ADDR        MOD_SQUARE_AUX5MIXERSW_ALG0_MUTE_ADDR
#define SQUARE_Aux6MixerGainSw_ADDR        MOD_SQUARE_AUX6MIXERSW_ALG0_MUTE_ADDR
#define SQUARE_Aux7MixerGainSw_ADDR        MOD_SQUARE_AUX7MIXERSW_ALG0_MUTE_ADDR
#define SQUARE_Aux8MixerGainSw_ADDR        MOD_SQUARE_AUX8MIXERSW_ALG0_MUTE_ADDR



#define PULSE_ENABLE_ADDR                  MOD_PULSE_ALG0_ON_ADDR
#define PULSE_FREQUENCY_ADDR               MOD_PULSE_ALG0_FREQ_STEP_ADDR
#define PULSE_GAIN_ADDR                    MOD_PULSE_GAIN_ALG0_SWGAINOPTADAU145XALG82TARGET_ADDR
#define PULSE_DUTY_CYCLE_ADDR              MOD_PULSE_ALG0_TH_ADDR
#define PULSE_Aux1MixerGainSw_ADDR         MOD_PULSE_AUX1MIXERSW_ALG0_MUTE_ADDR
#define PULSE_Aux2MixerGainSw_ADDR         MOD_PULSE_AUX2MIXERSW_ALG0_MUTE_ADDR
#define PULSE_Aux3MixerGainSw_ADDR         MOD_PULSE_AUX3MIXERSW_ALG0_MUTE_ADDR
#define PULSE_Aux4MixerGainSw_ADDR         MOD_PULSE_AUX4MIXERSW_ALG0_MUTE_ADDR
#define PULSE_Aux5MixerGainSw_ADDR         MOD_PULSE_AUX5MIXERSW_ALG0_MUTE_ADDR
#define PULSE_Aux6MixerGainSw_ADDR         MOD_PULSE_AUX6MIXERSW_ALG0_MUTE_ADDR
#define PULSE_Aux7MixerGainSw_ADDR         MOD_PULSE_AUX7MIXERSW_ALG0_MUTE_ADDR
#define PULSE_Aux8MixerGainSw_ADDR         MOD_PULSE_AUX8MIXERSW_ALG0_MUTE_ADDR

#define SweepFreq_ENABLE_ADDR              MOD_SWEEPFREQ_ALG0_ON_ADDR
#define SweepFreq_ADDR                     MOD_SWEEPFREQ_ALG0_START_FREQ_ADDR



#define SweepFreq_Aux1MixerGainSw_ADDR         MOD_SWEEPFREQ_AUX1MIXERSW_ALG0_MUTE_ADDR
#define SweepFreq_Aux2MixerGainSw_ADDR         MOD_SWEEPFREQ_AUX2MIXERSW_ALG0_MUTE_ADDR
#define SweepFreq_Aux3MixerGainSw_ADDR         MOD_SWEEPFREQ_AUX3MIXERSW_ALG0_MUTE_ADDR
#define SweepFreq_Aux4MixerGainSw_ADDR         MOD_SWEEPFREQ_AUX4MIXERSW_ALG0_MUTE_ADDR
#define SweepFreq_Aux5MixerGainSw_ADDR         MOD_SWEEPFREQ_AUX5MIXERSW_ALG0_MUTE_ADDR
#define SweepFreq_Aux6MixerGainSw_ADDR         MOD_SWEEPFREQ_AUX6MIXERSW_ALG0_MUTE_ADDR
#define SweepFreq_Aux7MixerGainSw_ADDR         MOD_SWEEPFREQ_AUX7MIXERSW_ALG0_MUTE_ADDR
#define SweepFreq_Aux8MixerGainSw_ADDR         MOD_SWEEPFREQ_AUX8MIXERSW_ALG0_MUTE_ADDR




#define IN1_METER_ADDR    MOD_IN1_METER_ALG0_SINGLEBANDLEVELREADS3002LEVEL_ADDR
#define IN2_METER_ADDR    MOD_IN2_METER_ALG0_SINGLEBANDLEVELREADS3002LEVEL_ADDR
#define IN3_METER_ADDR    MOD_IN3_METER_ALG0_SINGLEBANDLEVELREADS3002LEVEL_ADDR
#define IN4_METER_ADDR    MOD_IN4_METER_ALG0_SINGLEBANDLEVELREADS3002LEVEL_ADDR
#define IN5_METER_ADDR    MOD_IN5_METER_ALG0_SINGLEBANDLEVELREADS3002LEVEL_ADDR
#define IN6_METER_ADDR    MOD_IN6_METER_ALG0_SINGLEBANDLEVELREADS3002LEVEL_ADDR
#define COAX_L_METER_ADDR MOD_IN7_METER_ALG0_SINGLEBANDLEVELREADS3002LEVEL_ADDR
#define COAX_R_METER_ADDR MOD_IN8_METER_ALG0_SINGLEBANDLEVELREADS3002LEVEL_ADDR

#define OUT1_METER_ADDR                        MOD_OUT1_METER_ALG0_SINGLEBANDLEVELREADS3001LEVEL_ADDR
#define OUT2_METER_ADDR                        MOD_OUT2_METER_ALG0_SINGLEBANDLEVELREADS3001LEVEL_ADDR
#define OUT3_METER_ADDR                        MOD_OUT3_METER_ALG0_SINGLEBANDLEVELREADS3001LEVEL_ADDR
#define OUT4_METER_ADDR                        MOD_OUT4_METER_ALG0_SINGLEBANDLEVELREADS3001LEVEL_ADDR
#define OUT5_METER_ADDR                        MOD_OUT5_METER_ALG0_SINGLEBANDLEVELREADS3001LEVEL_ADDR
#define OUT6_METER_ADDR                        MOD_OUT6_METER_ALG0_SINGLEBANDLEVELREADS3001LEVEL_ADDR
#define OUT7_METER_ADDR                        MOD_OUT7_METER_ALG0_SINGLEBANDLEVELREADS3001LEVEL_ADDR
#define OUT8_METER_ADDR                        MOD_OUT8_METER_ALG0_SINGLEBANDLEVELREADS3001LEVEL_ADDR
                                  
#define OUT1_LOWPASS_ADDR   MOD_OUT1_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR
#define OUT2_LOWPASS_ADDR   MOD_OUT2_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR
#define OUT3_LOWPASS_ADDR   MOD_OUT3_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR
#define OUT4_LOWPASS_ADDR   MOD_OUT4_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR
#define OUT5_LOWPASS_ADDR   MOD_OUT5_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR
#define OUT6_LOWPASS_ADDR   MOD_OUT6_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR
#define OUT7_LOWPASS_ADDR   MOD_OUT7_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR
#define OUT8_LOWPASS_ADDR   MOD_OUT8_LOWPASS_ALG0_LOW_FILT1_PARAMB2_ADDR



#define OUT1_HIGHPASS_ADDR   MOD_OUT1_HIGHPASS_ALG0_HIGH_FILT1_PARAMB2_ADDR
#define OUT2_HIGHPASS_ADDR   MOD_OUT2_HIGHPASS_ALG0_HIGH_FILT1_PARAMB2_ADDR
#define OUT3_HIGHPASS_ADDR   MOD_OUT3_HIGHPASS_ALG0_HIGH_FILT1_PARAMB2_ADDR
#define OUT4_HIGHPASS_ADDR   MOD_OUT4_HIGHPASS_ALG0_HIGH_FILT1_PARAMB2_ADDR
#define OUT5_HIGHPASS_ADDR   MOD_OUT5_HIGHPASS_ALG0_HIGH_FILT1_PARAMB2_ADDR
#define OUT6_HIGHPASS_ADDR   MOD_OUT6_HIGHPASS_ALG0_HIGH_FILT1_PARAMB2_ADDR
#define OUT7_HIGHPASS_ADDR   MOD_OUT7_HIGHPASS_ALG0_HIGH_FILT1_PARAMB2_ADDR
#define OUT8_HIGHPASS_ADDR   MOD_OUT8_HIGHPASS_ALG0_HIGH_FILT1_PARAMB2_ADDR

#define RTA_SWITCH_SLEW_ADDR      MOD_NX1_1_3_ALG0_SLEW_MODE_ADDR
#define RTA_SWITCH_ADDR           MOD_NX1_1_3_ALG0_MONOMUXS300SLEW2VOL00_ADDR
#define OUT1_RTA 0
#define OUT2_RTA 1
#define OUT3_RTA 2
#define OUT4_RTA 3
#define OUT5_RTA 4
#define OUT6_RTA 5
#define OUT7_RTA 6
#define OUT8_RTA 7

#define IN1_RTA 8
#define IN2_RTA 9
#define IN3_RTA 10
#define IN4_RTA 11
#define IN5_RTA 12
#define IN6_RTA 13
#define COAX_L_RTA 14
#define COAX_R_RTA 15

#define  RTA1_ADDR   MOD_RTA1_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA2_ADDR   MOD_RTA2_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA3_ADDR   MOD_RTA3_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA4_ADDR   MOD_RTA4_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA5_ADDR   MOD_RTA5_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA6_ADDR   MOD_RTA6_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA7_ADDR   MOD_RTA7_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA8_ADDR   MOD_RTA8_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA9_ADDR   MOD_RTA9_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA10_ADDR  MOD_RTA10_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA11_ADDR  MOD_RTA11_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA12_ADDR  MOD_RTA12_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA13_ADDR  MOD_RTA13_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA14_ADDR  MOD_RTA14_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA15_ADDR  MOD_RTA15_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA16_ADDR  MOD_RTA16_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA17_ADDR  MOD_RTA17_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA18_ADDR  MOD_RTA18_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA19_ADDR  MOD_RTA19_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA20_ADDR  MOD_RTA20_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA21_ADDR  MOD_RTA21_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA22_ADDR  MOD_RTA22_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA23_ADDR  MOD_RTA23_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA24_ADDR  MOD_RTA24_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA25_ADDR  MOD_RTA25_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA26_ADDR  MOD_RTA26_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA27_ADDR  MOD_RTA27_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA28_ADDR  MOD_RTA28_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA29_ADDR  MOD_RTA29_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA30_ADDR  MOD_RTA30_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR
#define  RTA31_ADDR  MOD_RTA31_ALG0_LEVELDETGROWPINOUTS3002RTAOUT0_ADDR




void To824(float param_dec, unsigned char* param_hex) ;
void gain_control(unsigned int module_addr,double gain);
void parametric_EQ_calculation(unsigned int safeload_parameter_addr,double boost,unsigned int frequency, unsigned int Fs,double gainlinear,double Q);
void low_shelf(unsigned int safeload_parameter_addr,double boost,unsigned int frequency, unsigned int Fs,double gainlinear,double slope);
void high_shelf(unsigned int safeload_parameter_addr,double boost,unsigned int frequency, unsigned int Fs,double gainlinear,double slope);
/////////////////////////////
void mute(unsigned int module_addr,unsigned char sw );
void invert(unsigned int  safeload_parameter_addr,unsigned int  safeload_parameter);
void aux_mixer_gain_sw(unsigned int module_addr,unsigned char data );
void aux_mixer_gain(unsigned int module_addr,double sw);
void Butterworth_12_dB_oct(unsigned int safeload_parameter_addr,unsigned int frequency, unsigned int Fs,unsigned int type,double gain);
void Butterworth_24_dB_oct(unsigned int safeload_parameter_addr,unsigned int frequency, unsigned int Fs,double gain);
void Linkwitz_Riley_12dB_oct(unsigned int safeload_parameter_addr,unsigned int frequency, unsigned int Fs,unsigned int type,double gain);


void compressor_threshold_ratio(unsigned int safeload_parameter_addr,double threshold,double ratio);
void compressor_decay_ms(unsigned int safeload_parameter_addr,unsigned int millisecond);
void compressor_hold_ms(unsigned int safeload_parameter_addr,unsigned int millisecond);
void compressor_RMS_TC_ms(unsigned int safeload_parameter_addr,unsigned int millisecond);

void limit_threshold(unsigned int safeload_parameter_addr, double threshold);
void limit_RMS_TC_ms(unsigned int safeload_parameter_addr,unsigned int millisecond);
void limit_decay_ms(unsigned int safeload_parameter_addr,unsigned int millisecond);

void white_noise_enable(unsigned int module_addr,unsigned char enable);
void white_noise_gain(unsigned int module_addr,double gain);
void white_noise_aux_mixer_gain_sw(unsigned int module_addr,unsigned char sw );


void sine_enable(unsigned int module_addr,unsigned char enable);
void sine_gain(unsigned int module_addr,double gain);
void sine_aux_mixer_gain_sw(unsigned int module_addr,unsigned char sw );
void sine_frequency(unsigned int safeload_parameter_addr,unsigned int frequency);

void square_enable(unsigned int module_addr,unsigned char enable);
void square_gain(unsigned int module_addr,double gain);
void square_aux_mixer_gain_sw(unsigned int module_addr,unsigned char sw );
void square_frequency(unsigned int safeload_parameter_addr,unsigned int frequency);

void pulse_enable(unsigned int module_addr,unsigned char enable);
void pulse_gain(unsigned int module_addr,double gain);
void pulse_aux_mixer_gain_sw(unsigned int module_addr,unsigned char sw );
void pulse_frequency(unsigned int safeload_parameter_addr,unsigned int frequency);
void pulse_th(unsigned int module_addr,double percent );

void sweepfreq_enable(unsigned int safeload_parameter_addr,unsigned char enable);
void sweepfreq(unsigned int safeload_parameter_addr,double start_freq ,double stop_freq,unsigned int cycles_per_step,double steps);
void sweepfreq_aux_mixer_gain_sw(unsigned int module_addr,unsigned char sw );
void DC(unsigned int module_addr,double data );
double meter(unsigned int module_addr);

void Butterworth_24_dB_oct_lowpass(unsigned int safeload_parameter_addr,unsigned int frequency, unsigned int Fs,double gain);
void Butterworth_24_dB_oct_highpass(unsigned int safeload_parameter_addr,unsigned int frequency, unsigned int Fs,double gain);
void Linkwitz_Riley_24dB_oct_lowpass(unsigned int safeload_parameter_addr,unsigned int frequency, unsigned int Fs,double gain);
void Linkwitz_Riley_24dB_oct_highpass(unsigned int safeload_parameter_addr,unsigned int frequency, unsigned int Fs,double gain);
void Bessel_24_dB_oct_lowpass(unsigned int safeload_parameter_addr,unsigned int frequency, unsigned int Fs,double gain);
void Bessel_24_dB_oct_highpass(unsigned int safeload_parameter_addr,unsigned int frequency, unsigned int Fs,double gain);
void noise_gate_threshold(unsigned int safeload_parameter_addr,double threshold);
void noise_gate_RMS_TC_ms(unsigned int safeload_parameter_addr,unsigned int millisecond);
void noise_gate_decay_ms(unsigned int safeload_parameter_addr,unsigned int millisecond);
double read_824_data(unsigned int module_addr);

void RTA_switch(unsigned int safeload_parameter_addr,unsigned char sw );
void delay(unsigned int module_addr,unsigned int delay);
#endif










