/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "data.h"
#include "rtc.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_1 (GUI_ID_USER + 0x02)
#define ID_BUTTON_2 (GUI_ID_USER + 0x03)
#define ID_BUTTON_3 (GUI_ID_USER + 0x04)
#define ID_BUTTON_4 (GUI_ID_USER + 0x05)
#define ID_BUTTON_5 (GUI_ID_USER + 0x06)
#define ID_BUTTON_6 (GUI_ID_USER + 0x07)
#define ID_BUTTON_7 (GUI_ID_USER + 0x08)
#define ID_BUTTON_8 (GUI_ID_USER + 0x09)
#define ID_BUTTON_9 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_10 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_11 (GUI_ID_USER + 0x0C)
#define ID_BUTTON_12 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_13 (GUI_ID_USER + 0x0E)
#define ID_BUTTON_14 (GUI_ID_USER + 0x0F)
#define ID_BUTTON_15 (GUI_ID_USER + 0x10)
#define ID_BUTTON_16 (GUI_ID_USER + 0x11)
#define  ID_TEXT_0   (GUI_ID_USER + 0x12)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static Current USE_Data;  //需要的使用数据
static Time_First_Data* Current_Data;

static const GUI_POINT pPoint_left[] = {
	{ 0, 10 },
	{ 10, 0 },
	{ 10, 20 },
};

static const GUI_POINT pPoint_right[] = {
	{ 10 + 20, 0 },
	{ 20 + 20, 10 },
	{ 10 + 20, 20 },
};

/*
*******************************************************************************************
* 函 数 名: Show_Value
* 功能说明: 显示数值
* 形 参: 无
* 返 回 值: 无
*******************************************************************************************
*/
#define		BAND_X		300
#define 	BAND_Y   	75
#define 	FREQ_Y   	BAND_Y+34
#define  	TYPE_Y		FREQ_Y+34
#define 	GAIN_Y		TYPE_Y+34
#define		Q_Y			GAIN_Y+34

#define YEAR_MAX  	2099
#define YEAR_MIN	1970
#define MONTH_MAX	12
#define MONTH_MIN	1
#define DATE_MAX	31
#define DATE_MIN	1
#define HOUR_MAX	23
#define	HOUR_MIN	0
#define MINUTE_MAX	59
#define MINUTE_MIN	0

//定义无效区域
static const GUI_RECT Rect[] = {
	{ BAND_X-50, 34, 	 BAND_X+50, 34+25},
	{ BAND_X-50, BAND_Y, BAND_X+50, BAND_Y+20},
	{ BAND_X-50, FREQ_Y, BAND_X+50, FREQ_Y+20},
	{ BAND_X-50, TYPE_Y, BAND_X+50, TYPE_Y+20},
	{ BAND_X-50, GAIN_Y, BAND_X+50, GAIN_Y+20},
	{ BAND_X-50, Q_Y, 	 BAND_X+50, Q_Y+20},
};

static void Show_Value(void)
{
	char str[10];
	char over;
	s16 *temp;
	s32 date_max;
	
	GUI_SetColor(GUI_BLACK); 		//设置颜色
	GUI_SetTextMode(GUI_TM_TRANS);  //设置透明模式
	GUI_SetFont(&GUI_Font20_1); 	//设置字体
	
	//YEAR
	over = Max_Min(USE_Data.First_data,YEAR_MAX,YEAR_MIN);
	Current_Data->overflow |= (over<<First_Item);
	snprintf(str,sizeof(str) - 1,"%d",*USE_Data.First_data);  //把数值转为字符串
	GUI_DispStringHCenterAt(str,300,41);
	
	//MONTH
	over = Max_Min(USE_Data.Second_data,MONTH_MAX,MONTH_MIN);
	Current_Data->overflow |= (over<<Second_Item);
	snprintf(str,sizeof(str) - 1,"%d",*USE_Data.Second_data);  //把数值转为字符串
	GUI_DispStringHCenterAt(str,300,75);
	
	//DATE
	//判断是否闰年和是否为2月份
	if(Is_Leap_Year(*USE_Data.First_data) &&(*USE_Data.Second_data == 2))
	{
		date_max = 29;
	}
	//2月份平年
	else if(*USE_Data.Second_data == 2)
	{
		date_max = 28;
	}
	//30日的月份
	else if((*USE_Data.Second_data == 4) ||(*USE_Data.Second_data == 6)||
			(*USE_Data.Second_data == 9) ||(*USE_Data.Second_data == 11))
	{
		date_max = 30;
	}
	else
	{
		date_max = 31;
	}
	over = Max_Min(USE_Data.Third_data,date_max,DATE_MIN);
	Current_Data->overflow |= (over<<Third_Item);
	snprintf(str,sizeof(str) - 1,"%d",*USE_Data.Third_data);  //把数值转为字符串
	GUI_DispStringHCenterAt(str,300,109);
	
	//HOUR
	over = Max_Min(USE_Data.Four_data,HOUR_MAX,HOUR_MIN);
	Current_Data->overflow |= (over<<Four_Item);
	snprintf(str,sizeof(str) - 1,"%d",*USE_Data.Four_data);  //把数值转为字符串
	GUI_DispStringHCenterAt(str,300,143);
	
	//MINUTE
	over = Max_Min(USE_Data.Five_data,MINUTE_MAX,MINUTE_MIN);
	Current_Data->overflow |= (over<<Five_Item);
	snprintf(str,sizeof(str) - 1,"%d",*USE_Data.Five_data);  //把数值转为字符串
	GUI_DispStringHCenterAt(str,300,176);
}

//左边三角形
static void _cbButton_left(WM_MESSAGE * pMsg) //--------------（3）
{
	WM_HWIN hWin;
	hWin = pMsg->hWin;
	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		if (BUTTON_IsPressed(hWin))
		{
			//画红色三角形
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_left, 3, 0, 0);
		}
		else
		{
			//画黑色三角形
			GUI_SetColor(GUI_BLACK);
			GUI_FillPolygon(pPoint_left, 3, 0, 0);
		}

		break;

		//处理默认信息
	default:
		BUTTON_Callback(pMsg);
	}
}

//右边三角形

static void _cbButton_right(WM_MESSAGE * pMsg) //--------------（3）
{
	WM_HWIN hWin;

	//	const GUI_PID_STATE* pState = (const GUI_PID_STATE*)pMsg->Data.p;
	hWin = pMsg->hWin;

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		if (BUTTON_IsPressed(hWin))
		{
			//画红色三角形
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}
		else
		{
			//画黑色三角形
			GUI_SetColor(GUI_BLACK);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}
		break;

	default:
		BUTTON_Callback(pMsg);
	}
}
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 400, 240, 0, 0x0, 0 },

	//INPUT 2/3
	{ TEXT_CreateIndirect, "Text", ID_TEXT_0, 109, 3, 194, 28, 0, 0, 0 },

	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 0, 34, 198, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 0, 68, 198, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 0, 102, 198, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 0, 136, 198, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 0, 170, 198, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 0, 204, 198, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_6, 202, 204, 196, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_7, 208, 38, 40, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_8, 208, 72, 40, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_9, 208, 106, 40, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_10, 208, 140, 40, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_11, 208, 174, 40, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_12, 350, 38, 40, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_13, 350, 72, 40, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_14, 350, 106, 40, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_15, 350, 140, 40, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_16, 350, 174, 40, 25, 0, 0x0, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	int     NCode;
	int     Id;
	// USER START (Optionally insert additional variables)
	// USER END

	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		//TEXT设置
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem, "TIME  SETTINGS");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);
		BUTTON_SetText(hItem, "YEAR");
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);
		BUTTON_SetText(hItem, "MONTH");
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);
		BUTTON_SetText(hItem, "DATE");
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);
		BUTTON_SetText(hItem, "HOUR");
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);
		BUTTON_SetText(hItem, "MINUTE");
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);
		BUTTON_SetText(hItem, "SET");
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);
		BUTTON_SetText(hItem, "ESC");

		//left
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		//right
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点
		// USER START (Optionally insert additional code for further widget initialization)
		// USER END
		break;
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
			
		//点击主标题  退出
		case ID_TEXT_0:
			switch(NCode)
			{
				case WM_NOTIFICATION_RELEASED:
						GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
						hWin_now = CreateMainface();  //页面
						break;
			}
			break;
			
		case ID_BUTTON_0: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_SetFocus(WM_GetDialogItem(pMsg->hWin, Id));
				Current_Data->Item = First_Item;
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_1: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_SetFocus(WM_GetDialogItem(pMsg->hWin, Id));
				Current_Data->Item = Second_Item;
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_2: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_SetFocus(WM_GetDialogItem(pMsg->hWin, Id));
				Current_Data->Item = Third_Item;
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_3: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_SetFocus(WM_GetDialogItem(pMsg->hWin, Id));
				Current_Data->Item = Four_Item;
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_4: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_SetFocus(WM_GetDialogItem(pMsg->hWin, Id));
				Current_Data->Item = Five_Item;
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_5: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_SetFocus(WM_GetDialogItem(pMsg->hWin, Id));
				break;
			case WM_NOTIFICATION_RELEASED:
				//重新设置时间
				RTC_Set(*USE_Data.First_data,*USE_Data.Second_data,*USE_Data.Third_data,
						*USE_Data.Four_data,*USE_Data.Five_data,0);
				GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
				hWin_now = CreateMainface();  //显示Output_First页面
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_6: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				WM_SetFocus(WM_GetDialogItem(pMsg->hWin, Id));
				break;
			case WM_NOTIFICATION_RELEASED:
				GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
				hWin_now = CreateMainface();  //显示Output_First页面
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		//left
		case ID_BUTTON_7: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				Current_Data->change_item = First_Item;  //子选项改变
				Time_add_dec(USE_Data.First_data,&Rect[First_Item],&Current_Data->hItime,First_Time_left,pMsg);
				WM_InvalidateRect(pMsg->hWin,&Rect[Third_Item]);
				break;
			case WM_NOTIFICATION_RELEASED:
				Time_end(&Current_Data->Time_count,Current_Data->hItime);
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_8: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				Current_Data->change_item = Second_Item;  //子选项改变
				Time_add_dec(USE_Data.Second_data,&Rect[Second_Item],&Current_Data->hItime,Second_Time_left,pMsg);
				WM_InvalidateRect(pMsg->hWin,&Rect[Third_Item]);
				break;
			case WM_NOTIFICATION_RELEASED:
				Time_end(&Current_Data->Time_count,Current_Data->hItime);
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_9: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				Current_Data->change_item = Third_Item;  //子选项改变
				Time_add_dec(USE_Data.Third_data,&Rect[Third_Item],&Current_Data->hItime,Third_Time_left,pMsg);
				break;
			case WM_NOTIFICATION_RELEASED:
				Time_end(&Current_Data->Time_count,Current_Data->hItime);
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_10: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				Current_Data->change_item = Four_Item;  //子选项改变
				Time_add_dec(USE_Data.Four_data ,&Rect[Four_Item],&Current_Data->hItime,Four_Time_left,pMsg);
				break;
			case WM_NOTIFICATION_RELEASED:
				Time_end(&Current_Data->Time_count,Current_Data->hItime);
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_11: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				Current_Data->change_item = Five_Item;  //子选项改变
				Time_add_dec(USE_Data.Five_data ,&Rect[Five_Item],&Current_Data->hItime,Five_Time_left,pMsg);
				break;
			case WM_NOTIFICATION_RELEASED:
				Time_end(&Current_Data->Time_count,Current_Data->hItime);
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
			
		//right
		case ID_BUTTON_12: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				Current_Data->change_item = First_Item;  //子选项改变
				Time_add_dec(USE_Data.First_data,&Rect[First_Item],&Current_Data->hItime,First_Time_right,pMsg);
				WM_InvalidateRect(pMsg->hWin,&Rect[Third_Item]);
				break;
			case WM_NOTIFICATION_RELEASED:
				Time_end(&Current_Data->Time_count,Current_Data->hItime);
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_13: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				Current_Data->change_item = Second_Item;  //子选项改变
				Time_add_dec(USE_Data.Second_data,&Rect[Second_Item],&Current_Data->hItime,Second_Time_right,pMsg);
				WM_InvalidateRect(pMsg->hWin,&Rect[Third_Item]);
				break;
			case WM_NOTIFICATION_RELEASED:
				Time_end(&Current_Data->Time_count,Current_Data->hItime);
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_14: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				Current_Data->change_item = Third_Item;  //子选项改变
				Time_add_dec(USE_Data.Third_data,&Rect[Third_Item],&Current_Data->hItime,Third_Time_right,pMsg);
				break;
			case WM_NOTIFICATION_RELEASED:
				Time_end(&Current_Data->Time_count,Current_Data->hItime);
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_15: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				Current_Data->change_item = Four_Item;  //子选项改变
				Time_add_dec(USE_Data.Four_data ,&Rect[Four_Item],&Current_Data->hItime,Four_Time_right,pMsg);
				break;
			case WM_NOTIFICATION_RELEASED:
				Time_end(&Current_Data->Time_count,Current_Data->hItime);
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_16: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				Current_Data->change_item = Five_Item;  //子选项改变
				Time_add_dec(USE_Data.Five_data ,&Rect[Five_Item],&Current_Data->hItime,Five_Time_right,pMsg);
				break;
			case WM_NOTIFICATION_RELEASED:
				Time_end(&Current_Data->Time_count,Current_Data->hItime);
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
			// USER START (Optionally insert additional code for further Ids)
			// USER END
		}
		break;
		// USER START (Optionally insert additional message handling)
		// USER END
		
	/********************************定时器**********************************/
	case WM_TIMER:
		Id = WM_GetTimerId(pMsg->Data.v);
		switch(Id)  //根据不同定时器的ID号来处理不同的信息
		{
			//STR VOL
			case First_Time_left:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_7)))
				{
					Current_Data->change_item = First_Item;
					Time_long_press(pMsg,USE_Data.First_data,&Current_Data->Time_count,&Rect[First_Item],Id);
					WM_InvalidateRect(pMsg->hWin,&Rect[Third_Item]);
				}
				break;
				
			case Second_Time_left:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_8)))
				{
					Current_Data->change_item = Second_Item;
					Time_long_press(pMsg,USE_Data.Second_data,&Current_Data->Time_count,&Rect[Second_Item],Id);
					WM_InvalidateRect(pMsg->hWin,&Rect[Third_Item]);
				}
				break;
				
			case Third_Time_left:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_9)))
				{
					Current_Data->change_item = Third_Item;
					Time_long_press(pMsg,USE_Data.Third_data,&Current_Data->Time_count,&Rect[Third_Item],Id);
				}
				break;
				
			case First_Time_right:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_12)))
				{
					Current_Data->change_item = First_Item;
					Time_long_press(pMsg,USE_Data.First_data,&Current_Data->Time_count,&Rect[First_Item],Id);
					WM_InvalidateRect(pMsg->hWin,&Rect[Third_Item]);
				}
				break;
				
			case Second_Time_right:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_13)))
				{
					Current_Data->change_item = Second_Item;
					Time_long_press(pMsg,USE_Data.Second_data,&Current_Data->Time_count,&Rect[Second_Item],Id);
					WM_InvalidateRect(pMsg->hWin,&Rect[Third_Item]);
				}
				break;
				
			case Third_Time_right:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_14)))
				{
					Current_Data->change_item = Third_Item;
					Time_long_press(pMsg,USE_Data.Third_data,&Current_Data->Time_count,&Rect[Third_Item],Id);
				}
				break;
			
			//END VOL
			case Four_Time_left:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_10)))
				{
					Current_Data->change_item = Four_Item;
					Time_long_press(pMsg,USE_Data.Four_data,&Current_Data->Time_count,&Rect[Four_Item],Id);
				}
				break; 
				
			case Five_Time_left:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_11)))
				{
					Current_Data->change_item = Five_Item;
					Time_long_press(pMsg,USE_Data.Five_data,&Current_Data->Time_count,&Rect[Five_Item],Id);
				}
				break; 
				

				
			case Four_Time_right:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_15)))
				{
					Current_Data->change_item = Four_Item;
					Time_long_press(pMsg,USE_Data.Four_data,&Current_Data->Time_count,&Rect[Four_Item],Id);
				}
				break; 
				
			case Five_Time_right:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_16)))
				{
					Current_Data->change_item = Five_Item;
					Time_long_press(pMsg,USE_Data.Five_data,&Current_Data->Time_count,&Rect[Five_Item],Id);
				}
				break; 
				
		}
		break;
		
	case WM_PAINT:
		GUI_SetBkColor(GUI_BLACK);
		GUI_Clear();

		//标题项
		GUI_SetColor(GUI_RED);
		GUI_FillRoundedRect(0, 0, 400, 30, 4);

		//白色条
		GUI_SetColor(GUI_WHITE);
		GUI_FillRoundedRect(202, 34, 396, 34 + 30, 4);
		GUI_FillRoundedRect(202, 68, 396, 68 + 30, 4);
		GUI_FillRoundedRect(202, 102, 396, 102 + 30, 4);
		GUI_FillRoundedRect(202, 136, 396, 136 + 30, 4);
		GUI_FillRoundedRect(202, 170, 396, 170 + 30, 4);
	
		//显示数值
		Show_Value();
		break;
	
	/*********************************************自定义信息处理**************************************************/
	//旋钮左转
	case MSG_KNOB_CONTROL_LEFT:
		Item_change(&(Current_Data->Item),First_Item,Seven_Item,Next_dir);
		GUI_SendKeyMsg(GUI_KEY_TAB, 1);     //下一个聚焦点
		break;
	
	//旋钮右转
	case MSG_KNOB_CONTROL_RIGHT:
		Item_change(&(Current_Data->Item),First_Item,Seven_Item,Last_dir);
		GUI_SendKeyMsg(GUI_KEY_BACKTAB, 1); //上一个聚焦
		break;
	
	//CONTROL按下
	case MSG_KEY_CONTROL:
		GUI_SendKeyMsg(GUI_KEY_ENTER, 1);   //确定
		break;
	
	//ESC
	case MSG_KEY_ESC:
		GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
        hWin_now = CreateMainface();  //显示Output_First页面
		break;
	
	//没有旋钮动作
	case MSG_KNOB_NULL:
		Current_Data->Key_count 		= 0;
		Current_Data->dir 				= 0;
		break;
	
	//INPUT右转
	case MSG_KNOB_INPUT_RIGHT:
		if(Current_Data->dir	== 1)
		{
			Current_Data->Key_count = 0;
		}
		Current_Data->dir = 2;
		switch(Current_Data->Item)
		{
			//YEAR
			case First_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_dec(USE_Data.First_data,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				WM_InvalidateRect(pMsg->hWin,&Rect[Third_Item]);
				break;
			
			//MONTH
			case Second_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_dec(USE_Data.Second_data,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				WM_InvalidateRect(pMsg->hWin,&Rect[Third_Item]);
				break;
			
			//DATE
			case Third_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_dec(USE_Data.Third_data,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				break;
			
			//HOUR
			case Four_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_dec(USE_Data.Four_data,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				break;
			
			//MINUTE
			case Five_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_dec(USE_Data.Five_data,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				break;
		}
		break;
	
	//INPUT左转
	case MSG_KNOB_INPUT_LEFT:
		if(Current_Data->dir	== 2)
		{
			Current_Data->Key_count = 0;
		}
		Current_Data->dir = 1;
		switch(Current_Data->Item)
		{
			//YEAR
			case First_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_add(USE_Data.First_data,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				WM_InvalidateRect(pMsg->hWin,&Rect[Third_Item]);
				break;
			
			//MONTH
			case Second_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_add(USE_Data.Second_data,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				WM_InvalidateRect(pMsg->hWin,&Rect[Third_Item]);
				break;
			
			//DATE
			case Third_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_add(USE_Data.Third_data,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				break;
			
			//HOUR
			case Four_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_add(USE_Data.Four_data,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				break;
			
			//MINUTE
			case Five_Item:
				Current_Data->change_item = Current_Data->Item;
				Value_Change_add(USE_Data.Five_data,&Current_Data->Key_count);
				WM_InvalidateRect(pMsg->hWin,&Rect[Current_Data->Item]); //无效化该区域重新刷新
				break;
		}
		break;
	
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
static void Init_data(Time_First_Data *L)
{
	L->Item			=	First_Item;
	L->change_item		=	-1;
	L->Key_count		=	0;
	L->Time_count		=	0;
	
	
	//初始化变量
	USE_Data.First_data 	=	&L->data.YEAR_DATA;
	USE_Data.Second_data	=	&L->data.MONTH_DATA;
	USE_Data.Third_data		=	&L->data.DATE_DATA;
	USE_Data.Four_data 		= 	&L->data.HOUR_DATA;
	USE_Data.Five_data 		= 	&L->data.MINUTE_DATA;
	//没有复选框
	
	/*此处应该更新时间*/
	RTC_Get();//更新时间
	*USE_Data.First_data	=calendar.w_year;
	*USE_Data.Second_data	=calendar.w_month;
	*USE_Data.Third_data	=calendar.w_date;
	*USE_Data.Four_data		=calendar.hour;
	*USE_Data.Five_data		=calendar.min;
}


WM_HWIN Time_First(void) {
	WM_HWIN hWin;
	
	
	Button_flex_2();
	
	Init_data(Time_first);  //初始化数据
	
	Current_Data = Time_first;
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
