/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_SLIDER_0 (GUI_ID_USER + 0x01)
#define ID_SLIDER_1 (GUI_ID_USER + 0x02)
#define ID_SLIDER_2 (GUI_ID_USER + 0x03)
#define ID_SLIDER_3 (GUI_ID_USER + 0x04)
#define ID_SLIDER_4 (GUI_ID_USER + 0x05)
#define ID_SLIDER_5 (GUI_ID_USER + 0x06)
#define ID_SLIDER_6 (GUI_ID_USER + 0x07)
#define ID_SLIDER_7 (GUI_ID_USER + 0x08)
#define ID_TEXT_0 (GUI_ID_USER + 0x09)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x0A)
#define ID_CHECKBOX_1 (GUI_ID_USER + 0x0B)
#define ID_CHECKBOX_2 (GUI_ID_USER + 0x0C)
#define ID_CHECKBOX_3 (GUI_ID_USER + 0x0D)
#define ID_CHECKBOX_4 (GUI_ID_USER + 0x0E)
#define ID_CHECKBOX_5 (GUI_ID_USER + 0x0F)
#define ID_CHECKBOX_6 (GUI_ID_USER + 0x10)
#define ID_CHECKBOX_7 (GUI_ID_USER + 0x11)
#define ID_TEXT_1 (GUI_ID_USER + 0x12)
#define ID_TEXT_2 (GUI_ID_USER + 0x13)
#define ID_TEXT_3 (GUI_ID_USER + 0x14)
#define ID_TEXT_4 (GUI_ID_USER + 0x15)
#define ID_TEXT_5 (GUI_ID_USER + 0x16)
#define ID_TEXT_6 (GUI_ID_USER + 0x17)
#define ID_TEXT_7 (GUI_ID_USER + 0x18)
#define ID_TEXT_8 (GUI_ID_USER + 0x19)
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
#define Text_y  195
#define text_color GUI_BLACK
static char value[8]; //用来显示的值

//无效区域设置
static GUI_RECT Rect[] =
{
	{ 10,  Text_y, 40,  Text_y+20 },
	{ 50,  Text_y, 80,  Text_y+20 },
	{ 90, Text_y, 120, Text_y+20 },
	{ 130, Text_y, 160, Text_y+20 },
	{ 170, Text_y, 200, Text_y+20 },
	{ 210, Text_y, 240, Text_y+20 },
	{ 250, Text_y, 280, Text_y+20 },
	{ 290, Text_y, 320, Text_y+20 },
};

//显示滑块值
static void _ShowSlidervalue(void)
{
	GUI_SetColor(GUI_BLACK); //设置颜色
	GUI_SetTextMode(GUI_TM_TRANS); //设置透明模式
	GUI_SetFont(&GUI_Font20_1); //设置字体

	GUI_GotoXY(10, Text_y);  //设置1位置
	GUI_DispDecMin(-value[0]); //显示值
	GUI_GotoXY(50, Text_y);  //设置2位置
	GUI_DispDecMin(-value[1]); //显示值
	GUI_GotoXY(90, Text_y);  //设置3位置
	GUI_DispDecMin(-value[2]); //显示值
	GUI_GotoXY(130, Text_y);  //设置4位置
	GUI_DispDecMin(-value[3]); //显示值
	GUI_GotoXY(170, Text_y);  //设置5位置
	GUI_DispDecMin(-value[4]); //显示值
	GUI_GotoXY(210, Text_y);  //设置6位置
	GUI_DispDecMin(-value[5]); //显示值
	GUI_GotoXY(250, Text_y);  //设置7位置
	GUI_DispDecMin(-value[6]); //显示值
	GUI_GotoXY(290, Text_y);  //设置8位置
	GUI_DispDecMin(-value[7]); //显示值

}
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 400, 240, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_0, 109, 3, 194, 28, 0, 0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 5, 40, 34, 150, SLIDER_CF_VERTICAL, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_1, 45, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_2, 85, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_3, 125, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_4, 165, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_5, 205, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_6, 245, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_7, 285, 40, 34, 150, 8, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 330, 35, 60, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_1, 330, 60, 60, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_2, 330, 85, 60, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_3, 330, 110, 60, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_4, 330, 135, 60, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_5, 330, 160, 60, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_6, 330, 185, 60, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_7, 330, 210, 60, 23, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_1, 8, 212, 30, 240-212, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_2, 48, 212, 30, 240 - 212, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_3, 88, 212, 30, 240 - 212, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_4, 128, 212, 30, 240 - 212, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_5, 168, 212, 30, 240 - 212, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_6, 208, 212, 30, 240 - 212, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_7, 248, 212, 30, 240 - 212, 0, 0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_8, 288, 212, 30, 240 - 212, 0, 0, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	// USER START (Optionally insert additional variables)
	// USER END
	WM_HWIN hItem;
	int     NCode;
	int     Id;

	switch (pMsg->MsgId) {
		// USER START (Optionally insert additional message handling)
		// USER END
	case WM_INIT_DIALOG:
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem, "INPUT PAGE 3/3");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem, GUI_WHITE);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem, "AUX1");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetText(hItem, "AUX2");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
		TEXT_SetText(hItem, "AUX3");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);


		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
		TEXT_SetText(hItem, "AUX4");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
		TEXT_SetText(hItem, "AUX5");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
		TEXT_SetText(hItem, "AUX6");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
		TEXT_SetText(hItem, "AUX7");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
		TEXT_SetText(hItem, "AUX8");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
		TEXT_SetTextColor(hItem, text_color);

		//复选框
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
		CHECKBOX_SetText(hItem, "AUX1");
		CHECKBOX_SetTextColor(hItem,GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
		CHECKBOX_SetText(hItem, "AUX2");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2);
		CHECKBOX_SetText(hItem, "AUX3");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3);
		CHECKBOX_SetText(hItem, "AUX4");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_4);
		CHECKBOX_SetText(hItem, "AUX5");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_5);
		CHECKBOX_SetText(hItem, "AUX6");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_6);
		CHECKBOX_SetText(hItem, "AUX7");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_7);
		CHECKBOX_SetText(hItem, "AUX8");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_16B_1);

		//滑块
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, 80);
		//SLIDER_SetSkin(hItem, SLIDER_DrawSkinFlex); //可以用回之前的皮肤


		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, 80);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_2);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, 80);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_3);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, 80);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_4);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, 80);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_5);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, 80);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_6);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, 80);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_7);
		SLIDER_SetRange(hItem, 0, 80);  //要取绝对值
		SLIDER_SetValue(hItem, 80);



		break;

	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
		case ID_SLIDER_0: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0); //获得滑块句柄
				value[0] = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[0]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_1: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1); //获得滑块句柄
				value[1] = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[1]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_2: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_2); //获得滑块句柄
				value[2] = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[2]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_3: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_3); //获得滑块句柄
				value[3] = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[3]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_4: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_4); //获得滑块句柄
				value[4] = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[4]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_5: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_5); //获得滑块句柄
				value[5] = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[5]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_6: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_6); //获得滑块句柄
				value[6] = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[6]); //无效化该值重新刷新显示值

				//SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_7), value[6]);
				//WM_InvalidateRect(pMsg->hWin, &Rect[7]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_7: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_7); //获得滑块句柄
				value[7] = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[7]); //无效化该值重新刷新显示值

				//SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_6), value[7]);
				//WM_InvalidateRect(pMsg->hWin, &Rect[6]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		}
		break;

	case WM_PAINT:

		//背景
		GUI_SetBkColor(GUI_BLACK);
		GUI_Clear();

		//第一项
		GUI_SetColor(GUI_RED);
		GUI_FillRoundedRect(0, 0, 400, 30, 4);

		//滑块背景
		GUI_SetColor(GUI_LIGHTBLUE);
		GUI_FillRoundedRect(0, 35, 320, 236, 4);

		//色块
		GUI_SetColor(GUI_BLUE);
		GUI_FillRoundedRect(325, 34, 395, 236, 4);
		/*GUI_SetColor(GUI_BLACK);
		GUI_FillRoundedRect(0, 200, 320, 240, 4);*/

		//显示值色块
		GUI_SetColor(GUI_WHITE);
		GUI_FillRoundedRect(5, Text_y, 41, Text_y + 17, 2);
		GUI_FillRoundedRect(45, Text_y, 81, Text_y + 17, 2);
		GUI_FillRoundedRect(85, Text_y,  121, Text_y + 17, 2);
		GUI_FillRoundedRect(125, Text_y, 161, Text_y + 17, 2);
		GUI_FillRoundedRect(165, Text_y, 201, Text_y + 17, 2);
		GUI_FillRoundedRect(205, Text_y, 241, Text_y + 17, 2);
		GUI_FillRoundedRect(245, Text_y, 281, Text_y + 17, 2);
		GUI_FillRoundedRect(285, Text_y, 318, Text_y + 17, 2);

		_ShowSlidervalue(); //显示数值
		break;



	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN Input_Third(void) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
