/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "data.h"
#include "algorithm.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define Text_y  19

#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_SLIDER_0 (GUI_ID_USER + 0x01)
#define ID_SLIDER_1 (GUI_ID_USER + 0x02)
#define ID_SLIDER_2 (GUI_ID_USER + 0x03)
#define ID_SLIDER_3 (GUI_ID_USER + 0x04)
#define ID_SLIDER_4 (GUI_ID_USER + 0x05)
#define ID_SLIDER_5 (GUI_ID_USER + 0x06)
#define ID_SLIDER_6 (GUI_ID_USER + 0x07)
#define ID_SLIDER_7 (GUI_ID_USER + 0x08)
#define ID_BUTTON_0 (GUI_ID_USER + 0x09)
#define ID_BUTTON_1 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_2 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0C)
#define ID_BUTTON_4 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_5 (GUI_ID_USER + 0x0E)
#define ID_BUTTON_6 (GUI_ID_USER + 0x0F)
#define ID_BUTTON_7 (GUI_ID_USER + 0x10)
#define ID_TEXT_0 (GUI_ID_USER + 0x11)
#define ID_TEXT_1 (GUI_ID_USER + 0x12)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

/***************************************该页面需要用到的数据***************************************/
//申请关于Input界面的数据
//static Input_First_data *In_first; //数据结构体指针
//选中通道指示器
char INPUT_CHANNEL = 0;
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 400, 240, 0, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 5, 40, 34, 150, SLIDER_CF_VERTICAL, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_1, 55, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_2, 105, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_3, 155, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_4, 205, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_5, 255, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_6, 305, 40, 34, 150, 8, 0x0, 0 },
	{ SLIDER_CreateIndirect, "Slider", ID_SLIDER_7, 355, 40, 34, 150, 8, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 1, 200, 45, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 50, 200, 45, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 100, 200, 45, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 150, 200, 45, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 200, 200, 45, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 250, 200, 45, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_6, 300, 200, 45, 35, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_7, 350, 200, 48, 35, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_0, 59, 0, 294, 28, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_1, 370, 0, 30, 20, 0, 0x64, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/


//无效区域设置
static GUI_RECT Rect[] =
{
	{ 10, 17, 40, 37 },
	{ 60, 17, 90, 37 },
	{ 110, 17, 140, 37 },
	{ 160, 17, 190, 37 },
	{ 210, 17, 240, 37 },
	{ 260, 17, 290, 37 },
	{ 310, 17, 340, 37 },
	{ 360, 17, 390, 37 },
};

#define siler_x  5  //位置x
#define step_slider  0.04    //步进
#define slider_max   2000

//显示滑块值
static void _ShowSlidervalue(void)
{
	GUI_SetColor(GUI_BLACK); //设置颜色
	GUI_SetTextMode(GUI_TM_TRANS); //设置透明模式
	GUI_SetFont(GUI_FONT_13B_1); //设置字体
	
	

	

//	GUI_GotoXY(10, Text_y);  //设置1位置
//	GUI_DispDecMin(-value[0]); //显示值
//	GUI_GotoXY(60, Text_y);  //设置2位置
//	GUI_DispDecMin(-value[1]); //显示值
//	GUI_GotoXY(110, Text_y);  //设置3位置
//	GUI_DispDecMin(-value[2]); //显示值
//	GUI_GotoXY(160, Text_y);  //设置4位置
//	GUI_DispDecMin(-value[3]); //显示值
//	GUI_GotoXY(210, Text_y);  //设置5位置
//	GUI_DispDecMin(-value[4]); //显示值
//	GUI_GotoXY(260, Text_y);  //设置6位置
//	GUI_DispDecMin(-value[5]); //显示值
//	GUI_GotoXY(310, Text_y);  //设置7位置
//	GUI_DispDecMin(-value[6]); //显示值
//	GUI_GotoXY(360, Text_y);  //设置8位置
//	GUI_DispDecMin(-value[7]); //显示值
	
	//新的
	GUI_GotoXY(siler_x, Text_y);  //设置1位置
	GUI_DispFloatMin(-(In_first->data.IN_DATA_1*step_slider),2); //显示值
	
	GUI_GotoXY(siler_x+50, Text_y);  //设置2位置
	GUI_DispFloatMin(-(In_first->data.IN_DATA_2*step_slider),2); //显示值
	
	GUI_GotoXY(siler_x+100, Text_y);  //设置3位置
	GUI_DispFloatMin(-(In_first->data.IN_DATA_3*step_slider),2); //显示值
	
	GUI_GotoXY(siler_x+150, Text_y);  //设置4位置
	GUI_DispFloatMin(-(In_first->data.IN_DATA_4*step_slider),2); //显示值
	
	GUI_GotoXY(siler_x+200, Text_y);  //设置5位置
	GUI_DispFloatMin(-(In_first->data.IN_DATA_5*step_slider),2); //显示值
	
	GUI_GotoXY(siler_x+250, Text_y);  //设置6位置
	GUI_DispFloatMin(-(In_first->data.IN_DATA_6*step_slider),2); //显示值
	
	GUI_GotoXY(siler_x+300, Text_y);  //设置7位置
	GUI_DispFloatMin(-(In_first->data.IN_DATA_7*step_slider),2); //显示值
	
	GUI_GotoXY(siler_x+350, Text_y);  //设置8位置
	GUI_DispFloatMin(-(In_first->data.IN_DATA_8*step_slider),2); //显示值
	
	//AT24C16_PageWrite((u8 *)In_first,IIC_Addr[0],sizeof(Input_First_data));  //保存数据

}


// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	int     NCode;
	int     Id;
	// USER START (Optionally insert additional variables)
	// USER END

	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetText(hItem, "IN_1");
		BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
		//BUTTON_SetSkin(hItem, _DrawSkin_Button);
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetText(hItem, "IN_2");
		BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		BUTTON_SetText(hItem, "IN_3");
		BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		BUTTON_SetText(hItem, "IN_4");
		BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		BUTTON_SetText(hItem, "IN_5");
		BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		BUTTON_SetText(hItem, "IN_6");
		BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		BUTTON_SetText(hItem, "COA_L");
		BUTTON_SetFont(hItem, GUI_FONT_13B_1);
		//
		// Initialization of 'Button'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
		BUTTON_SetText(hItem, "COA_R");
		BUTTON_SetFont(hItem, GUI_FONT_13B_1);
		// USER START (Optionally insert additional code for further widget initialization)
		// USER END

		//滑块
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
		SLIDER_SetRange(hItem, 0, slider_max);  //要取绝对值
		SLIDER_SetValue(hItem, In_first->data.IN_DATA_1);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
		SLIDER_SetRange(hItem, 0, slider_max);  //要取绝对值
		SLIDER_SetValue(hItem, In_first->data.IN_DATA_2);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_2);
		SLIDER_SetRange(hItem, 0, slider_max);  //要取绝对值
		SLIDER_SetValue(hItem, In_first->data.IN_DATA_3);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_3);
		SLIDER_SetRange(hItem, 0, slider_max);  //要取绝对值
		SLIDER_SetValue(hItem, In_first->data.IN_DATA_4);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_4);
		SLIDER_SetRange(hItem, 0, slider_max);  //要取绝对值
		SLIDER_SetValue(hItem, In_first->data.IN_DATA_5);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_5);
		SLIDER_SetRange(hItem, 0, slider_max);  //要取绝对值
		SLIDER_SetValue(hItem, In_first->data.IN_DATA_6);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_6);
		SLIDER_SetRange(hItem, 0, slider_max);  //要取绝对值
		SLIDER_SetValue(hItem, In_first->data.IN_DATA_7);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_7);
		SLIDER_SetRange(hItem, 0, slider_max);  //要取绝对值
		SLIDER_SetValue(hItem, In_first->data.IN_DATA_8);
		//字符串
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_TOP);
		TEXT_SetText(hItem, "GAIN");
		TEXT_SetFont(hItem, GUI_FONT_20B_1);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem, "/dB");
		TEXT_SetFont(hItem, GUI_FONT_20_1);
		
		//返回之前的聚焦
		switch(INPUT_CHANNEL)
		{
			case 0:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
				In_first->Item = button_0;
				break;
			
			case 1:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
				In_first->Item = button_1;
				break;
			
			case 2:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
				In_first->Item = button_2;
				break;
			
			case 3:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
				In_first->Item = button_3;
				break;
			
			case 4:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
				In_first->Item = button_4;
				break;
			
			case 5:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
				In_first->Item = button_5;
				break;
			
			case 6:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
				In_first->Item = button_6;
				break;
			
			case 7:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
				In_first->Item = button_7;
				break;
			
		}
		WM_SetFocus(hItem); //聚焦
		break;
	
	/********************************************控件处理****************************************/
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) {
		//点击主标题  退出
		case ID_TEXT_0:
			switch(NCode)
			{
				case WM_NOTIFICATION_RELEASED:
						GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
						hWin_now = CreateMainface();  //显示主页面
						break;
			}
			break;	
		
		case ID_SLIDER_0: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				In_first->Item = slider_0;
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0); //获得滑块句柄
				In_first->data.IN_DATA_1 = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[0]); //无效化该值重新刷新显示值
				gain_control(IN1_GAIN_ADDR,-(In_first->data.IN_DATA_1*step_slider));
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_1: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				 In_first->Item = slider_1;
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1); //获得滑块句柄
				In_first->data.IN_DATA_2 = SLIDER_GetValue(hItem); //保存滑块值	
				WM_InvalidateRect(pMsg->hWin, &Rect[1]); //无效化该值重新刷新显示值
				gain_control(IN6_GAIN_ADDR,-(In_first->data.IN_DATA_2*step_slider));
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_2: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				In_first->Item = slider_2;
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_2); //获得滑块句柄
				In_first->data.IN_DATA_3 = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[2]); //无效化该值重新刷新显示值
				gain_control(IN3_GAIN_ADDR,-(In_first->data.IN_DATA_3*step_slider));
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_3: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				In_first->Item = slider_3;
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_3); //获得滑块句柄
				In_first->data.IN_DATA_4 = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[3]); //无效化该值重新刷新显示值
				gain_control(IN4_GAIN_ADDR,-(In_first->data.IN_DATA_4*step_slider));
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_4: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

			In_first->Item = slider_4;
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_4); //获得滑块句柄
				In_first->data.IN_DATA_5 = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[4]); //无效化该值重新刷新显示值
				gain_control(IN5_GAIN_ADDR,-(In_first->data.IN_DATA_5*step_slider));
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_5: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

			In_first->Item = slider_5;
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_5); //获得滑块句柄
				In_first->data.IN_DATA_6 = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[5]); //无效化该值重新刷新显示值
				gain_control(IN2_GAIN_ADDR,-(In_first->data.IN_DATA_6*step_slider));
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_6: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

			In_first->Item = slider_6;
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_6); //获得滑块句柄
				In_first->data.IN_DATA_7 = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[6]); //无效化该值重新刷新显示值
				gain_control(COAX_L_GAIN_ADDR,-(In_first->data.IN_DATA_7*step_slider));
			
				//COAR同路
				//SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_7), value[6]);
				//WM_InvalidateRect(pMsg->hWin, &Rect[7]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_SLIDER_7: // Notifications sent by 'Slider'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

			In_first->Item = slider_7;
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_7); //获得滑块句柄
				In_first->data.IN_DATA_8 = SLIDER_GetValue(hItem); //保存滑块值
				WM_InvalidateRect(pMsg->hWin, &Rect[7]); //无效化该值重新刷新显示值
				gain_control(COAX_R_GAIN_ADDR,-(In_first->data.IN_DATA_8*step_slider));
			
			
				//SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_6), value[7]);
				//WM_InvalidateRect(pMsg->hWin, &Rect[6]); //无效化该值重新刷新显示值
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_0: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				INPUT_CHANNEL = 0;              //选中1通道
				GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
                hWin_now = Input_Second();      //显示第三页面
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_1: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				INPUT_CHANNEL = 1;              //选中2通道
				GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
                hWin_now = Input_Second(); //显示第三页面
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_2: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				INPUT_CHANNEL = 2;              //选中3通道
				GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
                hWin_now = Input_Second(); 		//显示第三页面
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_3: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				INPUT_CHANNEL = 3;              //选中4通道
				GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
                hWin_now = Input_Second(); //显示第三页面
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_4: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				INPUT_CHANNEL = 4;              //选中5通道
				GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
                hWin_now = Input_Second(); //显示第三页面
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_5: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				INPUT_CHANNEL = 5;              //选中6通道
				GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
                hWin_now = Input_Second(); //显示第三页面
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_6: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:

				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				INPUT_CHANNEL = 6;              //选中7通道
				GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
                hWin_now = Input_Second(); //显示第三页面
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
		case ID_BUTTON_7: // Notifications sent by 'Button'
			switch (NCode) {
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				INPUT_CHANNEL = 7;              //选中8通道
				GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
                hWin_now = Input_Second(); //显示第三页面
				// USER END
				break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
			}
			break;
			// USER START (Optionally insert additional code for further Ids)
			// USER END
		}
		break;
		// USER START (Optionally insert additional message handling)
		// USER END
	case WM_PAINT:
		GUI_SetBkColor(GUI_LIGHTBLUE);
		GUI_Clear();

		GUI_SetColor(GUI_BLACK);
		GUI_DrawHLine(17, 0, 400);
		GUI_DrawHLine(38, 0, 400);

		GUI_SetColor(GUI_BLACK);
		GUI_DrawVLine(47, 18, 240);
		GUI_DrawVLine(97, 18, 240);
		GUI_DrawVLine(147, 18, 240);
		GUI_DrawVLine(197, 18, 240);
		GUI_DrawVLine(247, 18, 240);
		GUI_DrawVLine(297, 18, 240);
		GUI_DrawVLine(347, 18, 240);

		GUI_SetColor(GUI_WHITE);
		GUI_FillRoundedRect(0, Text_y, 46, Text_y+17, 2);
		GUI_FillRoundedRect(0 + 48, Text_y,  46 + 50, Text_y + 17, 2);
		GUI_FillRoundedRect(0 + 98, Text_y, 46 + 100, Text_y + 17, 2);
		GUI_FillRoundedRect(0 + 148, Text_y, 46 + 150, Text_y + 17, 2);
		GUI_FillRoundedRect(0 + 198, Text_y, 46 + 200, Text_y + 17, 2);
		GUI_FillRoundedRect(0 + 248, Text_y, 46 + 250, Text_y + 17, 2);
		GUI_FillRoundedRect(0 + 298, Text_y, 46 + 300, Text_y + 17, 2);
		GUI_FillRoundedRect(0 + 348, Text_y, 46 + 354, Text_y + 17, 2);
		
		
		_ShowSlidervalue(); //显示滑动值
		break;
		

	
	/*********************************************自定义信息处理**************************************************/
	//旋钮左转
	case MSG_KNOB_CONTROL_LEFT:
		Item_change(&(In_first->Item),slider_0,button_7,Next_dir); //项目指示改变
		GUI_SendKeyMsg(GUI_KEY_TAB, 1);     //下一个聚焦点
		break;
	
	//旋钮右转
	case MSG_KNOB_CONTROL_RIGHT:
		Item_change(&(In_first->Item),slider_0,button_7,Last_dir);
		GUI_SendKeyMsg(GUI_KEY_BACKTAB, 1); //上一个聚焦
		break;
	
	//CONTROL按下
	case MSG_KEY_CONTROL:
		GUI_SendKeyMsg(GUI_KEY_ENTER, 1);   //确定
		break;
	
	//ESC
	case MSG_KEY_ESC:
		GUI_SendKeyMsg(GUI_KEY_ESCAPE, 1);  //退出
		break;
	
	//INPUT左转
	case MSG_KNOB_INPUT_LEFT:
//		GUI_SendKeyMsg(GUI_KEY_LEFT,1); //滑块数值减少
		if(In_first->dir == 2)
		{
			In_first->Key_count = 0;
		}
		In_first->dir = 1;
		switch(In_first->Item)
		{
			//滑块1
			case slider_0:
				Value_Change_dec(&(In_first->data.IN_DATA_1),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_1),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0), In_first->data.IN_DATA_1);
				break;
			
			//滑块2
			case slider_1:
				Value_Change_dec(&(In_first->data.IN_DATA_2),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_2),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1), In_first->data.IN_DATA_2);
				break;
			
			//滑块3
			case slider_2:
				Value_Change_dec(&(In_first->data.IN_DATA_3),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_3),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_2), In_first->data.IN_DATA_3);
				break;
			
			//滑块4
			case slider_3:
				Value_Change_dec(&(In_first->data.IN_DATA_4),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_4),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_3), In_first->data.IN_DATA_4);
				break;
			
			//滑块5
			case slider_4:
				Value_Change_dec(&(In_first->data.IN_DATA_5),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_5),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_4), In_first->data.IN_DATA_5);
				break;
			
			//滑块6
			case slider_5:
				Value_Change_dec(&(In_first->data.IN_DATA_6),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_6),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_5), In_first->data.IN_DATA_6);
				break;
			
			//滑块7
			case slider_6:
				Value_Change_dec(&(In_first->data.IN_DATA_7),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_7),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_6), In_first->data.IN_DATA_7);
				break;
			
			//滑块8
			case slider_7:
				Value_Change_dec(&(In_first->data.IN_DATA_8),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_8),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_7), In_first->data.IN_DATA_8);
				break;
		}
		break;
	
	//INPUT右转
	case MSG_KNOB_INPUT_RIGHT:
//		GUI_SendKeyMsg(GUI_KEY_RIGHT,1); //滑块数值增加
		if(In_first->dir == 1)
		{
			In_first->Key_count = 0;  //上一次为减少数值
		}
		In_first->dir = 2;
		switch(In_first->Item)
		{
			//滑块1
			case slider_0:
				Value_Change_add(&(In_first->data.IN_DATA_1),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_1),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0), In_first->data.IN_DATA_1);
				break;
			
			//滑块2
			case slider_1:
				Value_Change_add(&(In_first->data.IN_DATA_2),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_2),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1), In_first->data.IN_DATA_2);
				break;
			
			//滑块3
			case slider_2:
				Value_Change_add(&(In_first->data.IN_DATA_3),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_3),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_2), In_first->data.IN_DATA_3);
				break;
			
			//滑块4
			case slider_3:
				Value_Change_add(&(In_first->data.IN_DATA_4),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_4),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_3), In_first->data.IN_DATA_4);
				break;
			
			//滑块5
			case slider_4:
				Value_Change_add(&(In_first->data.IN_DATA_5),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_5),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_4), In_first->data.IN_DATA_5);
				break;
			
			//滑块6
			case slider_5:
				Value_Change_add(&(In_first->data.IN_DATA_6),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_6),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_5), In_first->data.IN_DATA_6);
				break;
			
			//滑块7
			case slider_6:
				Value_Change_add(&(In_first->data.IN_DATA_7),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_7),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_6), In_first->data.IN_DATA_7);
				break;
			
			//滑块8
			case slider_7:
				Value_Change_add(&(In_first->data.IN_DATA_8),&(In_first->Key_count));
				Max_Min(&(In_first->data.IN_DATA_8),slider_max,0);
				SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_7), In_first->data.IN_DATA_8);
				break; 
		}
		break;
	
	//INPUT
	case MSG_KEY_INPUT:
//        GUI_EndDialog(pMsg->hWin, 0); //结束本界面
//		hWin_now = Input_Second(); //显示INPUT第二个界面
		break;
	
	//没有旋钮动作
	case MSG_KNOB_NULL:
		In_first->Key_count = 0;
		In_first->dir		= 0; //无动作
		break;
	/*********************************按键处理******************************************/
	case WM_KEY:
		switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) //获得关于按键信息的值
		{
			//ESC
			case GUI_KEY_ESCAPE:
            GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
            hWin_now = CreateMainface();  //显示主页面
			INPUT_CHANNEL = 0;
            break;
		}
		break;
		
		
	case WM_DELETE:
	//后续需要添加保存数据到IC240C中的代码
//		myfree(0,In_first); //释放动态内存
		break;
		
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
//初始化数据
static void Init_data(Input_First_data *L)
{
//	AT24C16_PageRead((u8 *)L,IIC_Addr[0],sizeof(Input_First_data));  //提取数据
//	L->IN_DATA_1 = 80;
//	L->IN_DATA_2 = 80;
//	L->IN_DATA_3 = 80;
//	L->IN_DATA_4 = 80;
//	L->IN_DATA_5 = 80;
//	L->IN_DATA_6 = 80;
//	L->IN_DATA_7 = 80;
//	L->IN_DATA_8 = 80;

}

WM_HWIN Input_First(void) {
	WM_HWIN hWin;
	
	//申请动态数据
//	In_first = (Input_First_data *)mymalloc(0,sizeof(Input_First_data));
//	if(In_first == NULL) //如果申请不成功，会错误
//		return 0;
//	else 
//	{
//		EEPROM_FREE = 1;
//		Init_data(In_first);   //申请成功就初始化数据
//	}
	
	Init_data(In_first);   //申请成功就初始化数据
	Button_flex_2();
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
