/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

//LOW PASS 

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "BUTTON_Private.h"
#include "data.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_BUTTON_0 (GUI_ID_USER + 0x05)
#define ID_BUTTON_1 (GUI_ID_USER + 0x06)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x07)
#define ID_CHECKBOX_1 (GUI_ID_USER + 0x08)
#define ID_BUTTON_2 (GUI_ID_USER + 0x09)

//增减按钮
#define ID_BUTTON_3 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_4 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_5 (GUI_ID_USER + 0x0C)
#define ID_BUTTON_6 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_7 (GUI_ID_USER + 0x0E)
#define ID_BUTTON_8 (GUI_ID_USER + 0x0F)

#define ID_BUTTON_9 (GUI_ID_USER + 0x10)
#define ID_BUTTON_10 (GUI_ID_USER + 0x11)
#define ID_BUTTON_11 (GUI_ID_USER + 0x12)

#define ID_BUTTON_12 (GUI_ID_USER + 0x13)
#define ID_BUTTON_13 (GUI_ID_USER + 0x14)
#define ID_BUTTON_14 (GUI_ID_USER + 0x15)
#define ID_BUTTON_15 (GUI_ID_USER + 0x16)
#define ID_BUTTON_16 (GUI_ID_USER + 0x17)
#define ID_BUTTON_17 (GUI_ID_USER + 0x18)
#define ID_CHECKBOX_2 (GUI_ID_USER + 0x19)
#define ID_CHECKBOX_3 (GUI_ID_USER + 0x1A)
#define ID_BUTTON_18 (GUI_ID_USER + 0x1B)
#define ID_BUTTON_19 (GUI_ID_USER + 0x1C)

#define dec_size  40
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
//static Output_Third_Data *Out_Third;

static Input_Five_data* Current_input;
static const GUI_POINT pPoint_left[] = {
	{ 0, 10 },
	{ 10, 0 },
	{ 10, 20 },
};

static const GUI_POINT pPoint_right[] = {
	{ 10+20, 0 },
	{ 20+20, 10 },
	{ 10+20, 20 },
};

//页面显示的字符串数据
static char face_string[][20] = 
{
//	"NULL",
	"INPUT1 PAGE 4/4",
	"INPUT2 PAGE 4/4",
	"INPUT3 PAGE 4/4",
	"INPUT4 PAGE 4/4",
	"INPUT5 PAGE 4/4",
	"INPUT6 PAGE 4/4",
	"COAL PAGE 4/4",
	"COAR PAGE 4/4",

};

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 400, 240, 0, 0x0, 0 },

	//INPUT 2/3
	{ TEXT_CreateIndirect, "Text", ID_TEXT_0, 109, 3, 194, 28, 0, 0, 0 },
	//INPUT_EQ SETTINGD
	{ TEXT_CreateIndirect, "Text", ID_TEXT_1, 59, 36, 294, 28, 0, 0, 0 },
	//LOW PASS
	{ TEXT_CreateIndirect, "Text", ID_TEXT_2, 0, 70, 194, 28, 0, 0, 0 },
	//HIGH PASS
	{ TEXT_CreateIndirect, "Text", ID_TEXT_3, 204, 70, 194, 28, 0, 0, 0 },

	//LOW PASS
	/*创建按钮*/
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 0, 102, 98, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 0, 136, 98, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 0, 170, 98, 32, 0, 0x0, 0 },


	/*创建复选框*/
	//LOW PASS
//	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 5, 208, 90, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_1, 107, 208, 90, 23, 0, 0x0, 0 },



	/*按钮*/
	//LOW PASS
	//left
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 104, 102 + 4, dec_size, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 104, 136 + 4, dec_size, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 104, 170 + 4, dec_size, 25, 0, 0x0, 0 },

	//right
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_6, 175-20, 102 + 4, dec_size, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_7, 175-20, 136 + 4, dec_size, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_8, 175-20, 170 + 4, dec_size, 25, 0, 0x0, 0 },

	//HIGH PASS
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_9, 202, 102, 98, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_10, 202, 136, 98, 32, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_11, 202, 170, 98, 32, 0, 0x0, 0 },

	//left
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_12, 104 + 202, 107, dec_size, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_13, 104 + 202, 141, dec_size, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_14, 104 + 202, 174, dec_size, 25, 0, 0x0, 0 },

	//right
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_15, 175 + 180, 107, dec_size, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_16, 175 + 180, 141, dec_size, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_17, 175 + 180, 174, dec_size, 25, 0, 0x0, 0 },

	//HIGH PASS
//	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_2, 5 + 203, 208, 90, 23, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_3, 107 + 203, 208, 90, 23, 0, 0x0, 0 },

	/*页面切换*/
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_18, 5, 5, dec_size, 25, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_19, 375-20, 5, dec_size, 25, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
//左边三角形
static void _cbButton_left(WM_MESSAGE * pMsg) //--------------（3）
{
	WM_HWIN hWin;
	hWin = pMsg->hWin;
	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		if (BUTTON_IsPressed(hWin))
		{
			//画红色三角形
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_left, 3, 0, 0);
		}
		else
		{
			//画黑色三角形
			GUI_SetColor(GUI_BLACK);
			GUI_FillPolygon(pPoint_left, 3, 0, 0);
		}

		break;

		//处理默认信息
	default:
		BUTTON_Callback(pMsg);
	}
}

//右边三角形
#define BUTTON_H2P(h) (BUTTON_Obj*) GUI_ALLOC_h2p(h)

static void _cbButton_right(WM_MESSAGE * pMsg) //--------------（3）
{
	WM_HWIN hWin;
	BUTTON_Obj * pObj; //用来提取出按钮的指针结构体，包含了各种信息

//	const GUI_PID_STATE* pState = (const GUI_PID_STATE*)pMsg->Data.p;
	hWin = pMsg->hWin;
	pObj = BUTTON_H2P(hWin);

	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		if (BUTTON_IsPressed(hWin))
		{
			//画红色三角形
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}
		else
		{
			//画黑色三角形
			GUI_SetColor(GUI_BLACK);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}

		//绘制聚焦,如果不接受聚焦则此项不起作用
		if (pObj->Widget.State & WIDGET_STATE_FOCUS)
		{
			GUI_SetColor(GUI_RED);
			GUI_FillPolygon(pPoint_right, 3, 0, 0);
		}
		break;


		//case WM_TOUCH:
		//	if (pMsg->Data.p) {  /* Something happened in our area (pressed or released) */
		//		if (pState->Pressed) {
		//			RMSTC_Value++;
		//			WIDGET_OrState(hWin, BUTTON_STATE_PRESSED);
		//			WM_NotifyParent(hWin, WM_NOTIFICATION_CLICKED);
		//		}
		//		else {
		//			/* React only if button was pressed before ... avoid problems with moving / hiding windows above (such as dropdown) */
		//
		//		}
		//	}
		//	else {
		//
		//	}
		//	break;
		//处理默认信息
	default:
		BUTTON_Callback(pMsg);
	}
}


/*
*******************************************************************************************
* 函 数 名: 进行数据传输
* 功能说明: 对此界面中的一些数据传输给DSP
* 形 参: 无
* 返 回 值: 无
*******************************************************************************************
*/
static void tranrfer_data(signed char param)
{
	if(Current_input->overflow != 0)
	{
		Current_input->overflow = 0;
		param = -1;
	}
	
	switch(param)
	{
		//低通
		case TYPE_LOW_Item_Out:
		case FREQ_LOW_Item_Out:
		case GAIN_LOW_Item_Out:
		case INVERT_LOW_Item_Out:
			if(Current_input->data.TYPE_DATA_HIGH == 0)
			{
				Data_output_pass(OUTPUT_CHANNEL,Current_input->data.FREQ_DATA_LOW,
				Current_input->data.GAIN_DATA_LOW,BESSEL_12_TYPE,0,Current_input->data.INVERT_LOW_STA,input_flag);
			}
			else if(Current_input->data.TYPE_DATA_HIGH == 1)
			{
				Data_output_pass(OUTPUT_CHANNEL,Current_input->data.FREQ_DATA_LOW,
				Current_input->data.GAIN_DATA_LOW,BUTTER_12_TYPE,0,Current_input->data.INVERT_LOW_STA,input_flag);
			}
			else if(Current_input->data.TYPE_DATA_LOW == 2)
			{
				Data_output_pass(OUTPUT_CHANNEL,Current_input->data.FREQ_DATA_LOW,
				Current_input->data.GAIN_DATA_LOW,BESSEL_24_TYPE,0,Current_input->data.INVERT_LOW_STA,input_flag);
			}
			else if(Current_input->data.TYPE_DATA_LOW == 3)
			{
				Data_output_pass(OUTPUT_CHANNEL,Current_input->data.FREQ_DATA_LOW,
				Current_input->data.GAIN_DATA_LOW,BUTTER_24_TYPE,0,Current_input->data.INVERT_LOW_STA,input_flag);
			}
			break;
			
		//高通
		case TYPE_HIGH_Item_Out:
		case FREQ_HIGH_Item_Out:
		case GAIN_HIGH_Item_Out:
		case INVERT_HIGH_Item_Out:
			if(Current_input->data.TYPE_DATA_HIGH == 0)
			{
				Data_output_pass(OUTPUT_CHANNEL,Current_input->data.FREQ_DATA_HIGH,
				Current_input->data.GAIN_DATA_HIGH,BESSEL_12_TYPE,1,Current_input->data.INVERT_HIGH_STA,input_flag);
			}
			else if(Current_input->data.TYPE_DATA_HIGH == 1)
			{
				Data_output_pass(OUTPUT_CHANNEL,Current_input->data.FREQ_DATA_HIGH,
				Current_input->data.GAIN_DATA_HIGH,BUTTER_12_TYPE,1,Current_input->data.INVERT_HIGH_STA,input_flag);
			}
			else if(Current_input->data.TYPE_DATA_HIGH == 2)
			{
				Data_output_pass(OUTPUT_CHANNEL,Current_input->data.FREQ_DATA_HIGH,
				Current_input->data.GAIN_DATA_HIGH,BESSEL_24_TYPE,1,Current_input->data.INVERT_HIGH_STA,input_flag);
			}
			else if(Current_input->data.TYPE_DATA_HIGH == 3)
			{
				Data_output_pass(OUTPUT_CHANNEL,Current_input->data.FREQ_DATA_HIGH,
				Current_input->data.GAIN_DATA_HIGH,BUTTER_24_TYPE,1,Current_input->data.INVERT_HIGH_STA,input_flag);
			}
			break;
			
		//复选框
	}
	
	Current_input->change_item = -1;
}
/******************************Show_Value 所需数据*****************************/
#include "stdio.h"
#include "string.h"

#define TYPE_LOW_X  150
#define TYPE_LOW_Y  107
#define FREQ_LOW_Y	TYPE_LOW_Y+34
#define GAIN_LOW_Y	FREQ_LOW_Y+34

//最大值和最小值
#define 	TYPE_MAX	3
#define		TYPE_MIN	0
#define		FREQ_MAX	20000
#define		FREQ_MIN	0
#define		GAIN_MAX	0
#define		GAIN_MIN	0


//定义无效区域
static const GUI_RECT InvaliRect_Value[][4] = {
	//LOW
	{ TYPE_LOW_X-50, TYPE_LOW_Y, TYPE_LOW_X+50, TYPE_LOW_Y+20}, 
	{ TYPE_LOW_X-50, FREQ_LOW_Y, TYPE_LOW_X+50, FREQ_LOW_Y+20},
	{ TYPE_LOW_X-50, GAIN_LOW_Y, TYPE_LOW_X+50, GAIN_LOW_Y+20},
//	{0},
	{0},
	//HIGH
	{ TYPE_LOW_X+150, TYPE_LOW_Y, TYPE_LOW_X+250, TYPE_LOW_Y+20}, 
	{ TYPE_LOW_X+150, FREQ_LOW_Y, TYPE_LOW_X+250, FREQ_LOW_Y+20},
	{ TYPE_LOW_X+150, GAIN_LOW_Y, TYPE_LOW_X+250, GAIN_LOW_Y+20},

};
/*
*******************************************************************************************
* 函 数 名: Show_Value
* 功能说明: 显示数值
* 形 参: 无
* 返 回 值: 无
*******************************************************************************************
*/
static void Show_Value(void)
{
	char str[10];
	char over;
	
	
	GUI_SetColor(GUI_WHITE);
	GUI_SetTextMode(GUI_TM_TRANS);
	GUI_SetFont(GUI_FONT_24_1);
	//显示字符
	GUI_DispStringHCenterAt("ENABLE",50,208);
	GUI_DispStringHCenterAt("ENABLE",250,208);
	
	GUI_SetColor(GUI_BLACK);
	GUI_SetTextMode(GUI_TM_TRANS);
	GUI_SetFont(&GUI_Font16B_1);
	
	//TYPE_LOW
	over = Max_Min(&Current_input->data.TYPE_DATA_LOW,TYPE_MAX,TYPE_MIN);
	Current_input->overflow |= (over<<TYPE_LOW_Item_Out);
	if(Current_input->data.TYPE_DATA_LOW == 0)
	{
		strcpy(str,"Besselx12");
	}
	else if(Current_input->data.TYPE_DATA_LOW == 1)
	{
		strcpy(str,"Butterx12");
	}
	else if(Current_input->data.TYPE_DATA_LOW == 2)
	{
		strcpy(str,"Besselx24");
	}
	else if(Current_input->data.TYPE_DATA_LOW == 3)
	{
		strcpy(str,"Butterx24");
	}
//	snprintf(str,sizeof(str) - 1,"%d",Current_input->data.TYPE_DATA_LOW);  //把数值转为字符串
	GUI_DispStringHCenterAt(str,TYPE_LOW_X,TYPE_LOW_Y);          //以当前坐标为中心显示字符串
	
	
	//TYPE_HIGH
//	snprintf(str,sizeof(str) - 1,"%d",Current_input->data.TYPE_DATA_HIGH);  //把数值转为字符串
	over = Max_Min(&Current_input->data.TYPE_DATA_HIGH,TYPE_MAX,TYPE_MIN);
	Current_input->overflow |= (over<<TYPE_HIGH_Item_Out);
	if(Current_input->data.TYPE_DATA_HIGH == 0)
	{
		strcpy(str,"Besselx12");
	}
	else if(Current_input->data.TYPE_DATA_HIGH == 1)
	{
		strcpy(str,"Butterx12");
	}
	else if(Current_input->data.TYPE_DATA_HIGH == 2)
	{
		strcpy(str,"Besselx24");
	}
	else if(Current_input->data.TYPE_DATA_HIGH == 3)
	{
		strcpy(str,"Butterx24");
	}
	GUI_DispStringHCenterAt(str,TYPE_LOW_X+200,TYPE_LOW_Y);          //以当前坐标为中心显示字符串
	
	//FREQ_LOW
	GUI_SetFont(&GUI_Font20_1);
	over = Max_Min(&Current_input->data.FREQ_DATA_LOW,FREQ_MAX,FREQ_MIN);
	Current_input->overflow |= (over << FREQ_LOW_Item_Out);
	snprintf(str,sizeof(str) - 1,"%d",Current_input->data.FREQ_DATA_LOW);  //把数值转为字符串
	GUI_DispStringHCenterAt(str,TYPE_LOW_X,FREQ_LOW_Y);          //以当前坐标为中心显示字符串
	
	//GAIN_LOW
	over = Max_Min(&Current_input->data.GAIN_DATA_LOW,GAIN_MAX,GAIN_MIN);
	Current_input->overflow |= (over << GAIN_LOW_Item_Out);
	snprintf(str,sizeof(str) - 1,"%d",Current_input->data.GAIN_DATA_LOW);  //把数值转为字符串
	GUI_DispStringHCenterAt(str,TYPE_LOW_X,GAIN_LOW_Y);          //以当前坐标为中心显示字符串
	


	//FREQ_HIGH
	over = Max_Min(&Current_input->data.FREQ_DATA_HIGH,FREQ_MAX,FREQ_MIN);
	Current_input->overflow |= (over << FREQ_HIGH_Item_Out);
	snprintf(str,sizeof(str) - 1,"%d",Current_input->data.FREQ_DATA_HIGH);  //把数值转为字符串
	GUI_DispStringHCenterAt(str,TYPE_LOW_X+200,FREQ_LOW_Y);          //以当前坐标为中心显示字符串
	
	//GAIN_HIGH
	over = Max_Min(&Current_input->data.GAIN_DATA_HIGH,GAIN_MAX,GAIN_MIN);
	Current_input->overflow |= (over << GAIN_HIGH_Item_Out);
	snprintf(str,sizeof(str) - 1,"%d",Current_input->data.GAIN_DATA_HIGH);  //把数值转为字符串
	GUI_DispStringHCenterAt(str,TYPE_LOW_X+200,GAIN_LOW_Y);          //以当前坐标为中心显示字符串
	
	//AT24C16_PageWrite((u8 *)(&(Current_input->data)),IIC_Addr[Current_input->face_switch+30],sizeof(Current_input->data));
	//判断更改项
	tranrfer_data(Current_input->change_item);
}
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
	// USER START (Optionally insert additional variables)
	// USER END
	WM_HWIN hItem;
	int		NCode;
	int		Id;

	switch (pMsg->MsgId) {
		// USER START (Optionally insert additional message handling)
		// USER END
	case WM_INIT_DIALOG:
		//TEXT设置
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetText(hItem, Current_input->String);
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		//INPUT_EQ
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetText(hItem, "INPUT FILTER");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		//LOW PASS
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetText(hItem, "LOW PASS");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		//HIGH PASS
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
		TEXT_SetText(hItem, "HIGH PASS");
		TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));

		//按钮设置
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "TYPE");          //设置显示的字符串

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "FREQ(Hz)");          //设置显示的字符串

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "GAIN(dB)");          //设置显示的字符串

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "TYPE");          //设置显示的字符串

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "FREQ(Hz)");          //设置显示的字符串

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11);
		BUTTON_SetFont(hItem, GUI_FONT_16B_1);  //设置字体
		BUTTON_SetText(hItem, "GAIN(dB)");          //设置显示的字符串

		//复选框
		//LOW PASS
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
		CHECKBOX_SetText(hItem, "LOW_HIGH");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_13H_1);
		CHECKBOX_SetState(hItem,Current_input->data.LOW_HIGH_STA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
		CHECKBOX_SetText(hItem, "BYPASS");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_13HB_1);
		CHECKBOX_SetState(hItem,Current_input->data.INVERT_LOW_STA);

		//HIGH PASS
		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2);
		CHECKBOX_SetText(hItem, "MID_HIGH");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_13H_1);
		CHECKBOX_SetState(hItem,Current_input->data.MID_HIGH_STA);

		hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3);
		CHECKBOX_SetText(hItem, "BYPASS");
		CHECKBOX_SetTextColor(hItem, GUI_WHITE);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetFont(hItem, GUI_FONT_13HB_1);
		CHECKBOX_SetState(hItem,Current_input->data.INVERT_HIGH_STA);

		
		//LOW PASS
		//left
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		//right
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		//HIGH PASS
		//left
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_12);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_13);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_14);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		//right
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_15);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_16);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_17);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		/*页面切换*/
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_18);
		WM_SetCallback(hItem, _cbButton_left);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点

		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_19);
		WM_SetCallback(hItem, _cbButton_right);
		BUTTON_SetFocussable(hItem, 0); //不接受输入焦点
		break;
	
	/***************************************子窗口响应********************************************/
	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);  //获得是哪个子窗口发生变化
		NCode = pMsg->Data.v;          //子窗口发生什么变化
		switch(Id)
		{
			//点击主标题  退出
			case ID_TEXT_0:
				switch(NCode)
				{
					case WM_NOTIFICATION_RELEASED:
							GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
							hWin_now = Output_First();  //页面
							break;
				}
				break;
				
			case ID_BUTTON_0:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0)); //改变聚焦
						Current_input->Item = TYPE_LOW_Item_Out;  //子选项改变
						break;
				}
				break;
				
			case ID_BUTTON_1:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1)); //改变聚焦
						Current_input->Item = FREQ_LOW_Item_Out;  //子选项改变
						break;
				}
				break;
				
			case ID_BUTTON_2:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2)); //改变聚焦
						Current_input->Item = GAIN_LOW_Item_Out;  //子选项改变
						break;
				}
				break;
				
			case ID_BUTTON_9:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9)); //改变聚焦
						Current_input->Item = TYPE_HIGH_Item_Out;  //子选项改变
						break;
				}
				break;
				
			case ID_BUTTON_10:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10)); //改变聚焦
						Current_input->Item = FREQ_HIGH_Item_Out;  //子选项改变
						break;
				}
				break;
				
			case ID_BUTTON_11:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_11)); //改变聚焦
						Current_input->Item = GAIN_HIGH_Item_Out;  //子选项改变
						break;
				}
				break;
			
			//LOW_HIGH
//			case ID_CHECKBOX_0:	
//				switch(NCode)
//				{
//					//复选框已被点击
//						case WM_NOTIFICATION_CLICKED:
//							WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0)); //改变聚焦
//							Current_input->Item = LOW_HIGH_Item_Out;
//							break;

//						//复选框已被释放
//						case WM_NOTIFICATION_RELEASED:
//							break;

//						//复选框的状态已改变
//						case WM_NOTIFICATION_VALUE_CHANGED:
//							
//							if(Current_input->checkbox_sta &(0x01<<0))
//							{
//								Current_input->change_item = LOW_HIGH_Item_Out;
//								if(Current_input->data.LOW_HIGH_STA == 0)
//								{
//									Current_input->data.LOW_HIGH_STA = 1;
//								}
//								else
//								{
//									Current_input->data.LOW_HIGH_STA = 0;
//								}
//							}
//							else
//							{
//								Current_input->checkbox_sta |= (0x01<<0);
//							}
//							break;
//				}
//				break;
			
			//INVERT_LOW
			case ID_CHECKBOX_1:	
				switch(NCode)
				{
					//复选框已被点击
						case WM_NOTIFICATION_CLICKED:
							WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1)); //改变聚焦
							Current_input->Item = INVERT_LOW_Item_Out;
							break;

						//复选框已被释放
						case WM_NOTIFICATION_RELEASED:
							break;

						//复选框的状态已改变
						case WM_NOTIFICATION_VALUE_CHANGED:
							
							if(Current_input->checkbox_sta &(0x01<<1))
							{
								Current_input->change_item = INVERT_LOW_Item_Out;
								if(Current_input->data.INVERT_LOW_STA == 0)
								{
									Current_input->data.INVERT_LOW_STA = 1;
								}
								else
								{
									Current_input->data.INVERT_LOW_STA = 0;
								}
							}
							else
							{
								Current_input->checkbox_sta |= (0x01<<1);
							}
							break;
				}
				break;
			
			//MID_HIGH
//			case ID_CHECKBOX_2:	
//				switch(NCode)
//				{
//					//复选框已被点击
//						case WM_NOTIFICATION_CLICKED:
//							WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_2)); //改变聚焦
//							Current_input->Item = MID_HIGH_Item_Out;
//							break;

//						//复选框已被释放
//						case WM_NOTIFICATION_RELEASED:
//							break;

//						//复选框的状态已改变
//						case WM_NOTIFICATION_VALUE_CHANGED:
//							
//							if(Current_input->checkbox_sta &(0x01<<2))
//							{
//								Current_input->change_item = MID_HIGH_Item_Out;
//								if(Current_input->data.MID_HIGH_STA == 0)
//								{
//									Current_input->data.MID_HIGH_STA = 1;
//								}
//								else
//								{
//									Current_input->data.MID_HIGH_STA = 0;
//								}
//							}
//							else
//							{
//								Current_input->checkbox_sta |= (0x01<<2);
//							}
//							break;
//				}
//				break;
			
			//INVERT_HIGH
			case ID_CHECKBOX_3:	
				switch(NCode)
				{
					//复选框已被点击
						case WM_NOTIFICATION_CLICKED:
							WM_SetFocus(WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_3)); //改变聚焦
							Current_input->Item = INVERT_HIGH_Item_Out;
							break;

						//复选框已被释放
						case WM_NOTIFICATION_RELEASED:
							break;

						//复选框的状态已改变
						case WM_NOTIFICATION_VALUE_CHANGED:
							
							if(Current_input->checkbox_sta &(0x01<<3))
							{
								Current_input->change_item = INVERT_HIGH_Item_Out;
								if(Current_input->data.INVERT_HIGH_STA == 0)
								{
									Current_input->data.INVERT_HIGH_STA = 1;
								}
								else
								{
									Current_input->data.INVERT_HIGH_STA = 0;
								}
							}
							else
							{
								Current_input->checkbox_sta |= (0x01<<3);
							}
							break;
				}
				break;
			
			//页面切换
			case ID_BUTTON_18:
				switch (NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:

						break;

					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
						hWin_now = Input_Third();      //切换下一个界面
						break;
				}
				break;
			
			case ID_BUTTON_19:
				switch (NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:

						break;

					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
						hWin_now = Input_Second();      //切换下一个界面
						break;
				}
				break;
				
			//增减
			case ID_BUTTON_3:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Current_input->change_item = TYPE_LOW_Item_Out;
						Time_add_dec(&Current_input->data.TYPE_DATA_LOW,InvaliRect_Value[TYPE_LOW_Item_Out],&Current_input->hItime,First_Time_left,pMsg);
	
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Time_end(&Current_input->Time_count,Current_input->hItime);
					break;
				}
				break;
				
			case ID_BUTTON_4:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Current_input->change_item = FREQ_LOW_Item_Out;
						Time_add_dec(&Current_input->data.FREQ_DATA_LOW,InvaliRect_Value[FREQ_LOW_Item_Out],&Current_input->hItime,Second_Time_left,pMsg);
	
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Time_end(&Current_input->Time_count,Current_input->hItime);
					break;
				}
				break;
				
			case ID_BUTTON_5:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Current_input->change_item = GAIN_LOW_Item_Out;
						Time_add_dec(&Current_input->data.GAIN_DATA_LOW,InvaliRect_Value[GAIN_LOW_Item_Out],&Current_input->hItime,Third_Time_left,pMsg);
	
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Time_end(&Current_input->Time_count,Current_input->hItime);
					break;
				}
				break;
				
			case ID_BUTTON_6:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Current_input->change_item = TYPE_LOW_Item_Out;
						Time_add_dec(&Current_input->data.TYPE_DATA_LOW,InvaliRect_Value[TYPE_LOW_Item_Out],&Current_input->hItime,First_Time_right,pMsg);
	
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Time_end(&Current_input->Time_count,Current_input->hItime);
					break;
				}
				break;
				
			case ID_BUTTON_7:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Current_input->change_item = FREQ_LOW_Item_Out;
						Time_add_dec(&Current_input->data.FREQ_DATA_LOW,InvaliRect_Value[FREQ_LOW_Item_Out],&Current_input->hItime,Second_Time_right,pMsg);
	
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Time_end(&Current_input->Time_count,Current_input->hItime);
					break;
				}
				break;
				
			case ID_BUTTON_8:
				switch(NCode)
				{
					//已点击按钮
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Current_input->change_item = GAIN_LOW_Item_Out;
						Time_add_dec(&Current_input->data.GAIN_DATA_LOW,InvaliRect_Value[GAIN_LOW_Item_Out],&Current_input->hItime,Third_Time_right,pMsg);
	
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Time_end(&Current_input->Time_count,Current_input->hItime);
					break;
				}
				break;
				
			case ID_BUTTON_12:
				switch(NCode)
				{
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Current_input->change_item = TYPE_HIGH_Item_Out;
						Time_add_dec(&Current_input->data.TYPE_DATA_HIGH,InvaliRect_Value[TYPE_HIGH_Item_Out],&Current_input->hItime,Four_Time_left,pMsg);
	
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Time_end(&Current_input->Time_count,Current_input->hItime);
					break;
				}
				break;
				
			case ID_BUTTON_13:
				switch(NCode)
				{
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Current_input->change_item = FREQ_HIGH_Item_Out;
						Time_add_dec(&Current_input->data.FREQ_DATA_HIGH,InvaliRect_Value[FREQ_HIGH_Item_Out],&Current_input->hItime,Five_Time_left,pMsg);
	
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Time_end(&Current_input->Time_count,Current_input->hItime);
					break;
				}
				break;
				
			case ID_BUTTON_14:
				switch(NCode)
				{
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Current_input->change_item = GAIN_HIGH_Item_Out;
						Time_add_dec(&Current_input->data.GAIN_DATA_HIGH,InvaliRect_Value[GAIN_HIGH_Item_Out],&Current_input->hItime,Six_Time_left,pMsg);
	
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Time_end(&Current_input->Time_count,Current_input->hItime);
					break;
				}
				break;
				
			case ID_BUTTON_15:
				switch(NCode)
				{
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Current_input->change_item = TYPE_HIGH_Item_Out;
						Time_add_dec(&Current_input->data.TYPE_DATA_HIGH,InvaliRect_Value[TYPE_HIGH_Item_Out],&Current_input->hItime,Four_Time_right,pMsg);
	
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Time_end(&Current_input->Time_count,Current_input->hItime);
					break;
				}
				break;
				
			case ID_BUTTON_16:
				switch(NCode)
				{
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Current_input->change_item = FREQ_HIGH_Item_Out;
						Time_add_dec(&Current_input->data.FREQ_DATA_HIGH,InvaliRect_Value[FREQ_HIGH_Item_Out],&Current_input->hItime,Five_Time_right,pMsg);
	
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Time_end(&Current_input->Time_count,Current_input->hItime);
					break;
				}
				break;
				
			case ID_BUTTON_17:
				switch(NCode)
				{
					case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						Current_input->change_item = GAIN_HIGH_Item_Out;
						Time_add_dec(&Current_input->data.GAIN_DATA_HIGH,InvaliRect_Value[GAIN_HIGH_Item_Out],&Current_input->hItime,Six_Time_right,pMsg);
	
					break;
					
					//已释放按钮
					case WM_NOTIFICATION_RELEASED:
						Time_end(&Current_input->Time_count,Current_input->hItime);
					break;
				}
				break;
			
			
		}
		break;
	/********************************************END*********************************************/
	/********************************定时器**********************************/
	case WM_TIMER:	
		switch(WM_GetTimerId(pMsg->Data.v))  //根据不同定时器的ID号来处理不同的信息
		{
			case First_Time_left:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3)))
				{
					Current_input->change_item = TYPE_LOW_Item_Out;
					Time_long_press(pMsg,&Current_input->data.TYPE_DATA_LOW,&Current_input->Time_count,InvaliRect_Value[TYPE_LOW_Item_Out],First_Time_left);
				}
				break;
				
			case Second_Time_left:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4)))
				{
					Current_input->change_item = FREQ_LOW_Item_Out;
					Time_long_press(pMsg,&Current_input->data.FREQ_DATA_LOW,&Current_input->Time_count,InvaliRect_Value[FREQ_LOW_Item_Out],Second_Time_left);
				}
				break;
				
			case Third_Time_left:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5)))
				{
					Current_input->change_item = GAIN_LOW_Item_Out;
					Time_long_press(pMsg,&Current_input->data.GAIN_DATA_LOW,&Current_input->Time_count,InvaliRect_Value[GAIN_LOW_Item_Out],Third_Time_left);
				}
				break;
				
			case First_Time_right:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_6)))
				{
					Current_input->change_item = TYPE_LOW_Item_Out;
					Time_long_press(pMsg,&Current_input->data.TYPE_DATA_LOW,&Current_input->Time_count,InvaliRect_Value[TYPE_LOW_Item_Out],First_Time_right);
				}
				break;
				
			case Second_Time_right:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_7)))
				{
					Current_input->change_item = FREQ_LOW_Item_Out;
					Time_long_press(pMsg,&Current_input->data.FREQ_DATA_LOW,&Current_input->Time_count,InvaliRect_Value[FREQ_LOW_Item_Out],Second_Time_right);
				}
				break;
				
			case Third_Time_right:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_8)))
				{
					Current_input->change_item = GAIN_LOW_Item_Out;
					Time_long_press(pMsg,&Current_input->data.GAIN_DATA_LOW,&Current_input->Time_count,InvaliRect_Value[GAIN_LOW_Item_Out],Third_Time_right);
				}
				break;
				
			case Four_Time_left:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_12)))
				{
					Current_input->change_item = TYPE_HIGH_Item_Out;
					Time_long_press(pMsg,&Current_input->data.TYPE_DATA_HIGH,&Current_input->Time_count,InvaliRect_Value[TYPE_HIGH_Item_Out],Four_Time_left);
				}
				break;
				
			case Five_Time_left:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_13)))
				{
					Current_input->change_item = FREQ_HIGH_Item_Out;
					Time_long_press(pMsg,&Current_input->data.FREQ_DATA_HIGH,&Current_input->Time_count,InvaliRect_Value[FREQ_HIGH_Item_Out],Five_Time_left);
				}
				break;
				
			case Six_Time_left:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_14)))
				{
					Current_input->change_item = GAIN_HIGH_Item_Out;
					Time_long_press(pMsg,&Current_input->data.GAIN_DATA_HIGH,&Current_input->Time_count,InvaliRect_Value[GAIN_HIGH_Item_Out],Six_Time_left);
				}
				break;
				
			case Four_Time_right:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_15)))
				{
					Current_input->change_item = TYPE_HIGH_Item_Out;
					Time_long_press(pMsg,&Current_input->data.TYPE_DATA_HIGH,&Current_input->Time_count,InvaliRect_Value[TYPE_HIGH_Item_Out],Four_Time_right);
				}
				break;
				
			case Five_Time_right:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_16)))
				{
					Current_input->change_item = FREQ_HIGH_Item_Out;
					Time_long_press(pMsg,&Current_input->data.FREQ_DATA_HIGH,&Current_input->Time_count,InvaliRect_Value[FREQ_HIGH_Item_Out],Five_Time_right);
				}
				break;
				
			case Six_Time_right:
				if(BUTTON_IsPressed(WM_GetDialogItem(pMsg->hWin,ID_BUTTON_17)))
				{
					Current_input->change_item = GAIN_HIGH_Item_Out;
					Time_long_press(pMsg,&Current_input->data.GAIN_DATA_HIGH,&Current_input->Time_count,InvaliRect_Value[GAIN_HIGH_Item_Out],Six_Time_right);
				}
				break;
				
			
		}
		break;
		
	case WM_PAINT:
		GUI_SetBkColor(GUI_BLACK);
		GUI_Clear();

		//标题项
		GUI_SetColor(GUI_RED);
		GUI_FillRoundedRect(0, 0, 400, 30, 4);

	
		GUI_SetColor(GUI_BLUE);
		GUI_FillRoundedRect(0, 34, 400, 64, 4);
		//LOW PASS
		GUI_FillRoundedRect(0, 68, 198, 98, 4);
		//HIGHT PASS
		GUI_FillRoundedRect(202, 68, 398, 98, 4);

		//LOW-HIGH
		GUI_FillRoundedRect(0, 204, 98, 234, 4);
		GUI_FillRoundedRect(202, 204, 298, 234, 4);
		//INVERT
		GUI_FillRoundedRect(102, 204, 198, 234, 4);
		GUI_FillRoundedRect(304, 204, 396, 234, 4);

		//白色条
		GUI_SetColor(GUI_WHITE);
		GUI_FillRoundedRect(102, 102, 198, 132, 4);
		GUI_FillRoundedRect(102, 136, 198, 166, 4);
		GUI_FillRoundedRect(102, 170, 198, 200, 4);


		GUI_FillRoundedRect(304, 102, 396, 132, 4);
		GUI_FillRoundedRect(304, 136, 396, 166, 4);
		GUI_FillRoundedRect(304, 170, 396, 200, 4);
		
		//显示各个子选项数值
		Show_Value();
		
		break;
		
	/*********************************************自定义信息处理**************************************************/
	//旋钮左转
	case MSG_KNOB_CONTROL_LEFT:
		//子选项指示
//		if(Current_input->Item == INVERT_HIGH_Item_Out)
//		{
//			Current_input->Item = TYPE_LOW_Item_Out;
//		}
//		else
//		{
//			Current_input->Item++;
//		}
		Item_change(&(Current_input->Item),TYPE_LOW_Item_Out,INVERT_HIGH_Item_Out,Next_dir);
		GUI_SendKeyMsg(GUI_KEY_TAB, 1);     //下一个聚焦点
		break;
	
	//旋钮右转
	case MSG_KNOB_CONTROL_RIGHT:
//		if(Current_input->Item == TYPE_LOW_Item_Out)
//		{
//			Current_input->Item = INVERT_HIGH_Item_Out;
//		}
//		else
//		{
//			Current_input->Item--;
//		}
		Item_change(&(Current_input->Item),TYPE_LOW_Item_Out,INVERT_HIGH_Item_Out,Last_dir);
		GUI_SendKeyMsg(GUI_KEY_BACKTAB, 1); //上一个聚焦
		break;
		
	//CONTROL按下
	case MSG_KEY_CONTROL:
		if((Current_input->Item == INVERT_LOW_Item_Out)   
			||(Current_input->Item == INVERT_HIGH_Item_Out)) //IN_MUTE_Item和IN_INVERT_Item项
		{
			GUI_SendKeyMsg(GUI_KEY_SPACE,1);
		}
		else
		{
			GUI_SendKeyMsg(GUI_KEY_ENTER, 1);   //确定
		}
		break;
		
	//没有旋钮动作
	case MSG_KNOB_NULL:
		Current_input->Key_count = 0;
		Current_input->dir	=	0;
		break;
	
	//ESC
	case MSG_KEY_ESC:
		GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
        hWin_now = Input_First();  //显示Input_First页面
//		INPUT_CHANNEL = 1;
		break;
	
	//页面切换
	case MSG_KNOB_OUT_LEFT:	
		GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
		hWin_now = Input_Second();      //切换下一个界面
		break;
	
	case MSG_KNOB_OUT_RIGHT:
		GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
		hWin_now = Input_Third();      //切换上一个界面
		break;
	
	//INPUT右转
	case MSG_KNOB_INPUT_RIGHT:  
		if(Current_input->dir == 2)
		{
			Current_input->Key_count = 0;
		}
		Current_input->dir = 1;
		switch(Current_input->Item)
		{
			//值减少
			case TYPE_LOW_Item_Out:
				Current_input->change_item = Current_input->Item;
				Value_Change_dec(&Current_input->data.TYPE_DATA_LOW,&Current_input->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[TYPE_LOW_Item_Out]); //无效化该区域重新刷新
				break;
			
			case FREQ_LOW_Item_Out:
				Current_input->change_item = Current_input->Item;
				Value_Change_dec(&Current_input->data.FREQ_DATA_LOW,&Current_input->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[FREQ_LOW_Item_Out]); //无效化该区域重新刷新
				break;
			
			case GAIN_LOW_Item_Out:
				Current_input->change_item = Current_input->Item;
				Value_Change_dec(&Current_input->data.GAIN_DATA_LOW,&Current_input->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[GAIN_LOW_Item_Out]); //无效化该区域重新刷新
				break;
			
			//值减少
			case TYPE_HIGH_Item_Out:
				Current_input->change_item = Current_input->Item;
				Value_Change_dec(&Current_input->data.TYPE_DATA_HIGH,&Current_input->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[TYPE_HIGH_Item_Out]); //无效化该区域重新刷新
				break;
			
			case FREQ_HIGH_Item_Out:
				Current_input->change_item = Current_input->Item;
				Value_Change_dec(&Current_input->data.FREQ_DATA_HIGH,&Current_input->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[FREQ_HIGH_Item_Out]); //无效化该区域重新刷新
				break;
			
			case GAIN_HIGH_Item_Out:
				Current_input->change_item = Current_input->Item;
				Value_Change_dec(&Current_input->data.GAIN_DATA_HIGH,&Current_input->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[GAIN_HIGH_Item_Out]); //无效化该区域重新刷新
				break;
			
			
		}
		break;
		
	case MSG_KNOB_INPUT_LEFT:  
		if(Current_input->dir == 1)
		{
			Current_input->Key_count = 0;
		}
		Current_input->dir = 2;
		switch(Current_input->Item)
		{
			//值增加
			case TYPE_LOW_Item_Out:
				Current_input->change_item = Current_input->Item;
				Value_Change_add(&Current_input->data.TYPE_DATA_LOW,&Current_input->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[TYPE_LOW_Item_Out]); //无效化该区域重新刷新
				break;
			
			case FREQ_LOW_Item_Out:
				Current_input->change_item = Current_input->Item;
				Value_Change_add(&Current_input->data.FREQ_DATA_LOW,&Current_input->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[FREQ_LOW_Item_Out]); //无效化该区域重新刷新
				break;
			
			case GAIN_LOW_Item_Out:
				Current_input->change_item = Current_input->Item;
				Value_Change_add(&Current_input->data.GAIN_DATA_LOW,&Current_input->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[GAIN_LOW_Item_Out]); //无效化该区域重新刷新
				break;
			
			//值增加
			case TYPE_HIGH_Item_Out:
				Current_input->change_item = Current_input->Item;
				Value_Change_add(&Current_input->data.TYPE_DATA_HIGH,&Current_input->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[TYPE_HIGH_Item_Out]); //无效化该区域重新刷新
				break;
			
			case FREQ_HIGH_Item_Out:
				Current_input->change_item = Current_input->Item;
				Value_Change_add(&Current_input->data.FREQ_DATA_HIGH,&Current_input->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[FREQ_HIGH_Item_Out]); //无效化该区域重新刷新
				break;
			
			case GAIN_HIGH_Item_Out:
				Current_input->change_item = Current_input->Item;
				Value_Change_add(&Current_input->data.GAIN_DATA_HIGH,&Current_input->Key_count);
				WM_InvalidateRect(pMsg->hWin, InvaliRect_Value[GAIN_HIGH_Item_Out]); //无效化该区域重新刷新
				break;
			
			
		}
		break;	
	/*********************************END***************************************/
	//释放内存
	case WM_DELETE:
//		myfree(0,Current_input);
		break;
	
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
static void Init_data(Input_Five_data *L)
{
	L->face_switch		=		INPUT_CHANNEL;
	L->Item				=		TYPE_LOW_Item_Out;
	L->String			=		face_string[INPUT_CHANNEL];
	L->Time_count		=		0;
	L->hItime			=		0;
	L->Key_count		=		0;
	L->checkbox_sta		=		0;
	L->change_item		=		-1;
	L->overflow			=		0;
	
	//数据初始化
//	L->data.RMSTC_DATA  =		0;
//	L->data.DECAY_DATA	=		0;
//	L->data.THRSH_DATA	=		0;
//	L->data.OUT_INVERT_STA 	=	0;
//	L->data.OUT_MUTE_STA	=	0;
//	L->data.DELAY_DATA	=		0;
//	AT24C16_PageRead((u8 *)(&(L->data)),IIC_Addr[L->face_switch+30],sizeof(L->data));
	
	//当复选框状态大于1时要初始化
	Checkbox_Init(&(L->data.LOW_HIGH_STA));
	Checkbox_Init(&(L->data.INVERT_LOW_STA));
	Checkbox_Init(&(L->data.MID_HIGH_STA));
	Checkbox_Init(&(L->data.INVERT_HIGH_STA));
	
}

WM_HWIN Input_Five(void) {
	WM_HWIN hWin;
	
	//申请动态内存
//	Out_Third = (Output_Third_Data *)mymalloc(0,sizeof(Output_Third_Data));
//	
//	if(Out_Third == NULL)
//	{
//		return 0;
//	}
//	else
//	{

//		Init_data(Out_Third);
//	}
//	
	Init_data(In_Five[INPUT_CHANNEL]);
	Current_input = In_Five[INPUT_CHANNEL];
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
