/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "data.h"
#include "algorithm.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_PROGBAR_0 (GUI_ID_USER + 0x01)
#define ID_PROGBAR_1 (GUI_ID_USER + 0x02)
#define ID_PROGBAR_2 (GUI_ID_USER + 0x03)
#define ID_PROGBAR_3 (GUI_ID_USER + 0x04)
#define ID_PROGBAR_4 (GUI_ID_USER + 0x05)
#define ID_PROGBAR_5 (GUI_ID_USER + 0x06)
#define ID_PROGBAR_6 (GUI_ID_USER + 0x07)
#define ID_PROGBAR_7 (GUI_ID_USER + 0x08)
#define ID_PROGBAR_8 (GUI_ID_USER + 0x09)
#define ID_PROGBAR_9 (GUI_ID_USER + 0x0A)
#define ID_PROGBAR_10 (GUI_ID_USER + 0x0B)
#define ID_PROGBAR_11 (GUI_ID_USER + 0x0C)
#define ID_PROGBAR_12 (GUI_ID_USER + 0x0D)
#define ID_PROGBAR_13 (GUI_ID_USER + 0x0E)
#define ID_TEXT_0 (GUI_ID_USER + 0x0F)
#define ID_TEXT_1 (GUI_ID_USER + 0x10)
#define ID_TEXT_2 (GUI_ID_USER + 0x11)
#define ID_TEXT_3 (GUI_ID_USER + 0x12)
#define ID_TEXT_4 (GUI_ID_USER + 0x13)
#define ID_TEXT_5 (GUI_ID_USER + 0x14)
#define ID_TEXT_6 (GUI_ID_USER + 0x15)
#define ID_TEXT_7 (GUI_ID_USER + 0x16)
#define ID_TEXT_8 (GUI_ID_USER + 0x17)
#define ID_TEXT_9 (GUI_ID_USER + 0x18)
#define ID_TEXT_10 (GUI_ID_USER + 0x19)
#define ID_TEXT_11 (GUI_ID_USER + 0x1A)
#define ID_TEXT_12 (GUI_ID_USER + 0x1B)
#define ID_TEXT_13 (GUI_ID_USER + 0x1C)
#define ID_PROGBAR_14 (GUI_ID_USER + 0x1D)
#define ID_PROGBAR_15 (GUI_ID_USER + 0x1E)
#define ID_TEXT_14 (GUI_ID_USER + 0x1F)
#define ID_TEXT_15 (GUI_ID_USER + 0x20)



static void huadong(WM_MESSAGE* pMsg);
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static Meter_First_Data * Current_Data;
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
	{ WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 400, 240, 0, 0x0, 0 },
	
	//INPUT
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 0,    40+5, 20, 168, 1, 0x0, 0 },
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_1, 25,   40+5, 20, 168, 1, 0x0, 0 },
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_2, 50,   40+5, 20, 168, 1, 0x0, 0 },
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_3, 75,   40+5, 20, 168, 1, 0x0, 0 },
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_4, 100,  40+5, 20, 168, 1, 0x0, 0 },
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_5, 125,  40+5, 20, 168, 1, 0x0, 0 },
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_6,  150, 40+5, 20, 168, 1, 0x0, 0 },
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_7,  175, 40+5, 20, 168, 1, 0x0, 0 },
	                                                           
	//OUTPUT                                                   
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_8,  200, 40+5, 20, 168, 1, 0x0, 0 },
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_9,  225, 40+5, 20, 168, 1, 0x0, 0 },
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_10, 250, 40+5, 20, 168, 1, 0x0, 0 },
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_11, 275, 40+5, 20, 168, 1, 0x0, 0 },
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_12, 300, 40+5, 20, 168, 1, 0x0, 0 },
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_13, 325, 40+5, 20, 168, 1, 0x0, 0 },
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_14, 350, 40+5, 20, 168, 1, 0x0, 0 },
	{ PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_15, 375, 40+5, 20, 168, 1, 0x0, 0 },

	{ TEXT_CreateIndirect, "Text", ID_TEXT_0,  5,   215+5, 9, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_1,  32,  215+5, 9, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_2,  57,  215+5, 9, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_3,  83,  215+5, 9, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_4,  107, 215+5, 9, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_5,  133, 215+5, 9, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_6,  159, 215+5, 9, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_7,  183, 215+5, 9, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_8,  207, 215+5, 9, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_9,  232, 215+5, 9, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_10, 258, 215+5, 9, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_11, 285, 215+5, 9, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_12, 309, 215+5, 9, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_13, 333, 215+5, 9, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_14, 358, 215+5, 9, 20, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_15, 382, 215+5, 9, 20, 0, 0x64, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
#define ID_TIMER_SPEC 0
#define METER_MAX  0
#define METER_MIN  -9600
//放大倍数
#define largen  100
//电平显示
static void meter_show(WM_HWIN htem,s16 value)
{
	htem = htem;
	value = value;
	
//	if(value != 0)
//	{
//		PROGBAR_SetValue(htem,value);
//	}
//	else
//	{
//		PROGBAR_SetValue(htem,METER_MIN);
//	}
	
	PROGBAR_SetValue(htem,value);
}

//显示数值

static const GUI_RECT pRect[]=
{
	{0,0,400,30},
};
void Show_Value(s16 value_input,s16 value_output)
{
	GUI_SetColor(GUI_BLACK); 		//设置颜色
	GUI_SetFont(&GUI_Font20_1); 	//设置字体
	GUI_GotoXY(0, 0);  				//设置位置
	GUI_DispDecMin(value_input/largen);
	
	GUI_GotoXY(200, 0);  				//设置位置
	GUI_DispDecMin(value_output/largen);
}

static void _cbDialog(WM_MESSAGE * pMsg) {
	WM_HWIN hItem;
	int     Id;
	// USER START (Optionally insert additional variables)
	// USER END

	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		Current_Data->hItime = WM_CreateTimer(pMsg->hWin, ID_TIMER_SPEC, 20, 0);	
		//进度条
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_IN1 = hItem;
	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_1);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_IN2 = hItem;
	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_2);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_IN3 = hItem;
	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_3);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_IN4 = hItem;
	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_4);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_IN5 = hItem;
	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_5);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_IN6 = hItem;
	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_6);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_COAL = hItem;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_7);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_COAR = hItem;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_8);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_OUT1 = hItem;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_9);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_OUT2 = hItem;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_10);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_OUT3 = hItem;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_11);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_OUT4 = hItem;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_12);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_OUT5 = hItem;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_13);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_OUT6 = hItem;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_14);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_OUT7 = hItem;
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_15);
		PROGBAR_SetMinMax(hItem,METER_MIN,METER_MAX);
		PROGBAR_SetValue(hItem,METER_MIN);
		Current_Data->hItem_OUT8 = hItem;
		
		//
		// Initialization of 'Window'
		//
		hItem = pMsg->hWin;
		WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x00000000));
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		TEXT_SetText(hItem, "1");
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		TEXT_SetText(hItem, "2");
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		TEXT_SetText(hItem, "3");
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		TEXT_SetText(hItem, "4");
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		TEXT_SetText(hItem, "5");
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		TEXT_SetText(hItem, "6");
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		TEXT_SetText(hItem, "L");
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
		TEXT_SetText(hItem, "R");
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		TEXT_SetText(hItem, "1");
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_9);
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		TEXT_SetText(hItem, "2");
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_10);
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		TEXT_SetText(hItem, "3");
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_11);
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		TEXT_SetText(hItem, "4");
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_12);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		TEXT_SetText(hItem, "5");
		//
		// Initialization of 'Text'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_13);
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		TEXT_SetText(hItem, "6");
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_14);
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		TEXT_SetText(hItem, "7");
		
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_15);
		TEXT_SetFont(hItem, GUI_FONT_16B_1);
		TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00FFFFFF));
		TEXT_SetText(hItem, "8");
		// USER START (Optionally insert additional code for further widget initialization)
		// USER END
		break;
		// USER START (Optionally insert additional message handling)
		// USER END
	/* 定时器回调消息 */
	case WM_TIMER:
		Id = WM_GetTimerId(pMsg->Data.v);
		switch (Id) 
		{
			/* 时间到了更新电平显示 */
			case ID_TIMER_SPEC:
				//输入电平
				Current_Data->data.INPUT_1_METER = meter(IN1_METER_ADDR)  *largen;//输入电平指示
				Current_Data->data.INPUT_2_METER = meter(IN2_METER_ADDR)  *largen;//输入电平指示
				Current_Data->data.INPUT_3_METER = meter(IN3_METER_ADDR)  *largen;//输入电平指示
				Current_Data->data.INPUT_4_METER = meter(IN4_METER_ADDR)  *largen;//输入电平指示
				Current_Data->data.INPUT_5_METER = meter(IN5_METER_ADDR)  *largen;//输入电平指示
				Current_Data->data.INPUT_6_METER = meter(IN6_METER_ADDR)  *largen;//输入电平指示
				Current_Data->data.COAX_L_METER = meter(COAX_L_METER_ADDR)*largen;//输入电平指示
				Current_Data->data.COAX_R_METER = meter(COAX_R_METER_ADDR)*largen;//输入电平指示
				
				//输出电平
				Current_Data->data.OUTPUT1_METER = meter(OUT1_METER_ADDR)*largen;//输出电平指示  
				Current_Data->data.OUTPUT2_METER = meter(OUT2_METER_ADDR)*largen;//输出电平指示
				Current_Data->data.OUTPUT3_METER = meter(OUT3_METER_ADDR)*largen;//输出电平指示
				Current_Data->data.OUTPUT4_METER = meter(OUT4_METER_ADDR)*largen;//输出电平指示
				Current_Data->data.OUTPUT5_METER = meter(OUT5_METER_ADDR)*largen;//输出电平指示
				Current_Data->data.OUTPUT6_METER = meter(OUT6_METER_ADDR)*largen;//输出电平指示
				Current_Data->data.OUTPUT7_METER = meter(OUT7_METER_ADDR)*largen;//输出电平指示
				Current_Data->data.OUTPUT8_METER = meter(OUT8_METER_ADDR)*largen;//输出电平指示
				
				//设置值
//				Value+=10;
//				if(Value > 0)
//				{
//					Value = -4500;
//				}
//				meter_show(Current_Data->hItem_IN1, Value);
//				meter_show(Current_Data->hItem_IN2, Value);
//				meter_show(Current_Data->hItem_IN3, Value);
//				meter_show(Current_Data->hItem_IN4, Value);
//				meter_show(Current_Data->hItem_IN5, Value);
//				meter_show(Current_Data->hItem_IN6, Value);
//				meter_show(Current_Data->hItem_COAL,Value);
//				meter_show(Current_Data->hItem_COAR,Value);
//				
//				//输出
//				meter_show(Current_Data->hItem_OUT1,Current_Data->data.OUTPUT1_METER);
//				meter_show(Current_Data->hItem_OUT2,Current_Data->data.OUTPUT2_METER);
//				meter_show(Current_Data->hItem_OUT3,Current_Data->data.OUTPUT3_METER);
//				meter_show(Current_Data->hItem_OUT4,Current_Data->data.OUTPUT4_METER);
//				meter_show(Current_Data->hItem_OUT5,Current_Data->data.OUTPUT5_METER);
//				meter_show(Current_Data->hItem_OUT6,Current_Data->data.OUTPUT6_METER);
//				meter_show(Current_Data->hItem_OUT7,Current_Data->data.OUTPUT7_METER);
//				meter_show(Current_Data->hItem_OUT8,Current_Data->data.OUTPUT8_METER);
				
				//输入
				meter_show(Current_Data->hItem_IN1,Current_Data->data.INPUT_1_METER);
				meter_show(Current_Data->hItem_IN2,Current_Data->data.INPUT_2_METER);
				meter_show(Current_Data->hItem_IN3,Current_Data->data.INPUT_3_METER);
				meter_show(Current_Data->hItem_IN4,Current_Data->data.INPUT_4_METER);
				meter_show(Current_Data->hItem_IN5,Current_Data->data.INPUT_5_METER);
				meter_show(Current_Data->hItem_IN6,Current_Data->data.INPUT_6_METER);
				meter_show(Current_Data->hItem_COAL,Current_Data->data.COAX_L_METER);
				meter_show(Current_Data->hItem_COAR,Current_Data->data.COAX_R_METER);
				
				//输出
				meter_show(Current_Data->hItem_OUT1,Current_Data->data.OUTPUT1_METER);
				meter_show(Current_Data->hItem_OUT2,Current_Data->data.OUTPUT2_METER);
				meter_show(Current_Data->hItem_OUT3,Current_Data->data.OUTPUT3_METER);
				meter_show(Current_Data->hItem_OUT4,Current_Data->data.OUTPUT4_METER);
				meter_show(Current_Data->hItem_OUT5,Current_Data->data.OUTPUT5_METER);
				meter_show(Current_Data->hItem_OUT6,Current_Data->data.OUTPUT6_METER);
				meter_show(Current_Data->hItem_OUT7,Current_Data->data.OUTPUT7_METER);
				meter_show(Current_Data->hItem_OUT8,Current_Data->data.OUTPUT8_METER);
				
//				PROGBAR_SetValue(Current_Data->hItem_IN1,Current_Data->data.INPUT_1_METER);
//				PROGBAR_SetValue(Current_Data->hItem_IN2,Current_Data->data.INPUT_2_METER);
//				PROGBAR_SetValue(Current_Data->hItem_IN3,Current_Data->data.INPUT_3_METER);
//				PROGBAR_SetValue(Current_Data->hItem_IN4,Current_Data->data.INPUT_4_METER);
//				PROGBAR_SetValue(Current_Data->hItem_IN5,Current_Data->data.INPUT_5_METER);
//				PROGBAR_SetValue(Current_Data->hItem_IN6,Current_Data->data.INPUT_6_METER);
//				PROGBAR_SetValue(Current_Data->hItem_COAL,Current_Data->data.COAX_L_METER);
//				PROGBAR_SetValue(Current_Data->hItem_COAR,Current_Data->data.COAX_R_METER);
//				
//				//输出
//				PROGBAR_SetValue(Current_Data->hItem_OUT1,Current_Data->data.OUTPUT1_METER);
//				PROGBAR_SetValue(Current_Data->hItem_OUT2,Current_Data->data.OUTPUT2_METER);
//				PROGBAR_SetValue(Current_Data->hItem_OUT3,Current_Data->data.OUTPUT3_METER);
//				PROGBAR_SetValue(Current_Data->hItem_OUT4,Current_Data->data.OUTPUT4_METER);
//				PROGBAR_SetValue(Current_Data->hItem_OUT5,Current_Data->data.OUTPUT5_METER);
//				PROGBAR_SetValue(Current_Data->hItem_OUT6,Current_Data->data.OUTPUT6_METER);
//				PROGBAR_SetValue(Current_Data->hItem_OUT7,Current_Data->data.OUTPUT7_METER);
//				PROGBAR_SetValue(Current_Data->hItem_OUT8,Current_Data->data.OUTPUT8_METER);
//				WM_InvalidateRect(hWin_now,&pRect[0]);
				WM_RestartTimer(pMsg->Data.v, 20);				
				break;
		}
		break;
		
	case WM_PAINT:

		//标题项
		GUI_SetColor(GUI_RED);
		GUI_FillRoundedRect(0, 2, 197, 36, 4);
		GUI_FillRoundedRect(199, 2, 398, 36, 4);
		GUI_SetPenSize(3);

		GUI_SetColor(GUI_BLUE);
		GUI_FillRoundedRect(0, 38, 400, 240, 4);


		GUI_SetColor(GUI_WHITE);
		GUI_SetFont(GUI_FONT_24B_1);
		GUI_SetTextMode(GUI_TEXTMODE_TRANS);
		GUI_DispStringHCenterAt("INPUT_METER",100,7);
		GUI_DispStringHCenterAt("OUTPUT_METER", 300, 7);
	
		//显示数值
//		Show_Value(Current_Data->data.INPUT_1_METER,Current_Data->data.OUTPUT1_METER);
		break;
	/**********************************自定义信息**********************************/
	case MSG_SLIDER_L:
		GUI_EndDialog(pMsg->hWin, 0); //结束本界面
		hWin_now = CreateMainface(); //显示INPUT第一个界面
		break;
	
	case MSG_SLIDER_R:
		GUI_EndDialog(pMsg->hWin, 0); //结束本界面
		hWin_now = RTA_Show(); //显示INPUT第一个界面
		break;
	
	//页面切换
	case MSG_KNOB_OUT_LEFT:	
		GUI_EndDialog(pMsg->hWin, 0); //结束本界面
		hWin_now = RTA_Show(); //显示界面
		break;
	
	case MSG_KNOB_OUT_RIGHT:
		GUI_EndDialog(pMsg->hWin, 0);   //结束当前界面
		hWin_now = CreateMainface();      //切换下一个界面
		break;
	
	//INPUT
	case MSG_KEY_INPUT:
        GUI_EndDialog(pMsg->hWin, 0); //结束本界面
		hWin_now = Input_First(); //显示INPUT第一个界面
		break;
	
	//OUTPUT
	case MSG_KEY_OUTPUT:
        GUI_EndDialog(pMsg->hWin, 0); //结束本界面
		hWin_now = Output_First(); //显示INPUT第一个界面
		break;
	
	//ESC
	case MSG_KEY_ESC:
		GUI_EndDialog(pMsg->hWin, 0); //关闭当前窗口
		hWin_now = CreateMainface();  //显示主页面
		break;
	
	//触摸测试
	case WM_TOUCH:
		huadong(pMsg);
		break;
	
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
void PROGBAR_self(void)
{
	PROGBAR_SKINFLEX_PROPS Props;
	PROGBAR_GetSkinFlexProps(&Props,0);
	//Props.aColorUpperL[0] = GUI_WHITE;
	Props.aColorUpperL[1] = GUI_LIGHTGREEN;
	//Props.aColorLowerL[0] = GUI_LIGHTGREEN;
	//Props.aColorLowerL[1] = GUI_GREEN;
	PROGBAR_SetSkinFlexProps(&Props, 0);
}

#define slider_direct  50
//滑动检测
static void huadong(WM_MESSAGE* pMsg)
{
	const GUI_PID_STATE* pState = (const GUI_PID_STATE*)pMsg->Data.p; //获得PID输入设备的数据
	int direct;
    if (pMsg->Data.p)    /* Something happened in our area (pressed or released) */
    {
        if (pState->Pressed)  //按下
        {
			if(Current_Data->touch_hua == 0)
			{
				Current_Data->touch_hua = 1;
				Current_Data->touch_x_last 	= pState->x;
				Current_Data->touch_y_last	= pState->y;
			}
		}
		else  //释放
		{
			Current_Data->touch_hua = 0;
			Current_Data->touch_x_current 	= pState->x;
			Current_Data->touch_y_current	= pState->y;
			direct = Current_Data->touch_x_current - Current_Data->touch_x_last;
			if(direct > slider_direct ) //滑动距离超过100个像素点
			{
				WM_SendMessageNoPara(hWin_now, MSG_SLIDER_R);
			}
			else if(direct<-slider_direct)
			{
				WM_SendMessageNoPara(hWin_now, MSG_SLIDER_L);
			}

		}
	}
}

static void Init_data(Meter_First_Data *L)
{
	L->touch_hua = 0;
	
}

WM_HWIN Meter_Show(void) {
	WM_HWIN hWin;

	Init_data(Meter_first);
	Current_Data = Meter_first;
	
	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
